### ISSUE TITLE
failed to load external entity

### ISSUE THREAD

**Issue by AndreKR** [phpDocumentor/phpDocumentor2#1026]
When I try running phpdoc with one of the non-twig templates, for example like this:

`..\php\php ..\phpdoc\phpDocumentor.phar --template="responsive"`

I get the following message:

> [phpDocumentor\Plugin\Core\Exception]
>  Specified DOMDocument lacks documentElement, cannot transform.
>  Apparently an error occurred with reading the structure.xml file, the reported error was "failed to load external entity "phar%3A/D%3A/xampp/phpdoc/phpDocumentor.phar/data/templates/responsive/layout.xsl"" on line 0

Can this be related to theseer/phpdox#105?

**Comment by mvriel** [comment]
There has been no response and no new mentions of this issue; given I cannot reproduce it I will close this issue

**Comment by websmurf** [comment]
I'm having the same issue on osx recently. Haven't been able to find much about this on the internet either. I've installed phpdocumentor through homebrew (brew install phpdocumentor), but I'm having the same issue when downloading the phar file manually and executing that. 

The parser process goes successfull, this is the first part of the transformer step:

>Load cache                                                         ..    0.029s
>Preparing template "responsive"                                    ..    0.008s
>Preparing 13 transformations                                       ..    0.000s
>Build "elements" index                                             ..    0.001s
>Replace textual FQCNs with object aliases                          ..    0.011s
>Resolve @link and @see tags in descriptions                        ..    0.001s
>Enriches inline example tags with their sources                    ..    0.001s
>Build "packages" index                                             ..    0.001s
>Build "namespaces" index and add namespaces to "elements"          ..    0.010s
>Collect all markers embedded in tags                               ..    0.001s
>Transform analyzed project into artifacts                          .. 
>Applying 13 transformations
>  Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\FileIo"
>  Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\Xml"
>  Initialize writer "phpDocumentor\Plugin\Core\Transformer\Writer\Xsl"
>  Initialize writer "phpDocumentor\Plugin\Graphs\Writer\Graph"
>  Execute transformation using writer "FileIo"
>  Execute transformation using writer "FileIo"
>  Execute transformation using writer "FileIo"
>  Execute transformation using writer "xml"
>  Execute transformation using writer "xsl"
>I/O warning : failed to load external entity >"phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/layout.xsl"
>PHP Warning:  XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar:///usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307
>
>Warning: XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar:///usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307
  Execute transformation using writer "xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/layout.xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/elements/common.xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/elements/namespace.xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/elements/class.xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/elements/constant.xsl"
I/O warning : failed to load external entity "phar:/usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/data/templates/responsive/elements/function.xsl"
PHP Warning:  XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar:///usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307
>
>Warning: XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar:///usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307
PHP Warning:  XSLTProcessor::transformToUri(): No stylesheet associated to this object in phar:///usr/local/Cellar/phpdocumentor/2.9.0/libexec/phpDocumentor.phar/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xsl.php on line 307

The last part is repeated a load of times. 
The only template that does work, is the clean template

**Comment by theseer** [comment]
I'm having the same issue with phpDox (https://github.com/theseer/phpdox/issues/255) for users under MacOS (and windows).

So far, I was equally unable to figure out why that happens exactly. An assumption would be that for whatever reason the stream wrapper handling is broken with libxml/libxsl on OSX.

That might be a PHP Bug as it works on Linux or a general limitation on OSX.

For now, the only workaround for the affected platforms is to not use the phar version or extract the templates.

Side note: The OS X problem seems to be independent of the problem this bug originally was about. OS X' libxml/libxslt cannot resolve a perfectly valid (stream-wrapped) path, the Windows problem looks more like a garbled path that cannot technically work. Same effect, different cause.
