### ISSUE TITLE
Generate - Static Help Pages (e.g. Readme, Install, Misc, Contact etc...)

### ISSUE THREAD

**Issue by rooseveltrp** [phpDocumentor/phpDocumentor2#1053]
Hi,

phpDocumentor2 is the best documentation wizard I ever came across. It already accomplishes a lot in terms of generating an API for an application. However, it will be nice if it could kill two birds with one stone.

I read in one of the posts phpDocumentor wants to or has plans to support Sphinx. It will be nice if phpDocumentor2 could read a directory for static pages (e.g. written in markdown syntax) and spit out a nice user manual using the same phpdocumentor2 template. I want to avoid dependency on Python or Sphinx just to generate a User Manual.

So, the API and the read me would have the same layout and possibly linked to each other.

Do you already have something in progress? If not I plan on forking and adding the little generator myself :smiley:. phpDocumentor2 already supports Markdown... so I don't think it will be too much trouble.

**Comment by mvriel** [comment]
Will be fixed in phpDocumentor 3
