### ISSUE TITLE
package (rpm) phpDocumentor

### ISSUE THREAD

**Issue by spuhler** [phpDocumentor/phpDocumentor2#1116]
I have a couple questions/problem with deps. After making an rpm (spec made from macro pear-make-rpm-spec) and trying to install the rpm I get the following dep problems:
error: Failed dependencies:
        pear(%path%foo.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
        pear(CodeSniffer/Core/AllTests.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
        pear(CodeSniffer/Standards/AllSniffs.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
        pear(PHPUnit/Extensions/OutputTestCase.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
        pear(phar:/ProjectWithXsdExtensionInPhar.phar/ProjectWithXsdExtensionInPhar.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch

I have php-pear-PHP_CodeSniffer installed. The files exist but are at:
/usr/share/pear/tests/PHP_CodeSniffer/CodeSniffer/Core/AllTests.php
/usr/share/pear/tests/PHP_CodeSniffer/CodeSniffer/Standards/AllSniffs.php
I don't know where these come from
pear(%path%foo.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
  pear(phar:/ProjectWithXsdExtensionInPhar.phar/ProjectWithXsdExtensionInPhar.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
pear(phar:/behat.phar/vendor/autoload.php)
pear(phar:/cilex.phar/vendor/autoload.php)
pear(test1.php)
pear(test2.php)
pear(test2.php)
pear(test3.php)
pear(test4.php) 
Then I miss this one too:
pear(PHPUnit/Extensions/OutputTestCase.php) is needed by php-pear-phpDocumentor-2.2.0-1.mga5.noarch
PHPUnit-3.7 doesn't provide it

Any help would be appreciated. If the files are not required, I can put an exception into the spec file.

**Comment by jaapio** [comment]
I'm closing this issue due inactivity of the creator.
