### ISSUE TITLE
Move GraphViz to its own plugin and do not include by default

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1185]
GraphViz has proved a hindrance when it comes to adoption and using phpDocumentor. By moving it to a separate plugin that is not enabled by default we hope to gain the following benefits:

- Increase ease of use after installation
- Reduce number of required dependencies

> Because this is a BC breaking change we intend to do this when moving to version 3.0

**Comment by mvriel** [comment]
Closing for now

**Comment by montogeek** [comment]
@mvriel GraphViz website is down. How can I install it?
