### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by corburn** [phpDocumentor/phpDocumentor2#1318]
http://www.soulbroken.co.uk/blog/2011/10/produce-a-checkstyle-report-for-doc-block-validation-with-docblox/ referenced in http://www.phpdoc.org/docs/latest/for-users/reporting/phpdoc-errors.html has been taken down.

**Comment by divayprakash** [comment]
@mvriel WHat exactly needs to be done here? I'd love to try my hand at it but I can't understand what needs to be done here.

**Comment by peterhuerlimann** [comment]
One could add https://web.archive.org/web/20131023172150/http://www.soulbroken.co.uk/2011/10/produce-a-checkstyle-report-for-doc-block-validation-with-docblox/ 
Though I am not sure if this still is an issue...

**Comment by corburn** [comment]
This is no longer an issue.
