### ISSUE TITLE
Missing js files on generated document

### ISSUE THREAD

**Issue by barguer** [phpDocumentor/phpDocumentor2#1407]
Hi
I've generated the docuementation for a project with version 2.7.0 using new-black template, but the document has been generated without any format. Icons are missing and all and the classes are empty, thoug I can access the source code.
http://snag.gy/4wuIZ.jpg
Inspecting the web looks like some js files have not been generated and the icons are missing too.
http://snag.gy/LqhLK.jpg

**Comment by jaapio** [comment]
@mbed67 was this issues solved?

**Comment by mbed67** [comment]
@jaapio this has been solved by PR's #24 and #25 on the abstract repository (when it was still a separate project)
