### ISSUE TITLE
Clean template does not generate classes when installed with Composer

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1427]
On IRC the user `BadCodSmell` has reported that when he installs phpDocumentor using Composer that the clean template runs as expected but no class documentation pages are generated. Even the /classes folder is absent.

the used command is

> phpdoc run --template=clean --filename=test3.php -t docs --title='Elvis Returns' --visibility=public -vvv

Both the PHAR and PEAR installation do not suffer from this issue and it is reported with both 2.7 and 2.6.1.

> This might be related to a version of PHP-Parser as BadCodSmell indicated that he uses that package.

**Comment by cmb69** [comment]
Apparently, the fix didn't make it to 2.8.2. I suggest to adjust the milestone accordingly.

**Comment by mrobinsonuk** [comment]
This evening I also encountered the same problem and I agree with @throup's description. I'm realise I'm not adding much, but I thought it may be helpful to add my observations.

Using phpDocumentor 2.8.2 installed via composer, if I also explicitly specify `phpdocumentor/reflection` `1.0.0`, `1.0.1`, `1.0.2` or `1.0.3` I receive `nikic/php-parser` `v1.3.0` as a dependency. In these cases, the generated HTML documentation is effectively empty.

When I specify `phpdocumentor/reflection` `1.0.4`, `1.0.5`, or `1.0.6` I instead receive `nikic/php-parser` `v0.9.4`, and with `phpdocumentor/reflection` `1.0.7` I receive `nikic/php-parser` `v0.9.5`. In these cases, the HTML documentation is generated just fine.

Would setting the minimum required version of `phpdocumentor/reflection` to `1.0.4` be a solution, or is there more to it than that?

**Comment by beporter** [comment]
Just a note, I'm still seeing this using `composer require phpdocumentor/phpdocumentor`. (This currently installs the [package version 2.8.4](https://packagist.org/packages/phpdocumentor/phpdocumentor#v2.8.4), even though the command line tool still reports v2.8.3.)

**Regardless of what template I choose**, there are no namespaces or classes listed in the generated HTML, only "stubbed" pages without any content in them, and strangely, the "Errors" page is populated properly.

```shell
$ composer info phpdocumentor/phpdocumentor
name     : phpdocumentor/phpdocumentor
descrip. : Documentation Generator for PHP
keywords : api, application, dga, documentation, phpdoc
versions : dev-master, 3.0.x-dev, * v2.8.4, v2.8.3, v2.8.2, v2.8.1, v2.8.0, v2.7.1, v2.7.0, v2.6.1, v2.6.0, v2.5.0, v2.4.0, v2.3.2, v2.3.1, v2.3.0, v2.2.0, v2.1.0, v2.0.1, v2.0.0, 2.0.0b7, v2.0.0b6, v2.0.0b5, v2.0.0b4, v2.0.0b3, v2.0.0b2, v2.0.0b1, 2.0.0a11, v2.0.0a10, v2.0.0a9, v2.0.0a8, v2.0.0a7, v2.0.0a5, 2.0.0a4, v2.0.0a3, dev-develop, dev-revert-1363-avoid-assert-true, dev-release-2.0.2, dev-release-2.0.1
type     : library
license  : MIT License (MIT) (OSI approved) http://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/phpDocumentor/phpDocumentor2.git 6d8f4c6381283dd2ae21efae30080adde9bfb1ba
dist     : [zip] https://api.github.com/repos/phpDocumentor/phpDocumentor2/zipball/6d8f4c6381283dd2ae21efae30080adde9bfb1ba 6d8f4c6381283dd2ae21efae30080adde9bfb1ba
names    : phpdocumentor/phpdocumentor

autoload
psr-0
phpDocumentor => src/, tests/unit/
Cilex\Provider => src/

requires
cilex/cilex ~1.0
erusev/parsedown ~1.0
herrera-io/phar-update 1.0.3
jms/serializer ~0.12
monolog/monolog ~1.6
php >=5.3.3
phpdocumentor/fileset ~1.0
phpdocumentor/graphviz ~1.0
phpdocumentor/reflection ~1.0
phpdocumentor/reflection-docblock ~2.0
symfony/config ~2.3
symfony/console ~2.3
symfony/event-dispatcher ~2.1
symfony/process ~2.0
symfony/stopwatch ~2.3
symfony/validator ~2.2
twig/twig ~1.3
zendframework/zend-cache ~2.1
zendframework/zend-config ~2.1
zendframework/zend-filter ~2.1
zendframework/zend-i18n ~2.1
zendframework/zend-serializer ~2.1
zendframework/zend-servicemanager ~2.1
zendframework/zend-stdlib ~2.1
zetacomponents/document >=1.3.1

requires (dev)
behat/behat ~3.0
mikey179/vfsstream ~1.2
mockery/mockery ~0.9@dev
phpunit/phpunit ~4.0
squizlabs/php_codesniffer ~1.4
symfony/expression-language ~2.4

suggests
ext-twig Enabling the twig extension improves the generation of twig based templates.
ext-xslcache Enabling the XSLCache extension improves the generation of xml based templates.


$ bin/phpdoc -V
phpDocumentor version 2.8.3
```
