### ISSUE TITLE
@var for compound statement isn't displayed correctly

### ISSUE THREAD

**Issue by camilstaps** [phpDocumentor/phpDocumentor2#1439]
I have a compound statement in one of my classes and as far as I know I'm following the [docs](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/var.html) here. This is just the relevant part of the file. The file itself and the class do have docblocks.

```
class contact {
    /**
     * @var PDO $pdo                The PDO class for database communication
     * @var int $id                 The id of the contact
     * @var int $clientId           The id of the client the contact is linked to
     * @var string $name            The name of the contact
     * @var string $address         The first address line (normally street and house number) of the contact
     * @var string $postal_code     The postal code of the contact
     * @var string $city            The city of the contact
     * @var string $state           The state or region of the contact
     * @var string $country         The country of the contact
     */
    protected $pdo, $id, $clientId, $name, $address, $postal_code, $city, $state, $country;
```

When I run phpdoc on this file, it's parsed fine without any output. However, when I look at the generated docs, the information isn't displayed correctly:

![enter image description here](http://i.stack.imgur.com/Cvg95.png)

Am I doing something wrong?

**Comment by jozwikjp** [comment]
it is in the documentation on 
[https://www.phpdoc.org/docs/latest/references/phpdoc/tags/var.html](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/var.html)

**Comment by camilstaps** [comment]
@jozwikjp what exactly is in the documentation?

**Comment by jozwikjp** [comment]
The '@var' documentation has example of multi line definitions with compound declarations.

``Even compound statements may be documented:
```
class Foo
{
  /**
   * @var string $name        Should contain a description
   * @var string $description Should contain a description
   */
  protected $name, $description;
}
```
``

**Comment by camilstaps** [comment]
@jozwikjp the point is that here all variables are listed as `PDO`, while only the first is.

**Comment by jozwikjp** [comment]
@camilstaps  I guess my point is the documentation does not match the functionality. So either is a is a documentation bug in the docs, or a bug in phpDocumentor2 not a improvement.

**Comment by camilstaps** [comment]
Cleaning up my issues list. I don't need this any more.
