### ISSUE TITLE
Inline @see should not always require FQSE; support "self" in tags

### ISSUE THREAD

**Issue by fi5er** [phpDocumentor/phpDocumentor2#1456]
Given the following example file in a namespaced source tree:

```
<?
namespace MyNS\Model\Cases;

class CaseNr
{
    /**
     * This is method one.
     *
     * - WORKS: see {@see \MyNS\Model\Cases\CaseNr::methodTwo() methodTwo()} for details.
     * - WORKS: see {@see \MyNS\Model\Cases\CaseNr::methodTwo()} for details.
     * - FAILS: see {@see CaseNr::methodTwo()} for details.
     * - FAILS: see {@see self::methodTwo()} for details.
     * - FAILS: see {@see methodTwo()} for details.
     * - WORKS: see {@see \MyNS\Model\Cases\CaseList::create()} for the return value.
     * - FAILS: see {@see CaseList::create()} for the return value.
     *
     * @return CaseList  WORKS
     * @throws CaseNrException  WORKS - but no link in output
     */
    public function methodOne ()
    {
        throw new CaseNrException();
        return new CaseList();
    }

    /**
     * This is method two.
     *
     * @param  CaseNr  $obj  WORKS
     * @return self  FAILS
     */
    public function methodTwo ($obj)
    {
        return $this;
    }
}
```

Referring from `methodOne()` to `methodTwo()` in the same class with an inline `{@see …}` tag always requires the "Fully Qualified Structural Element Name (FQSEN)". This can quite verbose, especially in deeply nested namespaced trees. It also forces us to hard-code the hierarchy in the documentation, which is error-prone when classes get renamed or moved.

The non-inline version of `@see` can resolve these references much better (all the tests marked with FAIL above work). `@return` and `@param` also manage to resolve some of them, so why can't `{@see}`?

(That the output always uses the long-winded "fully qualified" form for references inside the same class makes it harder to read, but that could be a template issue, or just my personal preferences.)

In a similar vein, `methodTwo()` is trying to document that it returns an object of the current class.
`@return self` doesn't work, but at least `@param CaseNr` gets resolved correctly. The `@return` and `@throw` tags in `methodTwo()` also get resolved correctly, but the documentation does not contain a link to the `CaseNrException` class (could be an unrelated template bug).

For comparison, ApiGen accepts both the `{@see self::…}` and `@return self` tags, as well as resolving `{@see CaseList::…}` correctly.

Related issues: #263, #1270

**Comment by jaapio** [comment]
@mbed67 can you check if this works after the fixes you did?

**Comment by mbed67** [comment]
@jaapio @fi5er some of it has been resolved now. 
* WORKS: see {@see CaseNr::methodTwo()} for details
* WORKS: see {@see CaseList::create()} for the return value

The use of self and using just the method name without the class doesn't work and there still is a known issue with the @throws (#920)
