### ISSUE TITLE
relative links to images and css wrong in all templates

### ISSUE THREAD

**Issue by waspsolutions** [phpDocumentor/phpDocumentor2#1457]
version 2.7.0 all templates have incorrect image hrefs and css incomplete for each template cli seems to run fine with no errors 

here you can view the output of the templates i have created a folder for each:

http://www.ifootyfan.com/generated_api_docs_abstract/
http://www.ifootyfan.com/generated_api_docs_clean/
http://www.ifootyfan.com/generated_api_docs_new-black
http://www.ifootyfan.com/generated_api_docs_old-ocean
http://www.ifootyfan.com/generated_api_docs_responsive
http://www.ifootyfan.com/generated_api_docs_responsive-twig
http://www.ifootyfan.com/generated_api_docs_zend

**Comment by jaapio** [comment]
@mbed67 can you give an update on this issue?

**Comment by mbed67** [comment]
@jaapio I cannot reproduce this with the current version. I think it is solved, but this issue has not been closed.
