### ISSUE TITLE
Generated docs do not contain the fontawesome font

### ISSUE THREAD

**Issue by tchaffee** [phpDocumentor/phpDocumentor2#1473]
When I generate docs using the 'clean' template it does not include the fontawesome font. The generated HTML / CSS uses fontawesome which it tries to use from the font directory (e.g. http://foo.bar.com/api/font/fontawesome-webfont.woff?v=3.2.1)

Because of this all the symbols are missing when browsing the docs and it look bad.

**Comment by mvriel** [comment]
I have reopened the issue

**Comment by tchaffee** [comment]
Thanks. If there is anything I can do to help you reproduce the issue please let me know.

**Comment by ameenross** [comment]
I seem to have the same issue. Firefox is affected, but Chrome does not have the issue. Changing the FontAwesome CSS file to use CDN fixes it. See: http://stackoverflow.com/a/19484963/1000608

**Comment by ameenross** [comment]
Odd, after restarting Firefox the problem is gone... Probably a case of cache corruption

**Comment by DannyvdSluijs** [comment]
Can confirm this is still an issue with FF37 on MacOSX Yosemite. While working on Safari 8 on same MacOSX Yosemite. This is tested with version 2.8.2

**Comment by mvriel** [comment]
I have checked the issue and the fonts folder gets copied in various tests that I did and when I open the site in Chrome I do not see any issues. Perhaps this is a compatibility issue between this asset and other browsers?

I was planning on managing the assets using bower anyway, so let's try once we implement that

**Comment by jaapio** [comment]
@mbed67 & @rgeraads could any of you please verify if this issue was solved? I don't have a mac here. On ubuntu this seems to work fine.

**Comment by mbed67** [comment]
@jaapio On my mac it looks good in chrome, firefox and safari. The fonts folder is present.

**Comment by DannyvdSluijs** [comment]
@jaapio Can confirm as well that it is working on Mac OS X El Capitan (10.11.4) with FF45.0.1
