### ISSUE TITLE
Argument $variable is missing from the Docblock of method

### ISSUE THREAD

**Issue by wesdean** [phpDocumentor/phpDocumentor2#1476]
I am getting an argument missing error for the first argument of every method with arguments. Here is a copy of my doc block and method.

/**
     * Sets configuration flags.
     *
     * @param String $flag The name of the flag to set.
     * @param Boolean $value The value of the flag.
     * @param Boolean $auto_run Whether to execute Config::run() after setting the flag.
     */
    public static function setFlag($flag, $value, $auto_run = false) {
        $value = !!$value;
        
        if ($auto_run && $value == self::varDefault(self::$flags[$flag])) $auto_run = false;
        
        self::$flags[$flag] = !!$value;
        if ($auto_run) self::run();
    }

**Comment by sascha-egerer** [comment]
Anyone to pick this?

**Comment by sascha-egerer** [comment]
There is currently no branch for version 2.8.x to do a pull request against it, right?

**Comment by mvriel** [comment]
All changes that need to be deployed as part of 2.* can be PRed to Master; develop is used for the work on version 3

**Comment by mvriel** [comment]
Thanks @sascha-egerer for helping us out! I have just merged the PR that fixes this issue and it will be included in the next 2.8.* release

**Comment by raviraya** [comment]
Actually I am using 2.8.1 version. I am having following issues. I am new for phpDocumentor

Error :Argument $ni is missing from the Docblock of investment()

this is the function I have

    /**
     * set investment
     * @param string $ni                  
     * @param string $pd          
     */

public function investment($ni = null, $pd = null){
......
}

When run in command I am getting the files with error report. I searched so many times I cant find the solutions. Any body please help me out.

**Comment by hschletz** [comment]
I just upgraded to 2.8.2 which definitely has the PR applied. Ist seemed to work at first, but after deleting the cache all those messages appeared again :-(

**Comment by quasipickle** [comment]
The problem still exists with 2.8.2
