### ISSUE TITLE
Error 404 while fetching file: Not Found

### ISSUE THREAD

**Issue by Ciloe** [phpDocumentor/phpDocumentor2#1512]
Hi !

I'm using phpdoc 2.8.1 version. When I generate documentation, I can't see the file description. I can see this error "Error 404 while fetching file: Not Found"

If I watch in my fireBug, I can see that "NetworkError: 404 Not Found - http://domain/job/Trombi%20Tumblr/javadoc/files/Appli/Bundle/TumblrsBundle/Controller/TumblrController.php.txt". So the file is not generated.

How can I fix that ?

**Comment by DaveWP** [comment]
The problem can be solved by making a change to Twig.php - see #1461, and making the following change to file.html.twig, class.html.twig and interface.html.twig in the template directories (based on clean)

At the bottom of each file you will see the following block

        <div class="modal-body">
            <pre data-src="{{ path('files/' ~ node.path ~ '.txt')|raw }}" class="language-php line-numbers"></pre>
        </div>
 
The path name needs to be filtered to handle space characters to create a valid URL.

        <div class="modal-body">
            <pre data-src="{{ path('files/' ~ node.path|replace({' ':'%20'}) ~ '.txt')|raw }}" class="language-php line-numbers"></pre>
        </div>

Note that I've seen suggestions about applying the URL Twig filter, but I've found this causes problems with handling the "\" character with references to %2F in file names.  With #1461 implemented, the correct folder structure is generated for the source files.

**Comment by mvriel** [comment]
I am sorry to close this issue in favor of #1461; I am pruning the issue list and having duplicates will impact the amount of time spent
