### ISSUE TITLE
Composer installation fails in folders with long names

### ISSUE THREAD

**Issue by cmb69** [phpDocumentor/phpDocumentor2#1529]
If I try to install phpDocumentor 2.8.2 in a folder with a long name, the Composer install fails:

    [ErrorException]
    ZipArchive::extractTo(): Full extraction path exceed MAXPATHLEN (260)

That already happens for `c:\test\a-long-folder-name\a-long-folder-name\composer.json`. It seems that the problem is caused by the files in vendor\phpdocumentor\phpdocumentor\features; not sure, if they should be there at all.

**Comment by axelitus** [comment]
I can confirm this is happening (at least in Windows 8.1). I've attached a screenshot with the error.
Indeed this happens for the features folder as it contains a specially long named folder/file structure, this added to an already long folder/name structure surpasses the MAXPATHLEN.

![phpdoc-error](https://cloud.githubusercontent.com/assets/732441/6904770/8a833e48-d6e0-11e4-860e-acd85f92c7a2.png)

**Comment by jorgekury** [comment]
Friend, I had this problem, to solve I decreases the name of the project folder

**Comment by mvriel** [comment]
Unfortunately this was an unforeseen side-effect when we introduced better names for our integration tests; windows paths may only be 256 characters in total length. 

We would need to reduce the length, or tell composer to ignore test files. Though the latter would only help when installing with composer

**Comment by cmb69** [comment]
AFAIK the path length restriction to 260 characters applies only for 32-bit Windows; 64-bit systems seem to allow 32767 bytes. Of course, that doesn't really help **now**, but it might be something to consider long-term.

I'm not sure if it is necessary to deliver the test files for Composer and in the phars. A large amount of users are probably only interested in running (not co-developing) PhpDocumentor. For the rest it might be okay to clone the Git repo – if necessary into C:\phpdoc (i.e. not wasting "precious" characters on an overly limited path lenght).

Just some quick and presumably pragmatic thoughts.

**Comment by akaias** [comment]
> AFAIK the path length restriction to 260 characters applies only for 32-bit Windows; 64-bit systems seem to allow 32767 bytes. 

well, in our case, we have 64 bit Windows 7 hosts, having the issue with the path names, so your assumption is wrong.

> I'm not sure if it is necessary to deliver the test files for Composer and in the phars. A large amount of users are probably only interested in running (not co-developing) PhpDocumentor.

that would be helpful

**Comment by TomasVotruba** [comment]
> We would need to reduce the length, or tell composer to ignore test files. Though the latter would only help when installing with composer

So adding `/test export-ignore` to `.gitattributes` would help?

**Comment by cmb69** [comment]
@akaias I just checked with a 64-bit PHP build, and indeed, the limit of 260 chars applies. [Windows allows longer names](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#MAXPATH), but probably too much had to be changed in PHP to make use of it.

**Comment by newtonianb** [comment]
What's the verdict on this? Same problem, windows 8.1 64 bit :-1:

**Comment by TomasVotruba** [comment]
I've prepared fix in #1564

**Comment by TomasVotruba** [comment]
:+1:
