### ISSUE TITLE
Unable to install from Composer on Windows

### ISSUE THREAD

**Issue by samwilson** [phpDocumentor/phpDocumentor2#1532]
I'm getting the following error when trying to run `composer.phar global require phpdocumentor/phpdocumentor`:

`[ErrorException]
ZipArchive::extractTo(C:\Users\samwilson\AppData\Roaming\Composer/vendor/composer/55ae25a0/phpDocumentor-phpDocumentor2-1c6a3bd\features\3. Creating Documentation\3.2. API Documentation\3.2.2. Tags/10. Hide element unless internal information is also to be rendered (internal).feature): failed to open stream: Invalid argument`

**Comment by gggeek** [comment]
Same here.
Either the filename is too long, or the forward slash (tags/10) is a problem, or both...

**Comment by gggeek** [comment]
ps: up to rev. 2.8.1 this did not manifest

**Comment by ashnazg** [comment]
Most likely filename to long for Windows.  The extract error is how that issue presents itself.  I saw this before in PDepend and PHPMD.  I think Manuel found a way for the tests heirarchy (where all the long filenames were) to be skipped by composer when installing those packages.

**Comment by cmb69** [comment]
Duplicate of #1529.

**Comment by fonsecas72** [comment]
This seems a problem we can not solve. Perhaps we can avoid this by using the phar?
So, can we close this @samwilson ?
:bee:

**Comment by samwilson** [comment]
Yep, I reckon so, especially with the note that's been added to the readme. :) Thanks!
