### ISSUE TITLE
2.8.2 phpDocumentor.phar is unavailable

### ISSUE THREAD

**Issue by martijngastkemper** [phpDocumentor/phpDocumentor2#1541]
It want to update the Homebrew formula, but the phar file is not available for version 2.8.2. Can you make that available in Github?

**Comment by mvriel** [comment]
Hello @martijngastkemper,

I have added the phar file to the github release: https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v2.8.2

Thank  you for updating the homebrew formula!

**Comment by martijngastkemper** [comment]
I've created a PR: https://github.com/Homebrew/homebrew-php/pull/1655
