### ISSUE TITLE
Rendering @throws Exception Description

### ISSUE THREAD

**Issue by DJWindless** [phpDocumentor/phpDocumentor2#1546]
Hello people,

when i rendering the documentation the throws exception only renders the description.

Example:

```
/**
 * Getting DB Values
 *
 * The method connect to localhost DB XYZ
 *
 * @throws Exception Connect to Database failed
 */
```

What is rendered in PHP Doc:

Getting DB Values

The method connect to localhost DB XYZ

throws                                               Connect to Database failed

I want to know how i can render the exception type. It gives so many exception types (InvalidArgumentException and so on).

If can tell me a way to render this, i would thank you very much
I'm using Version phpDocumentor2-2.8.2 with Template responsive-twig

Greetings

Robert

**Comment by jaapio** [comment]
thanks for your report. This issue will be fixed in the next release.
