### ISSUE TITLE
Files not parsed

### ISSUE THREAD

**Issue by Xymanek** [phpDocumentor/phpDocumentor2#1548]
I've just started using phpDocumentor and I've run into a problem: some files (not all) are not parsed.
If i go into error log and check the errors the is only 1 thing
![default](https://cloud.githubusercontent.com/assets/2865341/7568229/41ca45ac-f80a-11e4-8d84-3fa74d36a8e6.PNG)
And another thing is that markers (TODO) are parsed. Can somebody please help me?
Running Windows 8.1, PHP 5.6

**Comment by mvriel** [comment]
Is this `config.php` file an example of a file that is not parsed? Given that it shows in this report means it is being parsed but you seem to expect output that you are not observing.

Can you tell me what you expect to see and are not seeing when this file is parsed?

**Comment by Xymanek** [comment]
After investigating the problem myself I've found that [variable-length argument lists](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) are causing problems (due to the fact that only those files give error when i parse them (with the line that the function is declared on), rest are working fine). So i suppose (due to fact that variable-length argument lists were only introduced in 5.6), that phpDocumentor doesn't understand them yet. Any thoughts on when this will be added?

**Comment by Xymanek** [comment]
Anything on this?

**Comment by Mhykiel** [comment]
I'm new to phpdocumentor and having the same problem. I installed through pear through xampp command line. When I ran the phpdoc command in my htdocs folder where I made a phpdoc.xml file. When the template was"clean" I only got generated folders. When i made the theme "responsive" I got folders and files. Files like index, errors, deprecated, ect..

But when I looked at index.html through a web browser There were no packages listed. Just a page to errors. that look like the previous posters screenshot.

I even have a sample file from the documentation explaining docblocks. None of the methods, classes, page block, or class blocks.

**Comment by Mhykiel** [comment]
To add I also upgraded pear to 1.9. Tried uninstall and reinstall of phpdocumentor. I used phpdocumentor 2.8.1 because .2 wouldn't unpack.

I tried phpdocumentor on a different fresh install of xampp with an older php 5.5 and it still had same results.

**Comment by Erutan409** [comment]
Getting same issue, here.  I have a file named 'Anaylsis.php' and it's not being parsed at all with the same error on the report.  Even though I've given it a bogus file summary to see if it would be "let through."  I don't have any variable-length argument lists, though.

**Comment by Ennosuke** [comment]
I have a simmilar problem with a file. phpDocumentor states that there is no summary on file level, which is not the case. If wanted I may be able to provide a file where this is the case.

**Comment by Erutan409** [comment]
@Ennosuke did you by chance test your script file?  Per my edit above, that was my problem.

**Comment by Ennosuke** [comment]
@Erutan409 Yes, the file is in use and there are no parsing errors in it.

**Comment by jaapio** [comment]
Please try to upgrade to v3.0.0-alpha1 which should solve this issue. Feel free to open a new issue when needed
