### ISSUE TITLE
Create Definition files to replace the Configuration classes and be fed to factories

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1555]
> This issue depends on the Configuration Array format defined in #1522; collaboration between these two items is recommended

The Version Definition AGGREGATE contains several Entities that work together to declare a definition for a new or existing Documentation object.

A Definition can be seen as a specification that informs a Factory how to construct a new object. In the current design we plan on having a Version Definition that is used as basis for creating a new Documentation object using the Documentation Factory; and to have a Definition for each type of DocumentGroup.

The above means that we need a common interface for Definitions for DocumentGroups but the actual Definition classes are part of their respective DocumentGroup component and as such not documented as part of this component. 

![](http://www.plantuml.com:80/plantuml/png/ZLN1Rjf04BtxAqQ8Wzt4bdgD45AKAksfGZJg9OgYnOpjgM0NxOw9eYR_tjcrqzY03Lo0zPitC-_DZaapsaBb2D-m84rCHaTqul1UvMpiA_oDG3vNa5jKZB7P-OSERi2n9Lq-FYNokyFrtcKpURr5pT-jgNUdgD-ZADyevs1XpH_CEVkDrWaY-mGlSMSSzKfvViwb1BPrpl6TqGMLjLKTuklZDf8sj43EgxZDyhFUhj3w-eVJT-DkDvju7Ftu92sTw-XGMOibEP5iNAsuqHkc_Bh3wqzfQrhZlR5RnJ0jmlVrETsdHL-KKMj7f7cFj644IsN5WUhMWO8MsF40n2vM9DGEzsZL9e0DLsWxA0TIVhzq5u0l21fn3Mp-IoLf1deC4Pu8LLw1rmfCSGZFeW1xg7080UH0XDLC1KdgrMi8KDB9TaKw39kFUgb8ihXwvP0Xzbm94FlWc3BC6b5s159FC2e1fTTjL6CMY0hWJ6rpNqO8y2VzOYhL4i8IVprujiMFHP990zH8HBfXysL9ShLNj56h3Sg3GFTXhR9MDQsy45UDHWVAe5vxLyzECSncjsKfXiZemD8Odi_RYKvXtxrVnpFKdBVOzMaV_HWEM2oNh1tS4hb7UUfsTfA5W05I5sA7CygcEhLg84xIzABj5Lsqub8ferzuxvzFDtOZBygHPVCnNuE2UnbMTndTBCikM7OtChfXQnFNZ0uaKTYfqVdGz6r-lD2ZOzpiJQmONttHgRKP9vTqC5BeGOLZoCdN2PWqdSFaomHwej-rExBJc3Wbuo3x8rjKkwxDNOWWGZCkyxkXXnf_2moG7oar43sOzuFW7m00)

With the DefinitionRepository for the Versions it is possible to retrieve a Definition for each Version that is defined in the configuration file. As can be seen in the Class Diagram it accepts the ConfigurationFactory, which will create an array containing configuration settings upon calling its ‘get’ method. The ConfigurationFactory allows the Configuration to be retrieved by the DefinitionRepository as a Data source but postpone loading the configuration until absolutely necessary so that a user can provide their own Configuration file location.
Since each DocumentGroup can have a separate set of properties (a Guide using RestructuredText as Format can have different properties from an ApiReference using PHP as Format) each can have their own specialised Factory (part of the Component for that specific DocumentGuide); since the Version Definition Factory needs to be able to know when to use which Factory these specialized Factories need to be registered using the registerDocumentGroupDefinitionFactory method.

**Comment by jaapio** [comment]
@mvriel I think this one is solved. All classes in the diagram are there.
