### ISSUE TITLE
phpdocumentor cant install in thread safe version php 

### ISSUE THREAD

**Issue by dilidilidi** [phpDocumentor/phpDocumentor2#1565]
i have try thread safe php5.5.25(the official zip package),pear install is ok,but when i install phpdocumentor ,i get an error,unable to unpack path_to_temp_pear_download\phpdocumentor-2.8.2.tgz.
and i have try all the non thread safe php version(the official zip package of 5.4、5.5、5.6)，all is success.

all of above is under win7 x64

is this a bug?or maybe i lost something?

**Comment by jaapio** [comment]
Closing because these phpversions are not supported any more. 
Feel free to open a new issue when applicable
