### ISSUE TITLE
file name wrong in package.xml of phpDocumentor.2.8.2.tgz

### ISSUE THREAD

**Issue by sasha6806** [phpDocumentor/phpDocumentor2#1608]
d:\PHP56>pear upgrade d:\...\pear\download\phpDocumentor-2.8.2.tar
ERROR: file D:\Administrator\TEMP\pear\temp\tmp1288.tmp\phpDocumentor-2.8.2\features\4. Browsing the documentation\1. Creating a new
 template\4.1.1. Generate skeleton using template:init task.feature does not exist

The right file name is 4.1.1. Generate skeleton using template_init task.feature

**Comment by RoBorg** [comment]
Just to clarify as I understand it...

This is a Windows-specific issue. The filename specified is "features/4. Browsing the documentation/1. Creating a new template/4.1.1. Generate skeleton using template:init task.feature"

Windows doesn't allow ":" in a filename, so it gets converted to an "_" when the .tgz is unpacked.

Suggested resolution would be to rename the file to not have a ":" in it :)

**Comment by mvriel** [comment]
This is a duplicate of #1544, as such I will close it so that the conversation is central to #1544 and we have a more clear view on open issues.

Thank you for reporting this issue
