### ISSUE TITLE
Bug in variable-lenght argument list...

### ISSUE THREAD

**Issue by JGarciaVera** [phpDocumentor/phpDocumentor2#1610]
Hi, 

I have some libraries with functions defined using the new variable-lenght argument list available in php 5.6+ (http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) but phpDocumentor throws an error when trying to parse those files.

A function example is:
private function ReplaceTags(array $ExtraTags, $ReplaceEnv, $ReplaceParams, &...$ReplaceIn)

Thanks!!

**Comment by aduh95** [comment]
Hi,

I got the exact same issue as descibed here. My code is this one : 

```php
    public static function SQL()
    {
        return new prep\DirectSQL(...func_get_args());
    }
```

And once I comment the return statement, it works fine.

Thanks a lot!

**Comment by jaapio** [comment]
Php documentor is currently using an outdated version of phpparser. We are aware of the fact that this needs attention. But due a leak of time, we didn't find the moment to create a new release. 

Sorry for the inconvenience

**Comment by jaapio** [comment]
Closing this one since it is related to #1701
