### ISSUE TITLE
Thanks for the enormous effort

### ISSUE THREAD

**Issue by heiglandreas** [phpDocumentor/phpDocumentor2#1615]
There's been an enormous effort of countless hours of unpaid work of numerous contributors and project-leads gone into an awesome project! 

Complaining about things that do not work is so easy but often a simple THANK YOU because everything works as expected is lost! 

Therefore I just wanted to say **THANK YOU ALL**!

**Comment by Erutan409** [comment]
:+1:

**Comment by freshfelicio** [comment]
+1

**Comment by DeeZone** [comment]
:+1:

**Comment by mvriel** [comment]
I am awed by such kind words; I had already thanked @heiglandreas on twitter because wow. I am having trouble closing this issue so I am keeping it open longer :)
