### ISSUE TITLE
Links for @see tags in class DocBlocks don't go anywhere

### ISSUE THREAD

**Issue by jxmallett** [phpDocumentor/phpDocumentor2#1620]
I've just started using phpDocumentor for the first time and it's going well.

Unfortunately, I've found that if i put a `@see` tag in a class docblock it doesn't get linked like other `@see` tags do. eg:

```
/**
 * @see SecondClass SecondClass // A link will be displayed but the href will be empty.
 */
class FirstClass {
    /**
     * @see SecondClass SecondClass // This will link to SecondClass, as expected.
     */
    public function MyFunction() {
    }
}

class SecondClass {
}
```

I've tried using fully resolved namespaces, like `\MyCompany\SecondClass` and also linking to methods. I've tried linking to everything I can think of but I can't get anything to work.

Perhaps related: @see links will only display if I specify link text. `@see SecondClass` won't display anything, regardless of where the tag is.

I'm using phpdoc 2.8.5 with the 'clean' template. I'm using PHP 5.5.27, on Ubuntu 14.04.

Is this a bug or am I doing something wrong? Any help would be much appreciated!

**Comment by jxmallett** [comment]
Wow that was hard to debug! Tracked it down to a problem with the template though. I'll file a pull request soon.

**Comment by mvriel** [comment]
Thank you for your pull request; the fix will become available with the next release of phpDocumentor or on the master branch of phpDocumentor
