### ISSUE TITLE
Can't install w/ PEAR

### ISSUE THREAD

**Issue by web-elements** [phpDocumentor/phpDocumentor2#1630]
I'm trying to install phpDocumentor2 using pear.
I type in the terminal

> $ pear channel-discover pear.phpdoc.org
> $ pear install phpdoc/phpDocumentor

but something goes wrong:

> Warning: lstat(): Lstat failed for /tmp/pear/cache/8fe36aa0c2c9252d4de3baba587ca830rest.cacheid in REST.php on line 276
> No releases available for package "pear.phpdoc.org/phpDocumentor"
> install failed"

I have tryed

> $ pear clear-cache
> $ pear install phpdoc/phpDocumentor-2.8.5

but nothing changed ç__ç

**Comment by mvriel** [comment]
Issues with `lstat failed` generally indicate an issue on your local filesystem; you either may not have write permissions or another issue occurred.

Have you tried the same with with sudo?

**Comment by jaapio** [comment]
Closing this in favor of #1787. Feel free to reopen when you still have issues.
