### ISSUE TITLE
I can't install phpdoc on mac os X 10.10, could anyone give a hand, please ?

### ISSUE THREAD

**Issue by scfkcf** [phpDocumentor/phpDocumentor2#1644]
I'm a novice for pear and phpdoc, i've tried installing phpdoc many times but failed, could anyone give a hand?

**Comment by jaapio** [comment]
Did you get any error?

**Comment by mvriel** [comment]
There has been no response since September 4th; because there are no other reports of this issue and this item has expired I will close this issue
