### ISSUE TITLE
Templates giving lots of errors

### ISSUE THREAD

**Issue by abayob** [phpDocumentor/phpDocumentor2#1646]
Hello,

PHPdocumentor keeps creating " incomplete" documentary for the templates.
For example: the "clean"  template misses a lot of files on certain locations. I found out that some of the images missing are in a different directory than pointed to from the HTML.

Furthermore the "responsive-twig" and the "new-black" template seems to miss all the class-information.

I have installed PHPdocumentor 3 times, using different install methodes like PEAR (second time with clean PEAR-install) and Composer. Both gave the same issues.

Best regards,
Abayob

**Comment by abayob** [comment]
I even tried the PHAR-file. Still a lot of images missing...

**Comment by Erutan409** [comment]
Did you conclude that it wasn't a bug in the code?

**Comment by abayob** [comment]
Hello Michael,

 

Yes, I did. The problem lies in the inability to work under a vhost.
If the intention from PHPdoc is to create an offline site with all the content, then it works fine.

If the intention is to be able to host the site, there seems to be a problem with some elements.


Anyway, the question I asked does not answer the knowledge I seek, so I asked my question on stackoverflow and closed the one on Github.

 

Met vrolijke groet, 

 

Bart van Sleeuwen

Abayo Team
