### ISSUE TITLE
Add documentation pages ?

### ISSUE THREAD

**Issue by roukmoute** [phpDocumentor/phpDocumentor2#1647]
Hi,

I would like to know if is it in roadmap the possibility to write documentation page outside API.
Because for the moment, phpDocumentor generate rather an API.

Thanks

**Comment by mvriel** [comment]
Hello @roukmoute,

Currently this feature is planned for version 3.1 with Markdown source files and version 3.2 for RestructuredText source files. With the upcoming phpDocumentor 3 we had to do a redesign of the entire architecture to support this and other use cases.

I hope this answers your question,

With kind regards,

Mike van Riel
