### ISSUE TITLE
How to skip documenting of parent class?

### ISSUE THREAD

**Issue by Serhioromano** [phpDocumentor/phpDocumentor2#1656]
My classes are 1 method classes, but parent class is huge and the same everywhere. When I look at doc of child there are so many things when all I want just to show its primary method. And if I want to see parent class methods I can navigate there through Class hierarchy menu.

Is it possible to disallow documenting of parent methods and parameters?

**Comment by mvriel** [comment]
At the moment phpDocumentor does not support disabling its inheritance feature; depending on your chose template you can however choose to hide inherited elements. For example the `abstract` template supports this feature

**Comment by benjaminwy** [comment]
Is this still the case? It seems the `abstract` template no longer exists. Would the best way to achieve this behavior be to write my own template?
