### ISSUE TITLE
Phpdocumentor analysis with Exakat engin

### ISSUE THREAD

**Issue by dseguy** [phpDocumentor/phpDocumentor2#1657]
Hi.

Just as discussed with Jaap at 010 Rotterdam (PHP meetup), I ran the exakat engine on the phpdocumentor2 repository. 
The result are there : http://www.exakat.io/reports/phpdocumentor/

**Comment by jaapio** [comment]
Hi @dseguy,

It took some time for me to have a look at the results. I don't know yet it we can do any thing with the results. But I will keep exakat in mind.
