### ISSUE TITLE
jms/serializer has a version 1.0; install failed

### ISSUE THREAD

**Issue by tubssp** [phpDocumentor/phpDocumentor2#1660]
jms/serializer has a version 1.0

The installation from phpdocumentor2 failed

The error is "jms/serializer": "~0.12" in the file composer.json

**Comment by bassrock** [comment]
Getting the same error

**Comment by ima-tech** [comment]
Getting the same error also, what could prevent this bundle from updating to jms/serializer 1.0 ?

**Comment by mvriel** [comment]
Updating the version number to 1.0 may break people who have JMS/Serializer <1.0 in their projects. We should investigate whether JMS Serializer has the same API as 0.12 and if so we can add a version restriction that includes 1.0

**Comment by jaapio** [comment]
This issue is already solved. A new tag shall be created to release this. tag 2.8.5 contains the ~0.12 version. But master already has >=0.12.
