### ISSUE TITLE
phpunit runs two times because of phpunit target in continuousphp build settings

### ISSUE THREAD

**Issue by oswaldderiemaecker** [phpDocumentor/phpDocumentor2#1669]
Please remove the build:phpunit target in the build settings, it is already configured in the testing settings, this makes the build slower as it runs phpunit two times.

**Comment by jaapio** [comment]
I'm not sure how this is configured at the moment. But previously we had a phpunit run with the library versions that are defined in the composer.lock file. And we ran a build with a composer update. This allowed us to see if we could upgrade any libaries without breaking stuff.

**Comment by fdewinne** [comment]
continuousphp always rely on the tools defined in your composer.lock file :)

**Comment by mvriel** [comment]
Thanks for mentioning this; I intend to take a look at the DevOps side of the project, including the CI/CD config on short notice and will include this.

**Comment by mvriel** [comment]
This has been resolved
