### ISSUE TITLE
Extract Markers from a source file

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#1685]
phpDocumentor 2 is capable of extracting markers from source files and rendering them to a report file. This functionality was temporarily removed and should be readded. An interesting take is to add a middleware to the File parser that will search the parsed file and catalogue the output in a View object.

> This means that this item is dependent on the views being implemented fully.

_Markers_

A marker is an inline comment (`//`) anywhere in a file that starts with a keyword (such as TODO or FIXME), optionally followed by a colon and then by a description.

Example:

```
// TODO: This is the description for a marker
```

**Comment by jaapio** [comment]
It could be interesting to have this as middelware during the parsing process. currently we only support middelware as pre and post parsing. 
The pr below enables this kind of middelware.
https://github.com/phpDocumentor/Reflection/pull/92

**Comment by mvriel** [comment]
Closing the 3.0 tickets, will reconsider them after our re-alignment
