### ISSUE TITLE
[RFC] Be able to set cache-dir

### ISSUE THREAD

**Issue by BorislavSabev** [phpDocumentor/phpDocumentor2#1693]
Currently the phpDoc caches are written to the same directory as the setting: `parser->target`. 
It would be good to be able to set this to another directory.
The thing is that these dirs are much more (in numbers) than the others in the target directory and stuff tend to get clogged. The ideal solution would be to either be able to set this to any dir or just use `tmp/phpdoc/cache` (on Unix-like systems).

**Comment by mvriel** [comment]
This is already supported by the app, the run command supports the `--cache-folder` option to set it and the configuration supports it by setting the target path in the Parser section
