### ISSUE TITLE
Parse Error When Using 'use function'

### ISSUE THREAD

**Issue by quantumpacket** [phpDocumentor/phpDocumentor2#1706]
The below code which is valid since PHP 5.6 produces the following error when generating documentation:

> Parse Error: Syntax error, unexpected T_FUNCTION, expecting T_STRING or T_NS_SEPARATOR on line x  No summary was found for this file

```php
use function Acme\Rockets\fooBar;
```
**PHP:** 7.0.1
**PhpDoc:** dev-master

**Comment by jaapio** [comment]
We do not officially support php 7 yet. So I think that could cause your error. There are plans to have a look at how much effort it will take to be compatible with php 7.

**Comment by quantumpacket** [comment]
@jaapio I just tested under PHP 5.6.4 and the same parse error I get. This syntax is not PHP7 specific and has been available since 5.6.

**Comment by jaapio** [comment]
closed since phpparser was upgraded. before we only supported php =<5.5 for now php 7.0 is the limit.
