### ISSUE TITLE
Support updated JMS Serializer library

### ISSUE THREAD

**Issue by crazycodr** [phpDocumentor/phpDocumentor2#1707]
When i request for "phpdocumentor/phpdocumentor" as of right now, it turns out i can't install it because i'm using a version of "jms/serializer": "^1.1". I'm getting:

```

  Problem 1
    - phpdocumentor/phpdocumentor v2.8.5 requires jms/serializer ~0.12 -> no matching package found.
    - phpdocumentor/phpdocumentor v2.8.4 requires jms/serializer ~0.12 -> no matching package found.
    - phpdocumentor/phpdocumentor v2.8.3 requires jms/serializer ~0.12 -> no matching package found.
    - phpdocumentor/phpdocumentor v2.8.2 requires jms/serializer ~0.12 -> no matching package found.
    - phpdocumentor/phpdocumentor v2.8.1 requires jms/serializer ~0.12 -> no matching package found.
    - phpdocumentor/phpdocumentor v2.8.0 requires jms/serializer ~0.12 -> no matching package found.
    - Installation request for phpdocumentor/phpdocumentor ^2.8 -> satisfiable by phpdocumentor/phpdocumentor[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

This is simply because you guys have not updated phpdocumentor to the 1.0 branch which contains a ton of new features for JMS/Serializer. Even with ^ instead of ~, the problem would still exist. Is there anyway to change that in composer.json and do a quick release?

Thanks

**Comment by crazycodr** [comment]
Hummm i think it might be a related library, i forked phpdoc and did a composer install and i don't even see it installed... thats strange...

**Comment by jaapio** [comment]
A new release is pending. We have some other issues that have to be resolved before we can do a release. But due limited time we didn't have time for this yet.

**Comment by crazycodr** [comment]
Sad, i'm forced to use another solution then. Good luck
