### ISSUE TITLE
How to document an anonymous function when passed as an argument?

### ISSUE THREAD

**Issue by henrywright** [phpDocumentor/phpDocumentor2#1714]
Hey guys

Is there any guidance available on how to document an anonymous function when passed as an argument?

```PHP
// Call my_function(), passing 2 arguments.
my_function( 'foo', function() {
    // Body of the anon function I'd like to document.
} );
```

Thanks in advance.

**Comment by jaapio** [comment]
Currently phpdocumentor doesn't support anonymous functions. We are only reading the file for function statements which are different from anonymous functions.
Think this relates to #1689

**Comment by henrywright** [comment]
Thanks for the info.
