### ISSUE TITLE
Unable install using pear

### ISSUE THREAD

**Issue by superstarrajini** [phpDocumentor/phpDocumentor2#1715]
rk@uber1:~/phpmnulz$ sudo pear install phpdoc/phpDocumentor
downloading phpDocumentor-2.8.5.tgz ...
Starting to download phpDocumentor-2.8.5.tgz (8,184,822 bytes)
......done: 8,184,822 bytes
could not extract the package.xml file from "/build/php5-0LI9sl/php5-5.5.9+dfsg/pear-build-download/phpDocumentor-2.8.5.tgz"
Download of "phpdoc/phpDocumentor" succeeded, but it is not a valid package archive
Error: cannot download "phpdoc/phpDocumentor"
Download failed
install failed
rk@uber1:~/phpmnulz$

**Comment by jaapio** [comment]
This one dupplicates #1579 there is something wrong with the latest pear packages. That should already have been solved. We are preparing a new release, but there are some blocking issues. That need to be solved
