### ISSUE TITLE
Error messages "No summary for interface" and "No summary for trait" do not display the name

### ISSUE THREAD

**Issue by jack126guy** [phpDocumentor/phpDocumentor2#1717]
I'm not sure if this is the right place to report this, because the messages do not seem to be in this repository.

If there is no summary for an interface or trait, the error message does not include the name of the interface or trait. It simply says `No summary for interface ""` or `No summary for trait ""`.

To fix this, errors 50009 and 50010 should use `%2$s` instead of `%s`. I have tested this and it works.

**Comment by jaapio** [comment]
Thanks for reporting this. I solved this issue. It will be part of the next 2.8 release
