### ISSUE TITLE
How to document properties of another @property in the same class?

### ISSUE THREAD

**Issue by dharkness** [phpDocumentor/phpDocumentor2#1719]
We have a couple applications built on Zend Framework 1 (I know, I know), and I've been trying to find a way to document the properties set on a view inside each controller. The `view` property of every controller is a generic instance of `Zend_View`. Is there a way to document its properties?

```php
/**
 * @property User $view->user    <-- Define a magic property on the view...
 */
class UserController extends Zend_Controller_Action
{
    /**
     * @param int $id
     */
    public function viewAction($id) {
        $this->view->user = Users::get($id);
        if (!$this->view->user->isActive()) {    // <-- ...to get type-hinting here
            ...
        }
    }
}
```

Is this possible now?

Workaround: Declare a fake interface with the desired properties and an `@property` declaring `$view` to be of that interface.

```php
/**
 * @property UserView $view
 */
class UserController extends Zend_Controller_Action
{
    // body is identical
}

if (false) {    // or place in a separate file that doesn't get loaded
    /**
     * @property User user
     */
    interface UserView { }
}
```

The advantage to this method is that it provides type-hinting in the view scripts as well.

```php
<?php /* @var UserView $this */ ?>
<h1><?= $this->user->getName() ?></h1>
...
```

**Comment by jaapio** [comment]
If it is only about the type hinting in your IDE you could write a private method in your controller to access the $this->view->user . Which will also make it easier for you to rename the variable in the view without changing your controller.

But consider why you are using the view to store a variable and access it afterwards. If you take a look at the zf2 implemenation of the view this will look even stranger. The controller should provide variables to the view at the end of the controller action. The view is not a storage place for your variables from my point of view.

**Comment by dharkness** [comment]
The main reason is to document the values being passed to the view scripts via the view, but sometimes an action may need to use those values itself to decide what action to take. This is where type-hinting comes in handy.

As for storing values in the view, those that are used only by the controllers are stored as regular properties of the controller instance. We have very few cases like that. All of the view properties are indeed used when rendering the view scripts.

**Comment by jaapio** [comment]
phpdocumentor doens't support this kind of documentation properties. We do not support type hinting in your IDE any way. Most IDE's are parsing the docblocks them selves. So even if we would support this it was up to your IDE to give you the correct hints.

**Comment by dharkness** [comment]
No worries about adding the functionality. I was only asking if there was a syntax I hadn't seen that already allows this. I've gone with the fake view declaration, and it works great when writing the views.

That being said, I have no doubt the good IDEs will pick up any new features added to this awesome project. So while you may be building a documentation tool, please keep in the back of your mind that your enabling type hinting as well. :)

**Comment by jaapio** [comment]
Thanks for having us. We are very happy with all feedback from our users. If there is any thing we can do to help you please feel free to create a new issue.

**Comment by dharkness** [comment]
I see that [PSR-5](https://github.com/phpDocumentor/fig-standards/blob/features/typedef/proposed/phpdoc.md) has proposed the `@typedef` annotation. Assuming this works just like it does in JSDoc, it will work perfectly to do what I seek. :+1:
