### ISSUE TITLE
Parsing a file with variadic function results in an parse error

### ISSUE THREAD

**Issue by sknaetsch** [phpDocumentor/phpDocumentor2#1725]
Hi,

I'm using phpDocumentor version **2.8.5** in combination with php **5.6.15**. It seems that phpDocumentor has an issue with variadic functions.

Content of the test file (test.php):
```php
<?php
function test(...$params)
{
  return $params;
}
```

Running the simple command `phpdoc parse -f test.php` results in the following output:

    Collecting files .. OK
    Initializing parser .. OK
    Parsing files
    Parsing /tmp/test.php
    Parse Error: Syntax error, unexpected , expecting T_VARIABLE on line 2  No summary was found for this file
    Storing cache in "/tmp/output/build" .. OK

Running the same command again doesn't result in any issue:

    Collecting files .. OK
    Initializing parser .. OK
    Parsing files
    Parsing /tmp/test.php
    Storing cache in "/tmp/output/build" .. OK

I assume the cached result from the first try is used and somehow no error is thrown.

Any ideas?

**Comment by jaapio** [comment]
Because the cache is used the validation is not executed. The complete parsing is skipped where validation is part of. You can use --force to force reparsing.

**Comment by sknaetsch** [comment]
From my point of view the main issue is the syntax error in the parsing part. Why should there be no error with the cached version?

Can anyone reproduce the behaviour?

**Comment by jaapio** [comment]
The main issue is that we are using an old version of phpparser, which doesn't support php 5.5+ since variadic is added in php 5.6 our parser can't hande this. upgrading the parser would require more testing than our test-suite provides. All our effort is going to phpdocumentor 3 which is currently in development. We have limited resources so we won't be able to fix this soon. I'm sorry about that.

**Comment by sknaetsch** [comment]
Ok, thank you for the clear statement.

**Comment by jaapio** [comment]
Releated to #1701. 
And fixed in the next release.
