### ISSUE TITLE
Internal links created by `@see` are broken

### ISSUE THREAD

**Issue by fi5er** [phpDocumentor/phpDocumentor2#1726]
Using phpDocumentor2 version 2.8.5, most of the internal links created by `@see` or `{@see}` are unusable (absolute, missing, or contain backslashes etc):

``` php
namespace TheNS;

/** The class docu. */
class TheClass {

    /** @var int  A property description. */
    public $aProperty = 42;

    /**
     * The method summary.
     *
     * - {@see \TheNS\TheClass}
     * - {@see \TheNS\TheClass::$aProperty}
     * - {@see \TheNS\TheClass::aMethod()}
     * - {@see \TheNS\TheClass              the class}
     * - {@see \TheNS\TheClass::$aProperty  the property}
     * - {@see \TheNS\TheClass::aMethod()   the method}
     *
     * @see \TheNS\TheClass
     * @see \TheNS\TheClass::$aProperty
     * @see \TheNS\TheClass::aMethod()
     *
     * @see \TheNS\TheClass              the class
     * @see \TheNS\TheClass::$aProperty  the property
     * @see \TheNS\TheClass::aMethod()   the method
     */
    public function aMethod () {}
}
```

All six inline `{@see}` tags create links with absolute URLs: `href="/classes/TheNS.TheClass.html"`, tested with the "clean" and "responsive" templates.

The next three `@see` links are missing from the docu, see issue #1079.

The last three `@see` links are OK in the "clean" template, but in the "responsive" template, the href attributes are `%5CTheNS%5CTheClass`, `%5CTheNS%5CTheClass::aProperty`, and `%5CTheNS%5CTheClass::aMethod()`, respectively. `%5C` is a backslash.

This goes for the documentation of non-namespaced files as well. It doesn't make a difference whether FQSENs are used or not.

**Comment by frickenate** [comment]
Confirming on my part in 2.8.5 using the default clean template. If there is no text attached to the tag, then the link tag is generated by without any link text, making it impossible to see or follow the declarations to their definition.

**Comment by PhrozenByte** [comment]
dup of #1672

@frickenate, please don't report problems in random issues, always create a new issue for a new problem (otherwise it's nearly impossible for the phpDoc devs to track and fix the issues). Your additional remarks have nothing to do with @fi5er's issue. Just fyi, the issue with missing text links is a dup of #1670; I don't know anything about your second paragraph, please make sure it hasn't been reported yet using GitHub's search engine and open a new issue when necessary.

**Comment by mbed67** [comment]
Regular @see tags and inline @see tags are fixed now when they are not in the same line as a @param or @return tag. For the latter problem, a new issue is made #1880. I will close this issue for now.
