### ISSUE TITLE
Suggestion: @immutable tag for classes

### ISSUE THREAD

**Issue by Loupax** [phpDocumentor/phpDocumentor2#1728]
There are classes with objects that are not meant to be able to be changed. Surely, you can make all their members private and accessible only via getters, but that doesn't guarantee immutability:

For example

```
/**
 * Class Action
 * 
 * @property-read DateTime $time
 * @property-read string       $label
 */
class Action
{
    /**
     * @var DateTime
     */
    private $time;

    /**
     * @var int
     */
    private $label;
    
    /**
     * @param $time DateTime
     * @param $label string
     */
    public function __construct(DateTime $time, $label)
    {
        $this->time = clone $time;
        $this->label = $label;
    }

    public function __get($prop){
        if (property_exists($this, $prop)) {
            return $this->{$prop};
        } else {
            $class = get_class($this);
            trigger_error("Undefined property: $class::$prop", E_USER_NOTICE);
        }
    }

}

$action = new Action(new DateTime(), 'WTF_JUST_HAPPENED?');
// Time gets modified, even though the member is private in this object
$action->time->modify('+1 year');
```

All these cases that can lead to objects changing values can be left outside of the application runtime of course if we just add an `@immutable` tag to our class, and let our IDE give a warning every time we attempt to make changes to any of the members of that class.

What do you guys think? Would you believe this would be a useful addition to PHPDoc?

**Comment by jaapio** [comment]
I think your interface should be immutable. Which means, making your class final so nobody can extend it to change your properties. Return only immutable objects or scalar values. DateTime can be replaced with http://php.net/manual/en/class.datetimeimmutable.php for example. 

However I can imagine that you want to document that the class is immutable. But that will not trigger a warning on the call to modify(), since time is a mutable object. wrapped in an immutable object. I don't see how this should work.

**Comment by Loupax** [comment]
I agree that this would not work with native objects unless we have a list of methods that change their state which might be too much trouble than it's worth it...

If we ignore the native ones though, it is possible to check if the members change their state inside a method call. The way I think of it, if a method call of an @immutable class ends up doing a `$this->something = 'whatever';` it counts as chaning the state of the original object. I'll just think out loud for a minute here.

```
/**
 * @immutable
 */
class Foo{
   public $bar;
   public function __construct(Bar $bar){
      $this->bar = $bar;
   }
}
class Bar{
   private $count;
   public function increment(){
      $this->count++;
   }
}

$bar = new Bar();
$foo = new Foo($bar);

$foo->bar->increment(); // Changes the state and we can detect it
$bar->increment();         // Also changes the state of $foo, but I cannot imagine how we can detect it
                                       // should propably ignore these cases and keep that in mind when designing our class
```

I'll think about it some more I guess

**Comment by mvriel** [comment]
My suggestion would be to discuss it with IDE vendors first; the tag can be used without definining it in phpDocumentor as any unrecognized tag is allowed by it and at current there is not much that we can do with that information that would influence the generated docs.

In other words: if you like it, use it. And then you can see if IDE vendors are interested in consuming that tag.

**Comment by Loupax** [comment]
Looks like I missunderstood a few things and mixed up the IDE implementation with phpDocumentor :/ 
Thanks for your time, I'll close this issue now as it is irrelevant to the project :)

**Comment by mvriel** [comment]
No problem, let us know if you have any other questions
