### ISSUE TITLE
Allow `@param` documentation on the params themselves

### ISSUE THREAD

**Issue by Kroc** [phpDocumentor/phpDocumentor2#1729]
```php
//basic concept
function doThatThing (
    /** @param the thing to use */
    $with_this_thing
,   /** @param the thing to do it on */
    $on_this_thing
) {
    //...
}
```

```php
//allowing `@return` at the end of the parameter list
function doThatThing (
    /** @param the thing to use */
    $with_this_thing
,   /** @param the thing to do it on */
    $on_this_thing
    /** @return status number */
) {
    //...
}
```

```php
//perhaps like this with PHP 7 return types
//(though the previous would suffice too)
function doThatThing (
    /** @param the thing to use */
    $with_this_thing
,   /** @param the thing to do it on */
    $on_this_thing
): int /** @return status number */ 
{
    //...
}
```

**Comment by jaapio** [comment]
I don't understand why you would need this. Is it to be able to remove the variable names from the docblock? There where some other issues that asked for less documentation requirements. But this will conflict with the PRS-5 (draft) standard. Beside that there are some issues that we can not detect and parse the code this way.  A function will have parameters, the php-parser we are using will not parse files just line by line.

Your last example will contain the following nodes.
- comment
- comment
- function
  - param
  - param2
- docblock
- docblock
- docblock

Like you can see there is no connection between the docblock and the params. So we cannot implement it this way.
