### ISSUE TITLE
version of current element question

### ISSUE THREAD

**Issue by BardiaAfshin** [phpDocumentor/phpDocumentor2#1736]
There's no aparent verbose example of how the $id variable is populated and maintained, specifically with git.

``` php
@version $Id: tags.version.pkg,v 1.2 2006-04-29 04:08:27 cellog Exp $;
```

taken from here: http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.version.pkg.html

If we can get a example of usage added to the documentation, it would become more self explanatory.

**Comment by jaapio** [comment]
You are linking to the old documenation. Think this explains it better. 
https://phpdoc.org/docs/latest/references/phpdoc/tags/version.html

Apart from that this is more a question about git than about phpdocumentor.
