### ISSUE TITLE
Can't install with Composer

### ISSUE THREAD

**Issue by Melindrea** [phpDocumentor/phpDocumentor2#1738]
When I try to install from Packagist I get the following message:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.8.5
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.8.4
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.8.3
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.8.2
    - Conclusion: don't install phpdocumentor/phpdocumentor v2.8.1
    - Conclusion: remove pimple/pimple v3.0.2
    - Installation request for phpdocumentor/phpdocumentor ^2.8 -> satisfiable by phpdocumentor/phpdocumentor[v2.8.0, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5].
    - Conclusion: don't install pimple/pimple v3.0.2
    - phpdocumentor/phpdocumentor v2.8.0 requires cilex/cilex ~1.0 -> satisfiable by cilex/cilex[1.0.0, 1.0.1, 1.1.0].
    - cilex/cilex 1.0.0 requires pimple/pimple 1.0.* -> satisfiable by pimple/pimple[1.0.0, v1.0.1, v1.0.2].
    - cilex/cilex 1.0.1 requires pimple/pimple 1.0.* -> satisfiable by pimple/pimple[1.0.0, v1.0.1, v1.0.2].
    - cilex/cilex 1.1.0 requires pimple/pimple ~1.0 -> satisfiable by pimple/pimple[1.0.0, v1.0.1, v1.0.2, v1.1.0, v1.1.1].
    - Can only install one of: pimple/pimple[1.0.0, v3.0.2].
    - Can only install one of: pimple/pimple[v1.0.1, v3.0.2].
    - Can only install one of: pimple/pimple[v1.0.2, v3.0.2].
    - Can only install one of: pimple/pimple[v1.1.0, v3.0.2].
    - Can only install one of: pimple/pimple[v1.1.1, v3.0.2].
    - Installation request for pimple/pimple == 3.0.2.0 -> satisfiable by pimple/pimple[v3.0.2].
```

**Comment by mvriel** [comment]
It would seem that you have a dependency on Pimple 3 in your own project; since phpDocumentor 2 uses Pimple 2 that conflicts. I would suggest to consume phpDocumentor using the PHAR as that will allow you to circumvent such conflicting dependencies

**Comment by Melindrea** [comment]
Yes, I use Slim as my miniframework. Is it in the works to change to Pimple 3 in a later version, or …? (Either way, I’ll go with other ways of the dependency)

**Comment by mvriel** [comment]
phpDocumentor 3 will no longer use Cilex and Pimple; there we will start using PHP-DI 5 with no framework. So there may be other dependency conflicts but not with Pimple 3. 

With phpDocumentor 3 we are also going to make the PHAR installation the preferred route and tell people that installing with composer is a bit of 'at your own risk' as an installation using Composer has various caveats and runs the risk of conflicts; as a project we would prefer to focus on fixing issues in the other installation channels and adding new features and hope that the community will pick up on the composer caveats if they really want to install phpDocumentor using Composer.

**Comment by Melindrea** [comment]
Alright, thank you.

You can close this.
