### ISSUE TITLE
File name is missing after transformation

### ISSUE THREAD

**Issue by olgapshenichnikova** [phpDocumentor/phpDocumentor2#1749]
I use command phpdoc -d . -t out_dir
and get wonderful output, except one point:
In the right sidebar where are: 
"FILE, Tags, package, Default"
there are no file name... I was expecting file name contains the function...
Here is the output:
http://cs-doc.ip-5.ru/Tygh/

I installer phpDoccumentor using PEAR on Ubuntu 15.10

**Comment by mvriel** [comment]
This is resolved on master and will become available with the next release
