### ISSUE TITLE
Zend template empty

### ISSUE THREAD

**Issue by javiertrejo** [phpDocumentor/phpDocumentor2#1756]
Hi, i have a trouble when i use zend template i got and empty page, but when i use the responsive-twig template i can view the class methods and other info.

Also, in the responsive-twig template the tag @link and @see doesn't display the links to interactive navigation when the target is an external link like that:

@link http://silex.sensiolabs.org/doc/providers.html Silex provider documentation

I doing something bad?

![responsive-twig](https://cloud.githubusercontent.com/assets/6468154/14858534/cc47253e-0c76-11e6-8b3b-3ded1426a31c.png)
![zend](https://cloud.githubusercontent.com/assets/6468154/14858533/cc44ee04-0c76-11e6-87b0-53b48c64f885.png)

**Comment by jaapio** [comment]
I just had an internal report from @mbed67. She reported the same thing. I'm investigating this.

**Comment by jaapio** [comment]
@javiertrejo could you please check if the version of phpdocumentor in master fixes your issue? Please reopen/comment on this issue when it was not solved.
