### ISSUE TITLE
Value of @version tag missing

### ISSUE THREAD

**Issue by PhrozenByte** [phpDocumentor/phpDocumentor2#1762]
I'm not sure whether this has been reported already, GitHub's search engine doesn't work quite well for generic search terms like `@version` :unamused:

The clean template doesn't print the value of a block `@version` tag (phpDocumentor 2.9.0). I haven't tested other templates, but based on how the tags are processed in the clean template, I assume that this is template-independent.

``` php
/**
 * …
 *
 * @version 1.0
 */
```

![bildschirmfoto von 2016-05-23 16 38 48](https://cloud.githubusercontent.com/assets/920356/15474358/e383e4f6-2104-11e6-90b6-9205332ab3e8.png)

Also see http://picocms.org/phpDoc/master/classes/Pico.html

**Comment by mvriel** [comment]
This issue has been resolved and is available on master
