### ISSUE TITLE
phpDocumentor 2.9.0 reports itself as 2.8.5

### ISSUE THREAD

**Issue by PhrozenByte** [phpDocumentor/phpDocumentor2#1763]
The [`VERSION` file](https://github.com/phpDocumentor/phpDocumentor2/blob/v2.9.0/VERSION) needs to be updated.

```
$ grep -A 1 '"name": "phpdocumentor/phpdocumentor"' composer.lock 
            "name": "phpdocumentor/phpdocumentor",
            "version": "v2.9.0",

$ vendor/bin/phpdoc --version
phpDocumentor version 2.8.5
```

**Comment by mvriel** [comment]
This issue will resolve itself after v2.9.1 is released; I prefer to focus on fixing bugs and releasing that version than trying to re-tag and re-release v2.9.0. Our apologies for the inconvenience
