### ISSUE TITLE
Cannot install v2.9.0 by PEAR

### ISSUE THREAD

**Issue by grzegorzmorzyckissh** [phpDocumentor/phpDocumentor2#1764]
OS: Debian 8
PHP7

``` sh
$ pear install phpdoc/phpDocumentor
downloading phpDocumentor-2.8.5.tgz ...
Starting to download phpDocumentor-2.8.5.tgz (8,184,822 bytes)
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done: 8,184,822 bytes
install ok: channel://pear.phpdoc.org/phpDocumentor-2.8.5
$ phpdoc --version
phpDocumentor version 2.8.5
$ pear uninstall phpdoc/phpDocumentor
uninstall ok: channel://pear.phpdoc.org/phpDocumentor-2.8.5
$ pear install phpdoc/phpDocumentor-2.9.0
Failed to download phpdoc/phpDocumentor, version "2.9.0", latest release is version 2.8.5, stability "stable", use "channel://pear.phpdoc.org/phpDocumentor-2.8.5" to install
install failed
$ pear install phpdoc/phpDocumentor-2.9.0beta
Failed to download phpdoc/phpDocumentor, version "2.9.0beta", latest release is version 2.8.5, stability "stable", use "channel://pear.phpdoc.org/phpDocumentor-2.8.5" to install
install failed
$ pear install phpdoc/phpDocumentor-2.9.0alpha
Failed to download phpdoc/phpDocumentor, version "2.9.0alpha", latest release is version 2.8.5, stability "stable", use "channel://pear.phpdoc.org/phpDocumentor-2.8.5" to install
install failed
$ pear install phpdoc/phpDocumentor-2.9.0devel
Failed to download phpdoc/phpDocumentor, version "2.9.0devel", latest release is version 2.8.5, stability "stable", use "channel://pear.phpdoc.org/phpDocumentor-2.8.5" to install
install failed
$ pear install phpdoc/phpDocumentor-2.9.0dev
Failed to download phpdoc/phpDocumentor, version "2.9.0dev", latest release is version 2.8.5, stability "stable", use "channel://pear.phpdoc.org/phpDocumentor-2.8.5" to install
install failed
```

There is also no v2.9.0 on  [yours channel site](https://pear.phpdoc.org/). Is there any way to download v2.9.0 by PEAR??

**Comment by jaapio** [comment]
Thanks for reporting. We are aware of the fact that we still have to update our channel.

**Comment by grzegorzmorzyckissh** [comment]
Thanks for the reply. Unfortunately i suppose that information in v2.9.0 tag description about possibility of downloading by PEAR on Windows also would be not correct until this channel update.

**Comment by jaapio** [comment]
that's true.

**Comment by avindra** [comment]
The PHAR is also not up to date:

```
--2016-07-05 10:00:02--  http://phpdoc.org/phpDocumentor.phar
Location: https://phpdoc.org/phpDocumentor.phar [following]
--2016-07-05 10:00:03--  https://phpdoc.org/phpDocumentor.phar
Proxy request sent, awaiting response... 200 OK
Length: 17089708 (16M) [application/octet-stream]
Saving to: `phpDocumentor.phar'

100%[===============================================================>] 17,089,708   600K/s   in 28s

2016-07-05 10:00:32 (594 KB/s) - `phpDocumentor.phar' saved [17089708/17089708]

phpDocumentor version v2.8.5
```

Any eta on a release?

**Comment by avindra** [comment]
I cannot install this via composer either (I think because our project requires `symfony/console@3.1.2`):


```
$ composer require --dev phpdocumentor/phpdocumentor
Using version ^2.9 for phpdocumentor/phpdocumentor
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpdocumentor/phpdocumentor ^2.9 -> satisfiable by phpdocumentor/phpdocumentor[v2.9.0].
    - phpdocumentor/phpdocumentor v2.9.0 requires symfony/console ~2.3 -> satisfiable by symfony/console[2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev, 2.8.x-dev, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.0-BETA1, v2.5.0-BETA2, v2.5.0-RC1, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.0-BETA1, v2.7.0-BETA2, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

Is anyone working on these problems yet?

**Comment by avindra** [comment]
@jaapio : Is my problem with the PHAR related to #1763 ?

**Comment by jaapio** [comment]
Issue #1763 is only about the versionnumber in the phar. There are no issues with the phar file as far as I know. You should be able to use it, if not please create an issue and we will see how we can help you out.

**Comment by flxsource** [comment]
Is there any update to this, or anything that can be done? It is simple a matter of updating the PEAR channel?

**Comment by NHellFire** [comment]
Well, this explains why it didn't work after updating to PHP 7. The channel and phar on the site *still* haven't been updated.

**Comment by SharkWipf** [comment]
Is the website 100% dependent on @mvriel?  
From what I can find they have basically stopped contributing to this project altogether, and have become largely inactive on Github in general lately.  
![image](https://cloud.githubusercontent.com/assets/751205/25231022/7cad7dbe-25d6-11e7-8c88-280855d5f09f.png)
![image](https://cloud.githubusercontent.com/assets/751205/25231029/8466e7d4-25d6-11e7-951b-d86774f2ec4a.png)

**Comment by jaapio** [comment]
@mvriel was the only active developer of this project for a long time. A few years ago I jumped in but due a lag of time we are not able to work on the project active. We are all doing this in our spare time, beside a fulltime job and many other side projects.

Please feel free to open pr's. I will try to handle them as soon as possible.

**Comment by SharkWipf** [comment]
Fair enough, I completely understand. Thanks for your replies.  

I know this doesn't really have anything to do with you, but I replied because I'm pretty much dependent on this project.  
Due to the way @JetBrains implements phpDocumentor in PHPStorm, trying to use a different documentation engine causes conflicts and actually breaks some basic IDE features (they use phpDocumentor internally for some completion features but allow users to extend the autogenerated internal documentation, if this breaks the lookup features for these functions break too).  
Because of this, users of PHPStorm are pretty much dependent on phpDocumentor if they want nice generated documentation.  
Again, not at all your problem of course, but I did want you to know there are users dependent on this project because of that.  
JetBrains already sponsored you I believe, it'd be great if they could put people on actively contributing to phpDocumentor.

I have admittedly never used phpDocumentor before, I'll start using it today for the first time, if I find any issues I can fix I'll be sure to send in PRs.

**Comment by ashnazg** [comment]
@mvriel , is there anything special I need to know about the branches I see?  Should I work against `develop` for any fixes?

**Comment by jaapio** [comment]
Develop contains a new in development version of phpdocumentor. Please use
master for fixes on v2.

Op do 20 apr. 2017 19:29 schreef Chuck Burgess <notifications@github.com>:

**Comment by miken32** [comment]
For those coming here looking for a solution:

    wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor-2.9.0.tgz
    sudo pear install phpDocumentor-2.9.0.tgz

**Comment by mvriel** [comment]
All workarounds are no longer needed, I have updated both the website and the pear channel for the latest version. Please be aware that the version with --version does report 2.8.5 due to a packaging mistake where we forgot to update the version number. I won't be fixing that issue as 2.9.1 should be released soon :D

I'm sorry that it took so long to do the update, we are discussing way where we can automate this process so that it doesn't rely on my

**Comment by miken32** [comment]
I assume this problem is related; the certificate at pear.phpdoc.org has expired. `pear` won't talk to it and Firefox tells me:

pear.phpdoc.org uses an invalid security certificate.
The certificate expired on May 21, 2017 at 11:40 PM. The current time is May 23, 2017 at 12:27 PM.
