### ISSUE TITLE
Invalid @see class references in clean template

### ISSUE THREAD

**Issue by PhrozenByte** [phpDocumentor/phpDocumentor2#1767]
When using the `@see` block tag to reference a class in the root namespace (e.g. `Pico`), phpDocumentor 2.9.0 fails to interpret the namespace and shows a reference to `\\Pico` in the clean template (the link target is a empty string).

``` php
/**
 * …
 *
 * @see Pico
 */
```

![bildschirmfoto von 2016-05-25 22 29 50](https://cloud.githubusercontent.com/assets/920356/15555278/5171b7bc-22c8-11e6-90ce-2c24da842286.png)

Also see http://picocms.org/phpDoc/master/classes/PicoPluginInterface.html#method_getPico

**Comment by mbed67** [comment]
This issue has been resolved with the following PR: https://github.com/phpDocumentor/phpDocumentor2/pull/1848
