### ISSUE TITLE
@property annotation in trait

### ISSUE THREAD

**Issue by HeeJoon-Kim** [phpDocumentor/phpDocumentor2#1772]
Hi.

A property annotation in trait file, marked double dollar.

![image](https://cloud.githubusercontent.com/assets/20118729/16324701/a52ce152-39f1-11e6-9750-770807245c26.png)

Here is code.
![image](https://cloud.githubusercontent.com/assets/20118729/16325028/374f25c4-39f5-11e6-9da0-4f7fb74374b8.png)

In addition, xxxx.php.txt file is exists but, does not show.

**Comment by jaapio** [comment]
Can you add the name of the template you are using? Templates are responsible for the view. So it will be an issue of a specific template.

**Comment by HeeJoon-Kim** [comment]
Yes, you're right. It's a template problem. 
When i use a "clean" template, double marked dollar is appeared. But, responsive-twig is not.

**Comment by jaapio** [comment]
@mbed67 can you have a look at this one?

**Comment by mvriel** [comment]
I moved this item to 2.10.0 because we want to release 2.9.1

**Comment by mvriel** [comment]
This item was resolved as part of another issue and will be included in the next release
