### ISSUE TITLE
Anonymous class in object method issue.

### ISSUE THREAD

**Issue by HeeJoon-Kim** [phpDocumentor/phpDocumentor2#1777]
``` php
<?php
/**
 * Test class
 */
class TTT
{
    /**
     * Test method
     * @return string
     */
    public function a() {
        $a = null ?? new class { public function export() { return null; } };
        return 'test';
    }
}
```

**Anonymous class in object method occurs an error.**

``` text
[2016-07-12 17:05:40] phpDocumentor.ERROR: E_RECOVERABLE_ERROR: Object of class PhpParser\Node\Stmt\Class_ could not be converted to string {"code":4096,"message":"Object of class PhpParser\\Node\\Stmt\\Class_ could not be converted to string","file":"vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php","line":172,"context":[]} []

Catchable fatal error: Object of class PhpParser\Node\Stmt\Class_ could not be converted to string in /svc/web/common/common/src/phpDoc/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php on line 172
```

I added a "__toString" to anonymous class, but it was same results.

**Comment by richwandell** [comment]
I am having the same issue

**Comment by jaapio** [comment]
Resolved in our latest release v3.0.0-alpha1.

**Comment by varunsridharan** [comment]
@jaapio when will 3.0 be released ?

**Comment by jaapio** [comment]
It will be released when the work is done. We are working hard to get it ready. But our time is limited.

All help is welcome to speed up the process.

You could try the rc version which is quite stable. Please report any issues you have with the rc release.

**Comment by varunsridharan** [comment]
> It will be released when the work is done. 

Great 😆 

---

> We are working hard to get it ready. But our time is limited.

🙇 i agree and respect. let me check what i can do to help. as i am not much experienced on this

**Comment by jaapio** [comment]
If you are able to report any issues you have with the latest release it helps a lot :-) especially when you provide test cases.
