### ISSUE TITLE
--sourcecode flag ignored, source code is always generated,

### ISSUE THREAD

**Issue by MortimerCat** [phpDocumentor/phpDocumentor2#1780]
Not everyone wants to publish their source code, that is why there is a sourcecode flag. 

The latest version 2.9.0 makes my source code available even though I do not specify --sourcecode   Glancing at the code, I can not see anywhere that actually checks the parameter?

**Comment by Rozbo** [comment]
I also met this annoying bug, almost let me give up it

**Comment by rodrigolopezguerra** [comment]
+1 , there's a solution or workaround for this ?

**Comment by mvriel** [comment]
This issue is resolved on master using commit 945554c48a1fa9ca9904ce4eaccfa0c3d53474ec and will become available with the next release
