### ISSUE TITLE
uncought excpect regarding monolog

### ISSUE THREAD

**Issue by feamsr00** [phpDocumentor/phpDocumentor2#1782]
Hi,

When trying to create my first doc with phpdoc I encuntered an unhandled exception:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in phar://C:/dev/tools/phpdoc.phar/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in phar://C:/dev/tools/phpdoc.phar/vendor/monolog/monolog/src/Monolog/ErrorHandler.php on line 122
```
phpDoc: 2.8.5
php: 7.0.3

Let me know if you need any more information to solve this. Thanks!

**Comment by jaapio** [comment]
2.9 which is available solves this issue. Please dowload the new phar https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v2.9.0

**Comment by dtoro** [comment]
2.9 does not solve this issue FYI

**Comment by zakkates** [comment]
This is the message i'm receiving. Running 2.9. PHP 7.2.1
 
> Fatal error: Uncaught TypeError: Argument 1 passed to Monolog\ErrorHandler::handleException() must be an instance of Exception, instance of Error given in /usr/local/pear/share/pear/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php:122
Stack trace:
#0 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in /usr/local/pear/share/pear/phpDocumentor/vendor/monolog/monolog/src/Monolog/ErrorHandler.php on line 122``
