### ISSUE TITLE
phpdocumentor/flyfinder

### ISSUE THREAD

**Issue by spagu** [phpDocumentor/phpDocumentor2#1786]
- Installation request for phpdocumentor/phpdocumentor 3.0.x-dev -> satisfiable by phpdocumentor/phpdocumentor[3.0.x-dev].
    - phpdocumentor/phpdocumentor 3.0.x-dev requires phpdocumentor/flyfinder ^1.0@dev -> satisfiable by phpdocumentor/flyfinder[1.0.0-alpha1] but these conflict with your requirements or minimum-stability.

**Comment by kix** [comment]
@spagu, you could try adding `"minimum-stability": "dev"` to your `composer.json`. If that's not an option for you, maybe you should instead require stable `phpdocumentor/phpdocumentor`?

**Comment by jaapio** [comment]
You definitely should use a stable version of phpdocumentor. V3 is still under development. And is not in an usable state at the moment.

**Comment by spagu** [comment]
the problem is it is conflicting modern packages like slim3 with the depedencies.  The only solution I found was to install phpdoc2 as pear not composer and remove from requirement-dev.

**Comment by jaapio** [comment]
That's why we do not recommend to install phpdocumentor using composer. I think we might even stop publishing it as a composer package or have a look if we can provide the phar via composer.
