### ISSUE TITLE
__callStatic autocomplete

### ISSUE THREAD

**Issue by undercloud** [phpDocumentor/phpDocumentor2#1790]
Sorry, it hard to explain for me but I try to describe...
Is this possible create something like this:

```
<?php
/** Proxy */
class Facade
{
	/**
	 * @method SomeClass *
	 * or
	 * @return SomeClass
	 */
	public static function __callStatic($method, $args)
	{
		$obj = new SomeClass;

		return call_user_func_array([$obj, $method], $args);
	}
}
?>
```
then type in ide:
```
<?php
	Facade::/* ide popup list of methods for SomeClass */
?>
```

**Comment by undercloud** [comment]
I found http://windwalker.io/documentation/3.x/core/ioc-container.html#facade
Maybe ```@see``` make this trick?

**Comment by jaapio** [comment]
Autocompletion of IDE's doesn't have any thing related to phpdocumentor. We are using the same annotations but in a whole different way. Phpdocumentor is not used by the ide's to generate autocompletion. If you want to have this kind of features you should contact your IDE vendor.
