### ISSUE TITLE
Could not generate Documentation

### ISSUE THREAD

**Issue by janlueders** [phpDocumentor/phpDocumentor2#1793]
Hi,
i found a closed Issue with the same content. 
I use Ubunut 16.04 Gnome and i got this response equal with or without sudo

> pear install phpdoc/phpDocumentor
phpdoc/phpDocumentor is already installed and is the same as the released version 2.8.5
install failed

timber@timber-Lenovo-ideapad-500S-13ISK:/storage/web/www$ sudo phpdoc run -d linqfish/ -t lingfishdoc/

PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:193
Stack trace:
#0 /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(171): Doctrine\Common\Annotations\AnnotationException::optimizerPlusLoadComments()
#1 /usr/share/php/phpDocumentor/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php(338): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 /usr/share/php/phpDocumentor/src/Cilex/Provider/JmsSerializerServiceProvider.php(73): JMS\Serializer\SerializerBuilder->build()
#3 /usr/share/php/phpDocumentor/vendor/pimple/pimple/lib/Pimple.php(126): Cilex\Provider\JmsSerializerServiceProvider->Cilex\Provider\{closure}(Object(phpDocumentor\Application))
#4 /usr/share/php/phpDocumentor/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{cl in /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 193

**Comment by jaapio** [comment]
php is telling you what is wrong.

```
PHP Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in 
```

**Comment by janlueders** [comment]
no i'm sorry that did'nt help. not with php 7.0

but this one helps allot. 

http://askubuntu.com/questions/810739/php-7-and-phpdocumentor-install
