### ISSUE TITLE
Typehint for (std)objects (json-like) and multidimensional arrays support

### ISSUE THREAD

**Issue by RdeWilde** [phpDocumentor/phpDocumentor2#1794]
I would love to see support for annotation on multidimensional arrays and/or standard object properties.

I added some resources in this issue for another project https://github.com/machour/yii2-swagger-api/issues/5#issuecomment-256023138

Example snippets;
Object

```
/**
 * @property {
 *  @property int $id Composition id
 *  @property int $amount Composition amount
 * } $compositions
 */
$array = (Object)[
   'id' => 1
   'amount' => 2
];
```

Array

```
/**
 * @property [
 *  @property int $id Composition id
 *  @property int $amount Composition amount
 * ] $compositions
 */
$array = [
   'id' => 1
   'amount' => 2
];
```

**Comment by iluuu1994** [comment]
This looks a lot like [shapes](https://docs.hhvm.com/hack/shapes/introduction) in Hack. Objects have built in support for interfaces which are probably a better match. For arrays a shape-like definition could be useful.

**Comment by mvriel** [comment]
This item is addressed in other issues and has been discussed in the PSR-5 spec. As this is a duplicate I will be closing this issue. Unfortunately I cannot give a timeframe when this lands in phpDocumentor as it is being specced and then needs to be implemented
