### ISSUE TITLE
Include a `@refactor` tag or something Similar to mark code to be revisited, but that works.

### ISSUE THREAD

**Issue by christopher-wilson** [phpDocumentor/phpDocumentor2#1795]
We have `@todo`, but it implies that code doesn't work or is incomplete. Looking at the list of other tags, there doesn't seem to be an alternative. For the sake of encouraging convention, can we include something like `@refactor` or `@revisit`?

**Comment by mvriel** [comment]
At this point we are trying not to include to many new tags and are investigating using specialized forms of existing tags (as a sort of subtypes). This is still under investigation and won't be resolved soon.

I recommend using Markers is you would like a custom declaration of a location in the code, please see https://phpdoc.org/docs/latest/guides/running-phpdocumentor.html#markers for more information
