### ISSUE TITLE
Howto: Restart parser

### ISSUE THREAD

**Issue by es02** [phpDocumentor/phpDocumentor2#1798]
After 2.5hrs on a large project phpDoc just conks out:
```
Storing cache in "/home/es02/api-docs" .. OK
Load cache                                                         ..    0.037s
Preparing template "clean"                                         ..    0.027s
Preparing 17 transformations                                       ..    0.000s
Build "elements" index                                             ..   24.394s
Replace textual FQCNs with object aliases                          ..   26.606s
Resolve @link and @see tags in descriptions                        .. 
```

I have 520mb of cache files but the documentation for what I suspect to be my solution is missing: https://phpdoc.org/docs/latest/references/commands/project_parse.html

I have an output folder with an empty build folder in it.

Documenter works fine on small projects so I'm guessing I may need to make some changes to my php.ini file?

**Comment by jaapio** [comment]
It's imposible to continue the parsing process. You can recall the run command which will load the cache again. But I think it will stop again. Since the link and see tags have to be resolved with all project code in memory. We are trying to resolve this for version 3. But that's kind of hard to solve. 

You could try to raise your memory limits of php.

**Comment by mvriel** [comment]
When I look at this and see that it took 2.5 hours to resolve the link and see tags it seems to me phpDocumentor may have gotten into an infinite loop there. This should take this long compared to the other execution times.

Is this a public project that we can try to run the documention on ourselves?

**Comment by es02** [comment]
Unfortunately not, it's internal corporate code.

**Comment by jaapio** [comment]
Please try again with our new release v3.0.0-alpha. And open a new issue when still applicable.
