### ISSUE TITLE
@callable type hint parameters by using it like @method parameters

### ISSUE THREAD

**Issue by brainfoolong** [phpDocumentor/phpDocumentor2#1799]
According to 
https://phpdoc.org/docs/latest/references/phpdoc/tags/method.html
we can define method parameters easily with correc type hints.

Why not using this also for `@callable` or `Closure`?

Example:
```
class Test{
    /**
     * Add a callback
     * @param Closure $closure(integer $id, string $foo)
     */
    public function addCallback(Closure $closure){
        // IDE's now can pick-up this information and providing for example auto completion or something usefull
    }
    /**
     * Add a callback by callable
     * @param callable $callable(integer $id, string $foo)
     */
    public function addCallbackByCallable(callable $callable){
        // IDE's now can pick-up this information and providing for example auto completion or something usefull
    }
}
```

**Comment by mvriel** [comment]
Documenting anonymous functions is an ongoing discussion as this has several caveats to take into account. Since this is covered in other issues I will be closing this as a duplicate. Nonetheless I would like to thank you for bringing this helps us to gauge interest in this improvement
