### ISSUE TITLE
Syntax error, unexpected '{' in use grouping (php 7.0 & phpdoc 2.9.0)

### ISSUE THREAD

**Issue by ilianiv** [phpDocumentor/phpDocumentor2#1801]
I get `Parse Error: Syntax error, unexpected '{', expecting T_STRING` using use grouping feature:

```
use MyNamespace\Cache\{   <--
    CacheFactory, CacheFactoryContract
};
```
___
PHP 7.0.13
phpDocumentor 2.9.0

**Comment by jaapio** [comment]
We do not support this notation.

**Comment by ilianiv** [comment]
Hm, it is interesting that you insist phpdoc 2.9.0 supports php 7.0 syntax here https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v2.9.0 and php 7.0 has [group use declarations](https://wiki.php.net/rfc/group_use_declarations) that is not supported. 😕

**Comment by adjenks** [comment]
It's a feature of the 7.0 language syntax, why would you not support it?
