### ISSUE TITLE
The given template <comma separated templates> could not be found or is not readable

### ISSUE THREAD

**Issue by NestorAcevedo** [phpDocumentor/phpDocumentor2#1802]
Hi, according with the documentation: [https://www.phpdoc.org/docs/latest/getting-started/changing-the-look-and-feel.html](url) I could use more than one template but when I do for example `--template="zend,responsive-twig` or `--template="checkstyle,clean"` I get the error 

> **The given template zend,responsive-twig could not be found or is not readable**

but if I use for example `--template zend --template responsive-twig` phpdoc takes only the last one template parameter.

I am using phpDocumentor v2.8.5

Regards

**Comment by mvriel** [comment]
Hello @NestorAcevedo,

I have resolved the issue on master and it will be included in the next release. Thanks for mentioning this to us!
