### ISSUE TITLE
phpDocs requires at least two parameters for variadic

### ISSUE THREAD

**Issue by CharlotteDunois** [phpDocumentor/phpDocumentor2#1803]
I have an issue where I have to define at least two parameters to make a variadic method parameter to appear in the docs. Why does the docBlock require at least two parameters for variadic method parameters? If I just define one parameter with variadic, it doesn't appear in the docs. Is there any *legit* reason?  [PHP](https://3v4l.org/KRdBa) does not require two parameters, so why does phpDoc?

I have this as phpDoc:

      /**
     * Runs async multiple HTTPClient instances.
     *
     * @param  HTTPClient  ...$inst
     * @return bool
     */

But I just see this in the docs:

    multiple(\CharlotteDunois\HTTP\HTTPClient  $inst) : boolean
    Runs async multiple HTTPClient instances.

If I add now a second parameter, making that one variadic instead, I do see it as variadic in the docs.

    /**
     * Runs async multiple HTTPClient instances.
     *
     * @param  HTTPClient  $inst
     * @param  HTTPClient  ...$second
     * @return bool
     */

Docs:

    multiple(\CharlotteDunois\HTTP\HTTPClient  $inst, \CharlotteDunois\HTTP\HTTPClient  ...$second) : boolean
    Runs async multiple HTTPClient instances.

I am using phpDocumentor 2.9.0 from the Pear phpDoc channel.

Best Regards.

**Comment by mvriel** [comment]
This issue is resolved on master using commit 0a7f8d0f1845457baf0b4e97c2b17e06c9751525; it will become available with the next release
