### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by Rikvola-Joshua** [phpDocumentor/phpDocumentor2#1805]
D:\XAMPP\php>phpdoc -h
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'phpDocumentor expected to find an autoloader at "D:\XAMPP\php\pear\phpDocumentor\src\phpDocument
or/../../vendor/autoload.php" but it was not there. Usually this is because the "composer install" command has not been ran yet. If this is not the case, please open
an issue at http://github.com/phpDocumentor/phpDocumentor2 detailing what installation method you used, which path is mentioned in this error message and any other re
levant information.' in D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php:102
Stack trace:
#0 D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php(60): phpDocumentor\Bootstrap->createAutoloader('D:\\XAMPP\\php\\pe...')
#1 D:\XAMPP\php\phpdoc(23): phpDocumentor\Bootstrap->initialize()
#2 {main}
  thrown in D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 102

Fatal error: Uncaught exception 'RuntimeException' with message 'phpDocumentor expected to find an autoloader at "D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor/..
/../vendor/autoload.php" but it was not there. Usually this is because the "composer install" command has not been ran yet. If this is not the case, please open an is
sue at http://github.com/phpDocumentor/phpDocumentor2 detailing what installation method you used, which path is mentioned in this error message and any other relevan
t information.' in D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php:102
Stack trace:
#0 D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php(60): phpDocumentor\Bootstrap->createAutoloader('D:\\XAMPP\\php\\pe...')
#1 D:\XAMPP\php\phpdoc(23): phpDocumentor\Bootstrap->initialize()
#2 {main}
  thrown in D:\XAMPP\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 102

**Comment by jaapio** [comment]
Can you please describe what you did?

**Comment by Rikvola-Joshua** [comment]
I've installed the phpDocumentor on my Windows 10 machine, running the latest PHP version(in XAMPP) and then I run the command:
phpdoc -h
Thats all :)

**Comment by jaapio** [comment]
I think this is caused because our pear package is not updated to support php7

**Comment by Rikvola-Joshua** [comment]
Okay, i understand, thats a problem, wich one should i use in combination with php7?

**Comment by CharlotteDunois** [comment]
I run phpdoc (from PEAR phpdoc channel) with PHP7 and it works with no issues.

**Comment by Rikvola-Joshua** [comment]
Do you use Windows and XAMPP, I am a lazy man, with this setup i have never issues, exept this one, do I need another way for the Installing?

**Comment by CharlotteDunois** [comment]
Yes, Windows with XAMPP. I followed the install instructions for PEAR. Though I discovered you need to use `pear` ("run") to be able to use the `phpdoc` command (whenever you open a new command line window).

**Comment by Rikvola-Joshua** [comment]
Okay, thanks a lot, I will try it when i have time (sunday) and will give a feedback. 
:))

**Comment by mvriel** [comment]
@Rikvola-Joshua there appeared to have been an issue when packaging phpDocumentor 2.9.0 and I have just updated our PEAR channel to correctly expose this package. Can you retry using it? I am confident this will solve the issue and close this but should this not be the case, please mention this in the issue and we will reopen it
