### ISSUE TITLE
Global namespace access not correctly interpreted (clean template)

### ISSUE THREAD

**Issue by brunoczim** [phpDocumentor/phpDocumentor2#1807]
Lets suppose this code:
```php
<?php

namespace A;

class Error extends \Exception{

}
```

The template clean should generate a class graph in which class Error of namespace A inherits from class Exception of global namespace. But it generates a  class graph in which class Error of namespace A inherits from class xception of no namespace. 

EDIT: it isn't only in clean template

**Comment by jaapio** [comment]
There is no global namespace, Exception isn't located in a namespace so that seems to be correct for me.

**Comment by brunoczim** [comment]
Yes, there is a global space: 
http://php.net/manual/en/language.namespaces.global.php

And the phpdoc interpretes \Exception as if the "E" character is escaped, so it generates "xception" class in the graph.

**Comment by mvriel** [comment]
Thanks for reporting this issue; apparently 'unknown' classes were not properly integrated in the graph. I have changed the writer that creates the GraphViz dot file to add missing namespace and correctly connect the unknown classes

**Comment by robertmain** [comment]
![image](https://user-images.githubusercontent.com/537684/35168597-83331f08-fd27-11e7-80a5-5b8ee6f4b206.png)

I seem to be still having this issue..
