### ISSUE TITLE
Count called on non-countable object

### ISSUE THREAD

**Issue by kelunik** [phpDocumentor/phpDocumentor2#1808]
https://github.com/phpDocumentor/phpDocumentor2/blob/v2.9.0/src/phpDocumentor/Plugin/Core/Descriptor/Validator/Constraints/Functions/IsArgumentInDocBlockValidator.php#L33 calls count on either a `string` or an object that doesn't implement `Countable`. It seems to me, that `count` is never the right thing to call here. Instead something like `!== null` should be used.

This code results in a warning on PHP 7.2.

**Comment by mvriel** [comment]
Thank you for mentioning this, I have removed the check as it seems to be ineffective and have made a note to review this piece of the code as there seem to be a few oddities there. The removed check is present in master and will be present in the next release
