### ISSUE TITLE
Provide the signature of a method

### ISSUE THREAD

**Issue by tflori** [phpDocumentor/phpDocumentor2#1809]
Currently I'm writing a markdown template and want to have the signature of a method shown in a code block.

The Problem is that code blocks are scrollable. And anyway a one line signature might be not readable.

But to write it in template is also a pain in the ***. I propose a new method `public function getSignature($maxLength = 0): string` in `MethodDescriptor`:

```php
<?php

class MethodDescriptor extends DescriptorAbstract implements Interfaces\MethodInterface, Interfaces\VisibilityInterface
{

    /**
     * Get the signature of method
     *
     * If the signature is longer than $maxLength it returns with linebreaks.
     *
     * @param int $maxLength
     * @return string
     */
    public function getSignature($maxLength = 0)
    {
        $signature = 'function ' . $this->getName() . '(';

        if ($this->getArguments()->count() > 0) {
            $args = [];

            /** @var ArgumentDescriptor $argument */
            foreach ($this->getArguments() as $argument) {
                $arg = $argument->getName();

                if ($argument->isByReference()) {
                    $arg = '&' . $arg;
                }

                if ($argument->getTypes()->count() > 0 && $argument->getTypes()->get(0)  != 'mixed') {
                    $arg = $argument->getTypes()->get(0) . ' ' . $arg;
                }

                if ($argument->getDefault()) {
                    $arg .= ' = ' . $argument->getDefault();
                }

                $args[] = $arg;
            }

            $signature .= ' ' . implode(', ' , $args) . ' ';
        }

        $signature .= ')';

        if ($this->isStatic()) {
            $signature = 'static ' . $signature;
        }

        $signature = $this->getVisibility() . ' ' . $signature;

        if ($this->isAbstract()) {
            $signature = 'abstract ' . $signature;
        }

        if ($this->isFinal()) {
            $signature = 'final ' . $signature;
        }

        if ($this->getResponse()) {
            $types = $this->getResponse()->getTypes()->getAll();

            if (reset($types) == 'self') {
                $signature .= ': ' . $this->getParent()->getName();
            } else {
                $signature .= ': ' . implode('|', $types);
            }
        } elseif ($this->name === '__construct') {
            $signature .= ': ' . $this->getParent()->getName();
        }

        if ($maxLength &&
            $maxLength < strlen($signature) &&
            preg_match('/^(.*)\( (.*) \)($|:.*$)/', $signature, $match)
        ) {
            $lines = [$match[1] . '('];

            $line = '    ';
            foreach (explode(', ', $match[2]) as $arg) {
                if (strlen($line) + strlen($arg) + 1 >= $maxLength) {
                    $lines[] = $line;
                    $line = '    ';
                }
                $line .= $arg . ', ';
            }

            $lines[] = substr($line, 0, -2);

            $lines[] = ')' . $match[3];

            return implode("\n", $lines);
        }

        return $signature;
    }
}
```

**Comment by jaapio** [comment]
I do not understand why this would be an issue for you. I really like your idea of a markdown template so I'm would like to cooperate with you if possible to find a solution for this. Do you have a github project where your template can be found?  Or can you provide some more information how you are creating this template?

**Comment by tflori** [comment]
My template is based on https://github.com/cvuorinen/phpdoc-markdown-public but it is really scary when you look into method.md.twig.

To show code how the signature of the method looks like gives a quick overview over the parameters. And because it is highlighted you can easily read and it is an eye catcher: https://github.com/tflori/orm/blob/feature-entityFetcher/docs/reference.md

But I don't know how to avoid to long lines in twig and this method gives the option. My template is here: https://github.com/tflori/orm/tree/feature-entityFetcher/docs/_reference - you can see in method.md.twig that is much clearer to get the signature with a maximum length of 80 characters...

**Comment by mvriel** [comment]
The above method is what I consider to be view logic (especially with the line break support in there); I recommend writing a Twig extension in a Plugin (see the Twig plugin in phpDocumentor how to do that) with which you can perform the code above.

In future versions of phpDocumentor we would like to be able to 'require' plugins when using a theme so that the user is informed that they need to add it; for now I would advice adding this to the documentation of the template in the `template.xml`

**Comment by tflori** [comment]
just to mention it: this is not simply splitting a line by x characters. when the length exceeds the limit it is broken down by php logic - I'm not sure that it makes sense to have a template plugin for it.

On the other hand it is a signature of  a method and `MethodDescriptor" seems to be responsible to describe a method. The signature is nothing you can change by a template - it is given by the programming language.
