### ISSUE TITLE
Input, Success and Error example

### ISSUE THREAD

**Issue by haridarshan** [phpDocumentor/phpDocumentor2#1810]
Like [ApiDocJs](http://apidocjs.com/), is it possible with phpDocumentor to add input example, output success and error example in phpdoc block something like shown in this link [ApiDocJs Example](http://apidocjs.com/example/). Currently am using apigen as it accepts PSR-5 phpdoc tags and not able to generate documentation like it is generated by the apidocjs and since phpdocumentor is psr-5 compatible so like to know how can i achieve such result

> /**
>  * ...
>  * @success int id
>  * @success string name
>  * ...
>  * @response json Success:
>  * HTTP/1.1 200 OK
>  * { 
>  *  "content" : "This is an example content" 
>  * }
>  * @response json Error:
>  * HTTP/1.1 404 Not Found
>  * { 
>  *  "error" : "UserNotFound" 
>  * }
>  */

**Comment by mvriel** [comment]
phpDocumentor supports the [`@example`] tag that can be used for such purposes

[`@example`]: https://phpdoc.org/docs/latest/references/phpdoc/tags/example.html
