### ISSUE TITLE
Templates page doesn't have template names

### ISSUE THREAD

**Issue by tbillington** [phpDocumentor/phpDocumentor2#1812]
Lots of the documentation pages link to https://phpdoc.org/templates when showing the possible templates, but the /templates page has no names on any of the templates which made it impossible to use. I had to go looking in the source code for the list of templates to use.

**Comment by mvriel** [comment]
phpDocumentor features a command `template:list` that shows all templates that could be use (see https://phpdoc.org/docs/latest/references/commands/template_list.html).

But I agree with you that it would make for a good improvement on the website. I am going to close this issue and re-open a new one on the phpdoc.org repository for this.
