### ISSUE TITLE
Concatenation in property declaration breaks phpdoc

### ISSUE THREAD

**Issue by felixkk** [phpDocumentor/phpDocumentor2#1827]
Hi,

I have some path variables declared like this :

`private static $schemaPath = REAL_PATH.'/xml/xsd.xsd';`

When a class contains this kind of declaration, phpdoc skip it and nothing is generated for this file.

Thanks for reading

Edit :  In verbose mode this error is showed : 
`Parse Error: Syntax error, unexpected '.', expecting ',' or ';' on line 21  No summary was found for this file` 

Is there a way to make phpdoc ignore this var and keep parsing the rest of the file ?

**Comment by mvriel** [comment]
@felixkk I haven't been able to reproduce the issue with the following test file:

``` php
<?php

class A {
  private static $schemaPath = REAL_PATH.'/xml/xsd.xsd';
}
```

I have ran this file using phpDocumentor 2.9.0 and didn't encounter the issue that you describe. Have you tried this with the latest version of phpDocumentor and if so: can you provide us with a complete example file?

**Comment by felixkk** [comment]
I checked and my phpdoc version is 2.8.5, so I guess i'll probably just need to update ?

**Comment by jaapio** [comment]
That's right please upgrade :-)
