### ISSUE TITLE
New 7.1 "iterable" pseudo-type is not recognized

### ISSUE THREAD

**Issue by AlexHowansky** [phpDocumentor/phpDocumentor2#1831]
Don't know that I'd call this a bug, as it's a very new feature -- but at the least I'll mention it for your TODO list.

The new `iterable` pseudo-type in v7.1 is not recognized as a valid type. Instead, it is interpreted as a class in the current namespace. It should work like `callable`. For example, consider this code:

```
class Foo
{

    /**
     * Process a thing.
     *
     * @param callable $thing The thing to process.
     *
     * @return null
     */
    public function process(callable $thing)
    {
    }

}
```

This generates the following doc:

> process(callable  $thing) : null

Changing the `callable` to `iterable` we get:

> process(\iterable  $thing) : null

**Comment by mvriel** [comment]
Hello @AlexHowansky,

Thanks for mentioning this to us. We, unfortunately, have a bit of a backlog with new features but I have added this to the backlog to fix. For the record, here is the PHP Documentation page referring to this new type: http://php.net/manual/en/language.types.iterable.php

**Comment by jaapio** [comment]
Added a test to show this is resolved in v3.
