### ISSUE TITLE
[Template] dokuwiki syntax

### ISSUE THREAD

**Issue by sulian** [phpDocumentor/phpDocumentor2#1832]
Can you create a new template for an export in dokuwiki langage ? (or explain how to create a simple writer for this)

Thanks you

**Comment by mvriel** [comment]
Hello @sulian,

At this moment we have several other priorities to deal with and I would not consider it fair to keep this issue open while I think we can't get to it in time. I like the idea and can see how it would be useful to people.

I can point you to the documentation page where we give an overview on how to write your own template and use twig, for example, to render the necessary items in the right locations: https://phpdoc.org/docs/latest/getting-started/changing-the-look-and-feel.html

**Comment by sulian** [comment]
Hello @mvriel, thanks for your response. I'm looking the documentation.
