### ISSUE TITLE
Annotation for side effects

### ISSUE THREAD

**Issue by marcosh** [phpDocumentor/phpDocumentor2#1837]
It would be nice if we were able to document the fact that a method is performing some side effect.

I think we could introduce a `@side-effect [<description>]` annotation which the developer can use to document which side effect is the method actually performing

**Comment by mvriel** [comment]
We try to limit the number of tags that are included in the PHPDoc specification; this is the first request for this tag and as such, I do not feel we should actively include it in the specification. If this is of use to your project I can recommend writing a plugin for it. 

This plugin is something you can manage in your own project and if the community finds it useful we can integrate it into phpDocumentor itself.

As an additional note, you could solve this by adding an `@todo` to mention that this side-effect should be resolved.

Thank you for your recommendation and if we receive more requests for this type of tag we will reconsider including it as part of phpDocumentor itself.

**Comment by marcosh** [comment]
Thanks Mike for your response!

**Comment by devope** [comment]
> this is the first request

Here is my vote for side effect tag
