### ISSUE TITLE
How to remove the tag <p></p> in structure.xml 

### ISSUE THREAD

**Issue by yunfeifan** [phpDocumentor/phpDocumentor2#1839]
Hi,

I found the param's description is covered with <p></p> likes this:
`tag name="param" line="46" description="&lt;p&gt;MyTest&lt;/p&gt;" type="client" variable="client">`

How to remove the tag <p> in structure.xml?
thanks.

**Comment by jaapio** [comment]
Why would you like to remove it?

**Comment by yunfeifan** [comment]
Because I want to convert to markdown with the structure.xml.

Have you any idea about this?

Thanks.

**Comment by jaapio** [comment]
You could have a look at https://github.com/evert/phpdoc-md. Never used it myself

**Comment by yunfeifan** [comment]
Thank you very much.

**Comment by Skayo** [comment]
phpdoc-md unfortunately doesn't remove these annoying html tags. Please add an option to disable it!
