### ISSUE TITLE
@global tag

### ISSUE THREAD

**Issue by alissonzampietro** [phpDocumentor/phpDocumentor2#1840]
Which tag can i use in the place of @global?
I read in the documentation, that isn't indicated the use this tag, so i would like to know by which one can i replace?

**Comment by esokullu** [comment]
I think what they mean is that using global is generally not recommended in PHP, and you are instead encouraged to use static class variables, or class constants.

**Comment by alissonzampietro** [comment]
Cool!!! Thank you too much, surged this doubt and I stayed: why not?? Thank you too much again.

**Comment by jaapio** [comment]
Global can lead to strange behaviour that you will not understand in the future. Like where is this value comming from? Who changed my variable. 

We are convinced that you should protect your application's state. which you cannot do when everyone has access. This might help: http://stackoverflow.com/questions/5166087/php-global-in-functions

**Comment by alissonzampietro** [comment]
Sure @jaapio , my wish is to use to represent a $_POST value in the method.

**Comment by jaapio** [comment]
Think global should work in that case

**Comment by alissonzampietro** [comment]
Thanks ever so much

**Comment by alissonzampietro** [comment]
Thank you too much
