### ISSUE TITLE
PHP 7 Anonymous classes not supported

### ISSUE THREAD

**Issue by esokullu** [phpDocumentor/phpDocumentor2#1841]
The title says it all. We don't need PHPDoc to support documentation for anonymous class (or functions) but currently phpdoc breaks when you have an anonymous class in your code.

Any plans to release a new version for the latest changes in PHP 7+ that are not supported in current PHPDoc?

1. anonymous classes
2. nullable types
3. Group use declarations

are some of the basic ones that come to my mind.

**Comment by jaapio** [comment]
We are working on a new version of phpdocumentor. But due limited time and resources we are off schedule. But there are plans to support php7's new features.
