### ISSUE TITLE
Clean Template - Missing data for field `FILE`

### ISSUE THREAD

**Issue by neooblaster** [phpDocumentor/phpDocumentor2#1846]
Hi phpDoc team,

As discussed in issue #1844 , i encountered an issue regarding field `FILE ` in template Clean.

Mvriel told me to open issue because that seem to be a bug.

Please find hereafter a screenshot and the corresponding DocBlock : 

![image](https://cloud.githubusercontent.com/assets/22078558/26241981/0988ac4c-3c87-11e7-853f-ae17452a7c2f.png)

```php
<?php
/**
 * Fichier :: test.php
 *
 * @package Portail\tasks-planned
 * @author Nicolas DUPRE
 * @version 1.0.0
 */

/**
 * Version : 1.0.0 - Release : xx.xx.2017 - Author : Nicolas DUPRE
 *
 * ### Version 1.0.0 :: xx.xx.2017
 *
 * • A
 *
 * • B
 * 
 * 
 * ### Description Fonctionnelle
 *
 * 
 * ### Détail de la fonction
 *
 * @todo Faire ca
 * 
 * @param void 
 * 
 * @return void
 */
function new_func_file() {
	
}
```

Thanks a lot for your support.

Best Regards
Nicolas DUPRE.

**Comment by mvriel** [comment]
Thanks for helping us by opening this issue; I have marked it as a bug in the templates that needs to be resolved

**Comment by neooblaster** [comment]
It's with pleasure to contribute in all ways as possible :D

**Comment by mvriel** [comment]
Thanks to your detailed report we have been able to find the issue and resolve it in commit c5672cff803d18dd0c2a74e7f796fdbee446cbee. This fix is now on master and will be available in the next release.

**Comment by neooblaster** [comment]
Thanks alot for this really fast resolution.

I stay informed about release and if i find another issues, i will report them.
