### ISSUE TITLE
why does --template="clean" put source-files in the docfolder

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor2#1853]
frankly - there is an option if you want sources included and this is in doubt a SECURITY RELATED behavior having some .txt files with the complete source in a documentation folder

hacks like this SHOULD not be needed to prevent leaks

find "$CMS_UPDATE_SERVICE_LOCATION/documentation/code-referenzen/phpincludes/files" -type f -name \*.txt -delete

**Comment by jaapio** [comment]
We see it as a feature, but we are aware of the fact that it could be an issue. Therefor we included an option to add it optionally. But I think you are asking us to not process the files at all? when you do not provide the --source option?

**Comment by thelounge-zz** [comment]
because the source option don't accept a param and so it is intended in the current implementation *to enable* the current wrong default behavior?

**Comment by thelounge-zz** [comment]
or do *you* see the --source-option below?

php -d "extension=tokenizer.so" "$CMS_UPDATE_SERVICE_LOCATION/phpDocumentor.phar" run --force --progressbar --cache-folder="/tmp" --encoding="ISO-8859-1" --directory="$CMS_UPDATE_SERVICE_LOCATION/package" --filename="/www/phpincludes/newsletter.php" --ignore="modules/blog/tagcloud.php" --target="$CMS_UPDATE_SERVICE_LOCATION/documentation/code-referenzen/contentlounge" --title="ContentLounge - Technische Referenz" --defaultpackagename="ContentLounge" --template="clean"

**Comment by jaapio** [comment]
I'm not telling you that you are doing it wrong. I was trying to figure out what you meant to say with your issue. 

So again, you don't want us to create those files when you do not provide the source option :-)

**Comment by thelounge-zz** [comment]
DAMNED: --sourcecode          Whether to include syntax highlighted source code

--sourcecode=0

  [RuntimeException]
  The "--sourcecode" option does not accept a value

so when it does not accept a value it#s intention is TO ENABLE the "feature" but when it is enbaled by default and there is no disable-switch what's the option about and why is the DEFAULT that danerous and wrong? did you get it now?

**Comment by thelounge-zz** [comment]
wow - you don't consider by default leaking the whole sources in a documentation which is probably reachable online even in case of closed source as not a bug when there exists a --sourcecode option ehich is not enabled?

**Comment by mvriel** [comment]
Sorry for the confusion, we actually had a regression where the `--sourcecode` option was enabled by default. This has been resolved on the master branch and is part of the upcoming 2.9.1 release. Please see issue https://github.com/phpDocumentor/phpDocumentor2/issues/1780 for more information.

In other words, this issue has been resolved but has not been included in a tagged release yet.
