### ISSUE TITLE
Fatal error: Failed opening required "dompdf_config.inc.php" in Bootstrap.php on line 178

### ISSUE THREAD

**Issue by oscarmunoz20** [phpDocumentor/phpDocumentor2#1859]
Hi
I've installed phpDocumnetor2 using pearl I a got a success message "install ok: channel://pear.phpdoc.org/phpDocumentor-2.9.0" but when I put in the console phpdoc I got the following error:

PHP Warning:  require_once(C:\xampp\htdocs\siselc-thomas\vendor/dompdf/dompdf/dompdf_config.inc.php): failed to open stream: No such file or directory in C:\xampp\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 178

Warning: require_once(C:\xampp\htdocs\siselc-thomas\vendor/dompdf/dompdf/dompdf_config.inc.php): failed to open stream: No such file or directory in C:\xampp\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 178
PHP Fatal error:  require_once(): Failed opening required 'C:\xampp\htdocs\siselc-thomas\vendor/dompdf/dompdf/dompdf_config.inc.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 178

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\siselc-thomas\vendor/dompdf/dompdf/dompdf_config.inc.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\php\pear\phpDocumentor\src\phpDocumentor\Bootstrap.php on line 178

I am not an expert in this son I tried to install DOMPDF, but I am still getting the same error.

Thanks a lot

**Comment by jaapio** [comment]
@mvriel is this some historic dependency? I cannot find dompdf in the composer.json anymore.

**Comment by oscarmunoz20** [comment]
Hi, well, I am using the last version of Laravel (5.4) And the composer that comes whit it, didn't have dompdf, I just added just to check if that would solve the problem but it didn't. (Hope that was what you are asking, I am just a beginner)

Thanks a lot

**Comment by jaapio** [comment]
@oscarmunoz20 you could try to download the phar file from our website and run phpdoc that way. I think this is an issue in our pear package.

**Comment by mvriel** [comment]
@jaapio Yes, DOMPDF used to be used to generate PDFs with but caused too many conflicts and we never fully implemented PDF rendering. As such it was removed but this line in the bootstrap was too IIRC

**Comment by oscarmunoz20** [comment]
Thanks a lot, right now I am not able to try that out, but once I can, I will let you know if ti works.

**Comment by oscarmunoz20** [comment]
Hi, the phar file works great, thanks a Lot.

**Comment by nazmulsarkar** [comment]
How did it work, i mean where id you place the phar file? in the project root or else please.

**Comment by nazmulsarkar** [comment]
@oscarmunoz20 where did you place the phar file please? in the project root or else.
I am very new to use that...

**Comment by jaapio** [comment]
A phar file is basically an binary, it doesn't matter where you install it. Just like you install composer for example. Can be anywhere on your system.

**Comment by nazmulsarkar** [comment]
Thanks @jaapio , i already been sucessful, before i read your message by keeping the phar in th eproject root, its nicely working. Thanks for your message.

**Comment by cardonr** [comment]
This item was badly closed, because the version 2.9.0 on PEAR is corrupted. A new issue was open: https://github.com/phpDocumentor/phpDocumentor2/issues/1859

**Comment by TheOpenDevProject** [comment]
Still an issue with the latest package on pear

**Comment by elliottpost** [comment]
Also an issue with composer install

**Comment by dingo-d** [comment]
Can confirm too, I get the same error when I installed the phpDocumentor using

```sh
pear channel-discover pear.phpdoc.org
pear install phpdoc/phpDocumentor
```

What's the workaround for this? Removing the `addDomPdfConfig` method?

**Comment by elliottpost** [comment]
@dingo-d if you download the .phar from their site and run it that way (instead of with composer) it works (for me, anyway).

**Comment by dingo-d** [comment]
Yup, I ended up doing it that way and it works. I've had to modify things a bit for it to work on mac, but it's all ok now.

**Comment by cardonr** [comment]
Workaround to install with PEAR but using the archive on GitHub:

download https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor-2.9.0.tgz
launch PEAR from the command line with the downloaded package:
pear install phpDocumentor-2.9.0.tgz
(Thanks to the comment of miken32 on this issue: #1764). See #1887.

**Comment by mohamadreza89** [comment]
I still have this issue though I have installed the package via PEAR. Installing the dompdf package doesn't make a difference because the `dompdf_config.inc.php` doesn't exist
