### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by jbnv** [phpDocumentor/phpDocumentor2#1864]
Running phpDocumentor for the first time. I downloaded the PHAR file and set an alias to point to the PHAR file. When I run it, I'm getting the following output to the command line:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://www.phpdoc.org/phpDocumentor.phar">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at www.phpdoc.org Port 80</address>
</body></html>
```

This happening with no parameters and with `.d . -t .docs`.  What is the problem and how do I fix it? Apologies if this has already been answered; a search of both these issues and the Internet in general turned up no hits.

**phpdoc.dist.xml**

```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdoc>
  <parser>
    <target>.temp</target>
  </parser>
  <transformer>
    <target>.docs</target>
  </transformer>
  <files>
    <directory>./Support/</directory>
    <directory>./Traits/</directory>
    <directory>./Exceptions/</directory>
    <directory>./Testing/</directory>
    <directory>./Tests/</directory>
    <ignore>./vendor/</ignore>
  </files>
</phpdoc>
```

**Comment by jaapio** [comment]
I don't know how you downloaded the phar but it looks like you downloaded a html file. Please try reinstalling the phar.
