### ISSUE TITLE
Getting "Load cache .. Segmentation fault" every time I run phpdoc

### ISSUE THREAD

**Issue by greenie2600** [phpDocumentor/phpDocumentor2#1865]
I've just installed phpDocumentor 2.9.0 via PEAR. I'm running PHP 7.0.18-0ubuntu0.16.04.1. I have the latest version of php7.0-xsl installed.

I've tried running basic tasks against several different directories containing .php files. It always segfaults when it gets to "Load cache". For example:

    $ phpdoc -d /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper -t ~/lib24watch_phpdoc
    Collecting files .. OK
    Initializing parser .. OK
    Parsing files
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchUserHelper.php
      No summary was found for this file
      No summary for class ""
      Argument $data is missing from the Docblock of toHumanReadable
      Argument $key is missing from the Docblock of toHumanReadable
      No summary for method ""
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchPermissionsHelper.php
      No summary was found for this file
      No summary for class ""
      No summary for method ""
      Argument $lib24watchUser is missing from the Docblock of normalizeLib24watchUser
      No summary for method ""
      Argument $lib24watchUser is missing from the Docblock of isLoggedIn
      No summary for method ""
      Argument $lib24watchUser is missing from the Docblock of isImmutableSuperuser
      No summary for method ""
      Argument $lib24watchUser is missing from the Docblock of isSuperuser
      No summary for method ""
      Argument $plugin is missing from the Docblock of isPluginVisible
      Argument $lib24watchUser is missing from the Docblock of isPluginVisible
      No summary for method ""
      Argument $permissionKey is missing from the Docblock of hasPermission
      Argument $plugin is missing from the Docblock of hasPermission
      Argument $lib24watchUser is missing from the Docblock of hasPermission
      No summary for method ""
      No summary for property $currentLib24watchUser
      No summary for property $lib24watchModules
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchAutolinkerHelper.php
      No summary was found for this file
      No summary for class ""
      Argument $text is missing from the Docblock of autolink
      Argument $linkMap is missing from the Docblock of autolink
      Argument $linkerCallback is missing from the Docblock of autolink
      Argument $linkerCallbackExtraArgs is missing from the Docblock of autolink
      No summary for method ""
      Argument $first is missing from the Docblock of sortRanges
      Argument $second is missing from the Docblock of sortRanges
      No summary for method ""
      Argument $thisStart is missing from the Docblock of isOverlap
      Argument $thisEnd is missing from the Docblock of isOverlap
      Argument $otherStart is missing from the Docblock of isOverlap
      Argument $otherEnd is missing from the Docblock of isOverlap
      No summary for method ""
      Argument $value is missing from the Docblock of isBetween
      Argument $start is missing from the Docblock of isBetween
      Argument $end is missing from the Docblock of isBetween
      No summary for method ""
      Argument $first is missing from the Docblock of sortLinkMapCallback
      Argument $second is missing from the Docblock of sortLinkMapCallback
      No summary for method ""
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/LessHelper.php
      No summary for class ""
      Argument $View is missing from the Docblock of __construct
      Argument $config is missing from the Docblock of __construct
      Argument $options is missing from the Docblock of fetch
      Argument $less is missing from the Docblock of less
      Argument $less is missing from the Docblock of jsBlock
      Argument $input is missing from the Docblock of compile
      Argument $input is missing from the Docblock of string
      Argument $options is missing from the Docblock of setOptions
      Argument $plugin is missing from the Docblock of assetBaseUrl
      Argument $url is missing from the Docblock of pluginAssetFile
      Argument $url is missing from the Docblock of assetSplit
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/PanelHelper.php
      No summary was found for this file
      No summary for class ""
      Argument $options is missing from the Docblock of start
      No summary for method ""
      Argument $options is missing from the Docblock of applyTemplate
      Argument $options is missing from the Docblock of applyTemplateBrowse
      No summary for method ""
      Argument $options is missing from the Docblock of applyTemplateEdit
      No summary for method ""
      Argument $options is missing from the Docblock of applyTemplateFilter
      No summary for method ""
      No summary for method ""
      No summary for method ""
      Argument $remember_collapse is missing from the Docblock of rememberCollapseUnique
      No summary for method ""
      Argument $camel_string is missing from the Docblock of humanizeString
      Argument $plural is missing from the Docblock of humanizeString
      No summary for property $helpers
      No summary for property $index
      No summary for property $view_vars
      No summary for property $humanized_strings
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchImageCacheHelper.php
      No summary was found for this file
      No summary for class ""
      Argument $pluginName is missing from the Docblock of url
      Argument $basePath is missing from the Docblock of url
      No summary for property $helpers
    Storing cache in "/home/tmiller/lib24watch_phpdoc" .. OK
    Load cache                                                         .. Segmentation fault

A few other times, I've seen it stall when it gets to "Load cache" (without segfaulting), with 100% CPU usage and very little memory usage.

**Comment by jaapio** [comment]
Do you have the same issues when using our [phar](http://phpdoc.org/phpDocumentor.phar) install?

**Comment by greenie2600** [comment]
Unfortunately, yes, I do:

    $ php phpDocumentor.phar -d /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper -t ~/lib24watch_phpdoc
    Collecting files .. OK
    Initializing parser .. OK
    Parsing files
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchUserHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchUserHelper
      Argument $data is missing from the Docblock of toHumanReadable
      Argument $key is missing from the Docblock of toHumanReadable
      No summary for method toHumanReadable()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchPermissionsHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchPermissionsHelper
      No summary for method beforeRender()
      Argument $lib24watchUser is missing from the Docblock of normalizeLib24watchUser
      No summary for method normalizeLib24watchUser()
      Argument $lib24watchUser is missing from the Docblock of isLoggedIn
      No summary for method isLoggedIn()
      Argument $lib24watchUser is missing from the Docblock of isImmutableSuperuser
      No summary for method isImmutableSuperuser()
      Argument $lib24watchUser is missing from the Docblock of isSuperuser
      No summary for method isSuperuser()
      Argument $plugin is missing from the Docblock of isPluginVisible
      Argument $lib24watchUser is missing from the Docblock of isPluginVisible
      No summary for method isPluginVisible()
      Argument $permissionKey is missing from the Docblock of hasPermission
      Argument $plugin is missing from the Docblock of hasPermission
      Argument $lib24watchUser is missing from the Docblock of hasPermission
      No summary for method hasPermission()
      No summary for property $currentLib24watchUser
      No summary for property $lib24watchModules
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchAutolinkerHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchAutolinkerHelper
      Argument $text is missing from the Docblock of autolink
      Argument $linkMap is missing from the Docblock of autolink
      Argument $linkerCallback is missing from the Docblock of autolink
      Argument $linkerCallbackExtraArgs is missing from the Docblock of autolink
      No summary for method autolink()
      Argument $first is missing from the Docblock of sortRanges
      Argument $second is missing from the Docblock of sortRanges
      No summary for method sortRanges()
      Argument $thisStart is missing from the Docblock of isOverlap
      Argument $thisEnd is missing from the Docblock of isOverlap
      Argument $otherStart is missing from the Docblock of isOverlap
      Argument $otherEnd is missing from the Docblock of isOverlap
      No summary for method isOverlap()
      Argument $value is missing from the Docblock of isBetween
      Argument $start is missing from the Docblock of isBetween
      Argument $end is missing from the Docblock of isBetween
      No summary for method isBetween()
      Argument $first is missing from the Docblock of sortLinkMapCallback
      Argument $second is missing from the Docblock of sortLinkMapCallback
      No summary for method sortLinkMapCallback()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/LessHelper.php
      No summary for class \Lib24watch\View\Helper\LessHelper
      Argument $View is missing from the Docblock of __construct
      Argument $config is missing from the Docblock of __construct
      Name of argument $plugin does not match with the DocBlock's name $asset in assetBaseUrl()
      Name of argument $asset does not match with the DocBlock's name $plugin in assetBaseUrl()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/PanelHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\PanelHelper
      No summary for method start()
      No summary for method end()
      Argument $options is missing from the Docblock of applyTemplate
      Argument $options is missing from the Docblock of applyTemplateBrowse
      No summary for method applyTemplateBrowse()
      Argument $options is missing from the Docblock of applyTemplateEdit
      No summary for method applyTemplateEdit()
      Argument $options is missing from the Docblock of applyTemplateFilter
      No summary for method applyTemplateFilter()
      No summary for method generatePanelId()
      No summary for method getCurrentRoute()
      Argument $remember_collapse is missing from the Docblock of rememberCollapseUnique
      No summary for method rememberCollapseUnique()
      Argument $camel_string is missing from the Docblock of humanizeString
      Argument $plural is missing from the Docblock of humanizeString
      No summary for property $helpers
      No summary for property $index
      No summary for property $view_vars
      No summary for property $humanized_strings
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchImageCacheHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchImageCacheHelper
      Name of argument $fileSize does not match with the DocBlock's name $width in url()
      Name of argument $width does not match with the DocBlock's name $height in url()
      Name of argument $height does not match with the DocBlock's name $force in url()
      Name of argument $force does not match with the DocBlock's name $full in url()
      Name of argument $full does not match with the DocBlock's name $basePath in url()
      Argument $basePath is missing from the Docblock of url
      No summary for property $helpers
    Storing cache in "/home/tmiller/lib24watch_phpdoc" .. OK
    Load cache                                                         .. Segmentation fault

**Comment by greenie2600** [comment]
And, likewise for the composer install:

    $ php vendor/bin/phpdoc -d /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper -t ~/lib24watch_phodic
    Collecting files .. OK
    Initializing parser .. OK
    Parsing files
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchUserHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchUserHelper
      Argument $data is missing from the Docblock of toHumanReadable
      Argument $key is missing from the Docblock of toHumanReadable
      No summary for method toHumanReadable()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchPermissionsHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchPermissionsHelper
      No summary for method beforeRender()
      Argument $lib24watchUser is missing from the Docblock of normalizeLib24watchUser
      No summary for method normalizeLib24watchUser()
      Argument $lib24watchUser is missing from the Docblock of isLoggedIn
      No summary for method isLoggedIn()
      Argument $lib24watchUser is missing from the Docblock of isImmutableSuperuser
      No summary for method isImmutableSuperuser()
      Argument $lib24watchUser is missing from the Docblock of isSuperuser
      No summary for method isSuperuser()
      Argument $plugin is missing from the Docblock of isPluginVisible
      Argument $lib24watchUser is missing from the Docblock of isPluginVisible
      No summary for method isPluginVisible()
      Argument $permissionKey is missing from the Docblock of hasPermission
      Argument $plugin is missing from the Docblock of hasPermission
      Argument $lib24watchUser is missing from the Docblock of hasPermission
      No summary for method hasPermission()
      No summary for property $currentLib24watchUser
      No summary for property $lib24watchModules
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchAutolinkerHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchAutolinkerHelper
      Argument $text is missing from the Docblock of autolink
      Argument $linkMap is missing from the Docblock of autolink
      Argument $linkerCallback is missing from the Docblock of autolink
      Argument $linkerCallbackExtraArgs is missing from the Docblock of autolink
      No summary for method autolink()
      Argument $first is missing from the Docblock of sortRanges
      Argument $second is missing from the Docblock of sortRanges
      No summary for method sortRanges()
      Argument $thisStart is missing from the Docblock of isOverlap
      Argument $thisEnd is missing from the Docblock of isOverlap
      Argument $otherStart is missing from the Docblock of isOverlap
      Argument $otherEnd is missing from the Docblock of isOverlap
      No summary for method isOverlap()
      Argument $value is missing from the Docblock of isBetween
      Argument $start is missing from the Docblock of isBetween
      Argument $end is missing from the Docblock of isBetween
      No summary for method isBetween()
      Argument $first is missing from the Docblock of sortLinkMapCallback
      Argument $second is missing from the Docblock of sortLinkMapCallback
      No summary for method sortLinkMapCallback()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/LessHelper.php
      No summary for class \Lib24watch\View\Helper\LessHelper
      Argument $View is missing from the Docblock of __construct
      Argument $config is missing from the Docblock of __construct
      Name of argument $plugin does not match with the DocBlock's name $asset in assetBaseUrl()
      Name of argument $asset does not match with the DocBlock's name $plugin in assetBaseUrl()
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/PanelHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\PanelHelper
      No summary for method start()
      No summary for method end()
      Argument $options is missing from the Docblock of applyTemplate
      Argument $options is missing from the Docblock of applyTemplateBrowse
      No summary for method applyTemplateBrowse()
      Argument $options is missing from the Docblock of applyTemplateEdit
      No summary for method applyTemplateEdit()
      Argument $options is missing from the Docblock of applyTemplateFilter
      No summary for method applyTemplateFilter()
      No summary for method generatePanelId()
      No summary for method getCurrentRoute()
      Argument $remember_collapse is missing from the Docblock of rememberCollapseUnique
      No summary for method rememberCollapseUnique()
      Argument $camel_string is missing from the Docblock of humanizeString
      Argument $plural is missing from the Docblock of humanizeString
      No summary for property $helpers
      No summary for property $index
      No summary for property $view_vars
      No summary for property $humanized_strings
    Parsing /var/www/sandboxes/tmiller/24watch6/httpdocs/vendor/redacted/lib24watch/src/View/Helper/Lib24watchImageCacheHelper.php
      No summary was found for this file
      No summary for class \Lib24watch\View\Helper\Lib24watchImageCacheHelper
      Name of argument $fileSize does not match with the DocBlock's name $width in url()
      Name of argument $width does not match with the DocBlock's name $height in url()
      Name of argument $height does not match with the DocBlock's name $force in url()
      Name of argument $force does not match with the DocBlock's name $full in url()
      Name of argument $full does not match with the DocBlock's name $basePath in url()
      Argument $basePath is missing from the Docblock of url
      No summary for property $helpers
    Storing cache in "/home/tmiller/lib24watch_phodic" .. OK
    Load cache                                                         .. Segmentation fault

**Comment by nnrudakov** [comment]
Parsing errors does not matter. The same error.

Clear test file:
`<?php

/**
 * File...
 */

/**
 * File...
 *
 * @package    pack
 * @author     authod
 * @copyright  2016-2017
 */
class A
{
    /**
     * Var
     *
     * @var string
     */
    private $var;

    /**
     * A constructor.
     */
    public function __construct()
    {
        $this->var = 'test';
    }

    /**
     * Return var.
     *
     * @return string
     */
    public function getVar()
    {
        return $this->var;
    }
}
`

Command:
`vendor/bin/phpdoc run -f test.php -t docs --template=clean`

Result:
> Collecting files .. OK
Initializing parser .. OK
Parsing files
Parsing /test.php
Storing cache in "/docs" .. OK
Load cache                                                         .. Segmentation fault

**Comment by jaapio** [comment]
Could you please give this a retry with our new v3.0.0-alpha release. Think this solves your issue.

**Comment by nnrudakov** [comment]
There is no such error in this version.

**Comment by jaapio** [comment]
Thanks, will close this issue
