### ISSUE TITLE
title of pfirst window   on first page

### ISSUE THREAD

**Issue by wawrzyniakinfo** [phpDocumentor/phpDocumentor2#1866]
start message manual  content .
[phpDocumentor2-2.9.0.tar.gz](https://github.com/phpDocumentor/phpDocumentor2/files/1132911/phpDocumentor2-2.9.0.tar.gz)

**Comment by jaapio** [comment]
Can you provide some more information about the issue you found? I don't understand what you found.

**Comment by jaapio** [comment]
closing the leak of feedback
