### ISSUE TITLE
Compilation Errors Incomplete

### ISSUE THREAD

**Issue by blackdrago** [phpDocumentor/phpDocumentor2#1877]
It seems as if phpdoc automatically generates the  "No summary was found for this file" error for PHP files that have syntax errors.

If there is an error in the PHP file,  I see "No summary was found for this file" in the list of compilation errors. This is the only error displayed, and it's very confusing because the file absolutely does have a summary file. It's even more confusing when the PHP file executes as expected (e.g. when the true syntax error appears in a place of rarely-reached code). 

Here is a screenshot of the Compilation Error for the file:
<img width="734" alt="phpdoc-issue1-documentation" src="https://user-images.githubusercontent.com/924076/29425656-0cc93950-8352-11e7-973b-26e5af1f84b2.png">

Here is a screenshot of the top of my file, so you can see there is, in fact, a file summary:
<img width="562" alt="phpdoc-issue1-file" src="https://user-images.githubusercontent.com/924076/29425688-2b0dc12e-8352-11e7-98ac-15e9b9268610.png">

I only made the connection between a parsing error and this incorrect error message because I noticed something when I ran the phpdoc command (trying to get the invalid error to go away):
<img width="880" alt="phpdoc-issue1-screenshot" src="https://user-images.githubusercontent.com/924076/29425786-7f3cd00a-8352-11e7-800b-c4f0a25ff558.png">

To be clear, the error is this:
```
Parse Error: Syntax error, unexpected '[', expecting ',' or ')' on line 1064
```
Yet the compilation error stored is "No summary was found for this file."

This is output from the command-line, and as my project is very large, this reporting is often lost on me completely. The only reason I was about to see this file was that it came later in the project filenames, leaving it visible on my console screen. While it is visible (many other files are not -- my console only keeps so much output), it's not easy to spot.

Is there a reason that the Compilation Errors page doesn't include the actual Parse Error that phpdoc reported? I wouldn't mind if the "No summary was found for this file" error was there so long as the actual parsing error was also there to direct me to the real issue.

(In case you're wondering, the actual culprit for this issue was a ternary statement that had a missing $ on a variable. The line number for the error was dead on.)

**Comment by jaapio** [comment]
This is resolved in v3.0.0-alpha1. Console output will report syntax errors now.
