### ISSUE TITLE
undue parser errors for const arrays (PHP7)

### ISSUE THREAD

**Issue by restena-sw** [phpDocumentor/phpDocumentor2#1883]
When trying to generate phpdoc for my software package, I see errors like:

Collecting files .. OK
Initializing parser .. OK
Parsing files
Parsing /home/swinter/Development/GitHub/GEANT/CAT/core/Federation.php
Parse Error: Syntax error, unexpected '[' on line 163  No summary was found for this file
Parsing /home/swinter/Development/GitHub/GEANT/CAT/core/UserAPI.php
Parse Error: Syntax error, unexpected '[' on line 152  No summary was found for this file
Parsing /home/swinter/Development/GitHub/GEANT/CAT/core/ProfileSilverbullet.php
Parse Error: Syntax error, unexpected '[', expecting T_PAAMAYIM_NEKUDOTAYIM on line 86  No summary was found for this file
Parsing /home/swinter/Development/GitHub/GEANT/CAT/core/UserManagement.php
Parse Error: Syntax error, unexpected '[', expecting ',' or ')' on line 169  No summary was found for this file

All of these occurences are perfectly valid PHP7 code. Example from first occurence above:

$text = "<p>Could not create a new ".CONFIG_CONFASSISTANT['CONSORTIUM']['nomenclature_inst']."!</p>";

and this constant is defined elsewhere as:

(global scope)
const CONFIG_CONFASSISTANT = [
...
]

Apparently, the phpdoc parser does not recognise the new PHP7-style const ... array construct?

I use this all across my software package to hold the main product config, so basically, every  single source file that references the config can't be properly phpdoc'ed now :-(

If you care enough, the actual source is on github.com/GEANT/CAT/

**Comment by restena-sw** [comment]
Never mind... the dev box runs PHP7, but the machine I ran phpdoc on has 5.5 :-( Sorry for the noise!

**Comment by restena-sw** [comment]
Sorry, reopening: I thought this was working because I didn't get a parse error on a subsequent run with phpDocumentor 2.9.0 and php7 as the single interpreter on the system. It looked fine only because the previous cache was still there. When I rm -r the output directory and start fresh, I get the same wrong result as before, see original post.

I use the single-file phar version from the project homepage. It identifies itself as phpDocumentor 2.9.0 and my PHP version is now 7.0.7.

Could someone confirm that array constants ARE indeed supported?

**Comment by jaapio** [comment]
No we do not support this currently. We are working on a new version which will support this. But there is a huge amount of work to be done.

**Comment by jaapio** [comment]
When pr is merged this feature is covered by a behat test. Our current development version works with this syntax. Therefor I'm closing this issue. We will support this from v3.
