### ISSUE TITLE
phpDocumentor not working with vendor and display all Files

### ISSUE THREAD

**Issue by mogalejazkhan** [phpDocumentor/phpDocumentor2#1884]
php documentor not working with vendor in linux and show all file in doc with html and js all. how to display only api controller also take too long time to load in net beans

**Comment by mogalejazkhan** [comment]
PHP Warning:  include(phar:///home/computername/Desktop/phpDocumentor.phar/vendor/zendframework/zend-stdlib/src/Exception/ExtensionNotLoadedException.php): failed to open stream: phar error: Cannot open phar archive "/home/computername/Desktop/phpDocumentor.phar" for reading in phar:///home/computername/Desktop/phpDocumentor.phar/vendor/composer/ClassLoader.php on line 412

**Comment by jaapio** [comment]
I don't understand what issue you have. How did you install phpdocumentor? And what are you trying to do?

**Comment by jaapio** [comment]
Closing due a leak of feedback from TS. 
Feel free to reopen the issue when needed.
