### ISSUE TITLE
Grouping namespaces in 'use' breaks phpdoc

### ISSUE THREAD

**Issue by raz-atoth** [phpDocumentor/phpDocumentor2#1889]
Trying to parse a file containing a 'use' statement with grouped namespaces will will generate an error:

> Parse Error: Syntax error, unexpected '{', expecting T_STRING on line 8  No summary was found for this file

Replacing in the below example

`use \foo\bar\{ClassA, ClassB};`

with 

```
use \foo\bar\ClassA;
use \foo\bar\ClassB;
```
will work just fine.

Example:
```
<?php
/**
* Testing testing
*/

namespace foo;

use \foo\bar\{ClassA, ClassB};

/**
* Testing testing
*/
class A
{

	public function test()
	{
		echo 'testing';
	}

}
```

**Comment by jaapio** [comment]
dupplicates #1828, closing
