### ISSUE TITLE
Parse Error: Syntax error, unexpected '?'

### ISSUE THREAD

**Issue by SandroMiguel** [phpDocumentor/phpDocumentor2#1900]
The code bellow produces the following error when generating documentation:

> Parse Error: Syntax error, unexpected '?' on line 2328  No summary was found for this file

```
public function retrieveData(int $idRecipe): ?\stdClass {
    ...
}
```
phpDocumentor 2.8.5

**Comment by jaapio** [comment]
dupplicates #1833
