### ISSUE TITLE
Bug in phpDocumentor2 @method parser

### ISSUE THREAD

**Issue by SteveJobzniak** [phpDocumentor/phpDocumentor2#1906]
- `7.11 @method`: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#711-method says that methods should be documented with `@method [return type] [name]([type] [parameter], [...]) [description]`
- `Appendix A. Types`: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#appendix-a-types says that `@return int[]` (type followed by `[]`) is proper array notation.

Well, try documenting this class in phpDocumentor2:

![input](https://user-images.githubusercontent.com/22373193/31856568-b7c63a88-b6c4-11e7-9499-1f6ccf46588c.png)

This is the result. It totally dies:

![output](https://user-images.githubusercontent.com/22373193/31856569-c019918a-b6c4-11e7-9822-747a9ea976f3.png)

As you can see, phpDocumentor2 dies whenever the `@method` type is `Class[]` as opposed to `Class`. It then fails to parse the line and outputs a blank method name instead...

It also fails for lines with `@method $this setSomething()` and outputs those as blank too. Even though PSR-5 (at the bottom of its type-appendix) says that `$this` is a valid type.

As far as I can see from PSR-5, my `@method` syntax is correct in all of our files...

We use relative class-paths for the types (as opposed to FQDN), and trailing `[]` syntax for arrays of objects. You can see our files here, if you need tests that use `@method` to the max: https://github.com/mgp25/Instagram-API/tree/master/src/Response

**Comment by SteveJobzniak** [comment]
I just checked our regular `@return VideoUploadUrl[]` classes.

Those are properly documented:

![works](https://user-images.githubusercontent.com/22373193/31856613-dbaa9092-b6c5-11e7-961e-a201d9aaa911.png)

That means the `Class[]` syntax _is_ a valid return type, and that the phpDocumentor2 bugs are only in the `@method` parser. I guess it doesn't get much love and attention since not many people use it. ;-)

**Comment by jaapio** [comment]
Thanks for this complete report. Only thing I'm missing is which version of phpdocumentor you are using. 

We are currently working very hard to get phpdocumentor v3 out. We would be very pleased if you are able to test our current development version to check if this issue still exists. If so we will have a look.

**Comment by SteveJobzniak** [comment]
@jaapio Hi. Sorry, I forgot the version:

```
phpdoc --version
phpDocumentor version v2.9.0
```

And it's great to hear that v3 is on the way. I know what it's like to work on a big project (similar level of stars and activity as this one) and know what it feels like to be close to a new major release. I hope it goes well and relieves pressure. :-)

Unfortunately I can't test the dev version. I installed phpdocumentor with Homebrew which has no "from-source" version for that formula: https://github.com/Homebrew/homebrew-php/blob/master/Formula/phpdocumentor.rb

**Comment by SteveJobzniak** [comment]
However, if any of you clone this repo, you can check if it's fixed in v3:

https://github.com/mgp25/Instagram-API.git

**Comment by jaapio** [comment]
#1926 shows that this works with v3.0.0-alpha1.
