### ISSUE TITLE
please update phpDocumentor.phar to support php 7.1

### ISSUE THREAD

**Issue by thelounge-zz** [phpDocumentor/phpDocumentor2#1907]
i see git commits even for PHP 7.2 while the phar still don't support PHP 7.1 properly

function myfunc(): ?array aka nullable return-types

27/27 [============================] 100%Parse Error: Syntax error, unexpected '?' on line 705

**Comment by jaapio** [comment]
There is a difference between development and release ready. Our current development status is not ready for a release yet.

So you will have to clone the repo and use the bleeding edge develop version and learn to live with the bugs in there or wait until we have a fully functional and tested version.

**Comment by RinkAttendant6** [comment]
Is there an estimate or roadmap for the next release?

**Comment by jaapio** [comment]
I can't give you a date, but we are making progress. I would appreciate it very much if you could try our develop branch.

**Comment by thelounge-zz** [comment]
well, give me a phar file and i can, no chance that i install composer and friends on our PHP stack

**Comment by thelounge-zz** [comment]
https://github.com/phpDocumentor/phpDocumentor2/releases

can someone provide a alpha2/beta whatever which is newer than 2017-12 as phar?

**Comment by jaapio** [comment]
Please find the new phar at the release page.
