### ISSUE TITLE
Executable terminates at Resolve @link and @see tags in descriptions 

### ISSUE THREAD

**Issue by kalymnred** [phpDocumentor/phpDocumentor2#1909]
Im using the phar version 2.9.0 in a laravel 5.4 project (ubuntu 16.04 with php 7.1.10) and i cant pass this stage..
This is the output:
Storing cache in "/var/www/html/doc_cache" .. OK
Load cache                                                         ..   64.264s
Preparing template "clean"                                  ..    0.003s
Preparing 17 transformations                              ..    0.000s
Build "elements" index                                         ..    3.084s
Replace textual FQCNs with object aliases          ..    2.451s
Resolve @link and @see tags in descriptions      .. Killed

The procedure simply terminates without any output..

**Comment by jaapio** [comment]
Please try our fresh release https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v3.0.0-alpha1 and let me now if you still have the same issue. Feel free to reopen when needed
