### ISSUE TITLE
File with only requires

### ISSUE THREAD

**Issue by maltepet** [phpDocumentor/phpDocumentor2#1915]
This:

![image](https://user-images.githubusercontent.com/3633108/33278391-6e98951a-d369-11e7-86a8-674217b785b5.png)

results in this:

![image](https://user-images.githubusercontent.com/3633108/33278407-7d333bfc-d369-11e7-866f-7fb0b3ba3480.png)

This:
![image](https://user-images.githubusercontent.com/3633108/33278484-af0018d0-d369-11e7-8104-bee89c05e85b.png)

results in this:
![image](https://user-images.githubusercontent.com/3633108/33278508-c1ff063a-d369-11e7-847a-8f9719e5112f.png)

It appears that a file with only requires in it breaks parsing the docblock

**Comment by jaapio** [comment]
Thanks for reporting, I wrote a testcase to ensure this keeps working in the future. This will be part of our next alpha release.
