### ISSUE TITLE
How to document variable number of arguments for method?

### ISSUE THREAD

**Issue by d-claassen** [phpDocumentor/phpDocumentor2#1916]
According to the PHPDoc v1 manual we used to be able to document a variable number of arguments like so:
```php
/**
 * Sum list of numbers
 * @param int $numbers,... 
 * @return int
 */
function sum(int ...$numbers): int
{
  return count($numbers) ? array_sum($numbers) : 0;
}
```

But this causes these Compilation Errors:

Type|Line|Description
---|----|-------
error | 7 | Name of argument $numbers does not match with the DocBlock's name $numbers,... in \sum()
error | 7 | The type hint of the argument is incorrect for the type definition of the `@param` tag with argument $numbers in \sum()
notice | 7 | Parameter $numbers,... could not be found in \sum()

And I can't find anything about it in the v2 docs. Is this still supported in v2? And if yes, how are we supposed to document it?

**Comment by jaapio** [comment]
It should be supported by v3.0.0-alpha. You can just document it as `...$numbers`
I think the latter should also work in v2.

**Comment by d-claassen** [comment]
`...$numbers` makes the errors go away. It just doesn't seem to reflect in any of the templates. Are any plans to improve that in v3 as well?

**Comment by jaapio** [comment]
Yes we are planning to update the templates as well. But will take some time since some large refactoring is happening right now

**Comment by d-claassen** [comment]
Awesome! Thanks for clearing this up for me.
