### ISSUE TITLE
PHP7 group use declarations

### ISSUE THREAD

**Issue by GinoPane** [phpDocumentor/phpDocumentor2#1918]
Hi!
It seems that group use declarations are not supported at all:

`Parse Error: Syntax error, unexpected '{', expecting T_STRING on line 7 `

![image](https://user-images.githubusercontent.com/3897579/33706206-3e14c7c8-db2b-11e7-9dc6-378c926586e1.png)

IS it planned to implement PHP7 features?

Version is 2.8.5

**Comment by jaapio** [comment]
duplicates #1828

**Comment by GinoPane** [comment]
Cool, thanks! Worth waiting for 3rd version 😄
