### ISSUE TITLE
3.0.0-alpha1: -i parameter only ignores directories, not individual files

### ISSUE THREAD

**Issue by restena-sw** [phpDocumentor/phpDocumentor2#1925]
## Expected Behavior
I'm using the PHAR of 3.0.0-alpha1 with the following command-line:

php ../phpDocumentor-3.0.0alpha1.phar -d . -t phpdoc -i core/phpqrcode.php,vendor,config,tests,translation,tutorials,build

The -i list contains the file core/phpqrcode.php.

I would expect the file to be ignored, i.e. not parsed and no PHPDoc being generated for anything contained in that file (in this case, classes in the global namespace beginning with QR...).

## Actual Behavior

While running, I see:
[...]
Parsing core/Options.php
Parsing core/phpqrcode.php
Parsing core/ProfileFactory.php
[...]

And the HTML output contains all the classes in that file. An example of the generated PHPDoc on my dev server is:

http://ticker.eduroam.lu/cat-trunk/phpdoc/classes/QRcode.html

(see how it's referenced as "File: core/phpqrcode.php"

I have also changed the order of the list in -i to have the file as the last item - but no change.

## Steps to Reproduce the Problem

  1. git clone https://github.com/GEANT/CAT.git
  2. phpdoc with the command-line above
  3. Look at the output

## Your environment

* Version used: 3.0.0-alpha1
* Install method: phar
* php version:
PHP 7.1.12 (cli) (built: Dec  1 2017 13:53:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
* CentOS 7
* Link to your project: https://github.com/GEANT/CAT

**Comment by jaapio** [comment]
Thanks for your report, we will have a look how to resolve this issue. It will be part of alpha2 release.

**Comment by ashnazg** [comment]
https://github.com/phpDocumentor/FlyFinder/pull/5 helped with --ignore working again, but with the caveat that ignore arguments are *relative* to the -d arg dirs, e.g. `-d core -i phpqrcode.php` for the OP's case.  Granted, `-d .` means that all `-i` args are de facto relative, so many users probably won't note the distinction.  However, for args like `-d src/Cilex` here in phpDocumentor2, ignoring the Monolog file would require either the explicitly relative `-i Provider/MonologServiceProvider.php` (relative to the -d arg where the file is located, not relative to the execution dir), or a wildcard `-i */MonologServiceProvider.php`.

Presumably this change won't be visible to phpdoc until after a flyfinder release and phpdoc require deps update.

**Comment by ashnazg** [comment]
(@restena-sw :  last comment still means that your use of `-d . -i core/phpqrcode.php` should be fine... again, after phpdoc picks up the flyfinder update)

**Comment by jaapio** [comment]
Issue is resolved when #1957 is merged
