### ISSUE TITLE
phpDocumentor alpha 3 not generating any document

### ISSUE THREAD

**Issue by NestorAcevedo** [phpDocumentor/phpDocumentor2#1930]
phpDocumentor Alpha 3 is not generating any documentation. Only generates page skeleton.
## Expected Behavior

Normal PHP Documentor generated. Commonly it takes some time to finish.

## Actual Behavior
Generating only page skeleton. Just like the issue https://github.com/phpDocumentor/phpDocumentor2/issues/1874

Commonly when I run phpDocumentor on my project, it takes around 1 minute to achieve the documentation. But in this case only takes less than 1 second

## Steps to Reproduce the Problem

  1. Run phpdocumentor from command line 

## Your environment

PHP7 + MariaDB. Yii Framework 2.0.13

* Version used: 3.0.0-alpha1
* Install method Phar file
* php version 7.1.12
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): openSUSE Tumbleweed 
* Link to your project: Local

**Comment by ashnazg** [comment]
In case it helps... I originally had the same "fast execution, empty docs" behavior yesterday.  My problem turned out to just be running the executable from inside the ./bin dir instead of from the root dir that contained the phpdoc.dist.xml.

Bad result:  `cd phpDocumentor2/bin; ./phpdoc -c ../phpdoc.dist.xml`
Good result:  `cd phpDocumentor2; ./bin/phpdoc -c phpdoc.dist.xml`

Granted, you're probably _not_ executing from a phpDocumentor2 clone, but I did want to highlight the _possibility_ that some unexpected issue with _relative pathing_ might be in play here.

**Comment by ashnazg** [comment]
I'm duplicating this behavior right now, when using any `-d` value except just `.`.  It looks like the underlying file finder logic _does_ see the files in these dirs, _but_ they are not "satisfying the specification" when each file is considered.

**Comment by jaapio** [comment]
I do not completely understand what command you are executing right now.

I found an issue with single file patterns using `-f.` could you add the actual commands you tried. So we can write some tests to check the behavior.

**Comment by ashnazg** [comment]
`./bin/phpdoc -d src -t build` from the root of a phpDocumentor2 clone.

**Comment by NestorAcevedo** [comment]
In my case, I run inside my local bin directory "/home/myuser/bin"
`php phpDocumentor.phar -i "vendor/,console/migrations/" -d "/home/myuser/public_html/myproject" -t "/home/myuser/Documentos/myproject/" --title="My project"`

This same command works perfectly with 2.9.0

**Comment by ashnazg** [comment]
@NestorAcevedo a workaround for you would be this:

```
cd /home/myuser/public_html/myproject
php phpDocumentor.phar -i "vendor/,console/migrations/" -d . -t "/home/myuser/Documentos/myproject/" --title="My project"
```

Right now, the only `-d` arg that I see working correctly is `-d .`.  Any other value specified for `-d` is not working.

I'm still troubleshooting...

**Comment by jaapio** [comment]
Think this one can be closed since #1936 was merged @ashnazg?

**Comment by DurandSacha** [comment]
`php phpdoc.phar -d .` has worked for me. 

- I renamed file for have path with no space and no specials letters

**Comment by achur00** [comment]
this was a great  help, thanks everyone
