### ISSUE TITLE
Undocumented parameters raise an error when inheriting documentation

### ISSUE THREAD

**Issue by robertmain** [phpDocumentor/phpDocumentor2#1948]
I'm currently seeing errors in my generated docs that I haven't documented various parameters etc. when I'm using `{@inheritdoc}`

These errors should be omitted if the parameter documentation is there, but just inherited

## Steps to Reproduce the Problem

  1. Create an interface with docblock'd methods
  2. Create a class that implements this interface

`my_interface.php`
```php
<?php

interface Fooable{
    /**
     * Does Foo
     * 
     * @param String $myParam Example parameter
     * @return void
    */
    public function doFoo($myParam);
}
```

`FooImplementation.php`

```php
<?php

class FooImplementation implements Fooable
{
    /**
     * {@inheritdoc}
    */
    public function doFoo()
    {
        echo 'Foo';
    }
}
```

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 2.x
* Install method: Composer
* php version: 7.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10
* Link to your project: https://github.com/robertmain/UniformCache/blob/clean-slate/src/CacheItem.php#L37-L43

**Comment by jaapio** [comment]
We do know that there is an issue with this in phpdocumentor v2. But we are not able to fix this without major a refactoring. So we solved this issue in phpdoc v3. We are working hard to get a stable version out. A first alpha release is available.
