### ISSUE TITLE
Docker image instructions do not work

### ISSUE THREAD

**Issue by jcchavezs** [phpDocumentor/phpDocumentor2#1950]
The instructions about pulling the docker image does not work

## Expected Behavior

`docker pull phpdoc/phpdoc` works

## Actual Behavior

`docker pull phpdoc/phpdoc` does not work because there is no `latest` tag in [docker hub](https://hub.docker.com/r/phpdoc/phpdoc/tags/).

## Steps to Reproduce the Problem

  1. Run `docker pull phpdoc/phpdoc`

**Comment by jaapio** [comment]
I will update the documentation. But a work around is to specify the version.

`docker pull phpdoc/phpdoc:v3.0.0-alpha1`

**Comment by mikemix** [comment]
`instrumentisto/phpdoc` image is much better, and has more tags available instead of alpha version.

**Comment by jaapio** [comment]
I just fixed the docker build for our master branch. This will provide the latest version of phpdoc/phpdoc.
