### ISSUE TITLE
Way to run phpDoc as part of test stack with exit code of 1 if errors exist

### ISSUE THREAD

**Issue by prodikl** [phpDocumentor/phpDocumentor2#1951]
It would be great if there was a CLI switch that could be added that would make php fail by returning a non-zero exit code if errors exist.

My test stack includes phpStan, phpUnit, codeception, and my CI will stop if any of them return a non-zero exit code. It would be great if I could add phpDoc to the stack to fail if any errors exist.

This would prevent undocumented units from succeeding. It would also be great to do a quick error check before committing my code instead of having to run it, then look at the output for errors.

## Expected Behavior
Would be great if I could run something like

`phpdoc -d ./src --fail`

And have it
1: Fail on error (non-zero exit code)
2: Show errors in cli output for easy actioning

## Actual Behavior
Currently the only way (afaik) to check for errors is to look at the cli output or view the built docs and check the errors page.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: v2.9.0
* Install method: Homebrew
* php version: 7.0.6
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Mac 10.13.2

**Comment by jaapio** [comment]
We have scheduled this request for phpdoc v3. 
https://github.com/phpDocumentor/phpDocumentor2/issues/1032

**Comment by prodikl** [comment]
awesome, looking forward to it!

**Comment by burrellramone** [comment]
I'm looking forward to this as well.

**Comment by ryan7273** [comment]
Also looking forward to it. At the moment, I run phpdoc from a script to get this behavior.
For the others eagerly awaiting this feature:
```
#!/usr/bin/env sh
if [ "$(grep -c 'No errors have been found in this project.' docs/reports/errors.html)" = 0 ]; then
    exit 3
fi
```
