### ISSUE TITLE
PHP7 Nullable Return Types Not Supported

### ISSUE THREAD

**Issue by robertmain** [phpDocumentor/phpDocumentor2#1952]
When running phpdocumentor over a class containing a method that has a nullable return type(see below), it causes the parser to fail to output any documentation for that class

```php
<?php

class User extends ABM
{
    public function save($arg) : ?int
    {
        if ($arg === 25) {
            return $arg;
        } else {
            return false;
        }
    }
}
```

## Expected Behavior
I would expect the nullable status of the return type to be documented

## Actual Behavior
The parser fails to output any documentation for that class

## Steps to Reproduce the Problem

  1. Create PHP file containing the class shown above
  2. Run `phpdoc` with the following command: `phpdoc -f file.php -t docs`

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: dev-master
* Install method: Composer
* php version: 7.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Windows 10
* Link to your project: https://github.com/robertmain/codeigniter-starter

**Comment by jaapio** [comment]
Please switch to 3.0.0-alpha1 to have php7+ support. v2 will not have support for php7+ due some major changed that are required to support php7.

**Comment by robertmain** [comment]
How do I do that? I'm using dev-master in my composer file

**Comment by jaapio** [comment]
you can run `composer require --dev "phpdocumentor\phpdocumentor:v3.0.0-alpha1"`

**Comment by robertmain** [comment]
Thanks. If that's the new recommended version, you may want to update your readme, because that's still saying to install dev-master :)

**Comment by jaapio** [comment]
We do not recommend using master. It is just an example. Normally you want to stick with the latest stable release like every other php package. But it is up to you which exact version you want to use.

The alpha version is a pre release which we cannot recommend. But in this specific case you don't have a choice.

**Comment by robertmain** [comment]
>We do not recommend using master. It is just an example.

It says right here in your installation instructions to use `dev-master`.

![image](https://user-images.githubusercontent.com/537684/36074951-35fb9abc-0f15-11e8-82c1-dda98c9a5576.png)

>Normally you want to stick with the latest stable release like every other php package. 

So, that would be v2 then - which you just told me [here](https://github.com/phpDocumentor/phpDocumentor2/issues/1952#issuecomment-364739616) not to use.

>The alpha version is a pre release which we cannot recommend.

Any news on when v3 is going to drop? Sounds like it should fix a large number of issues with v2

**Comment by jaapio** [comment]
Yes it will fix a lot of issues. But we are changing so much that we will need to do a lot of testing before we can release the final version. A number of alpha versions and beta will follow. We update all internals. And some major refactoring is still in progress.

I can not give you a release date. We are working on v3 for 2 years now. I hope we can finish it this year. But I had the same hope last year :blush:
