### ISSUE TITLE
Cannot generate documentation for classes which have functions with return type declarations.

### ISSUE THREAD

**Issue by montypanday** [phpDocumentor/phpDocumentor2#1977]
## Expected Behavior
Should be able to generate docs for these files.

## Actual Behavior
No documentation generated for file which have a function with return type declared in this way
[](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration)

## Steps to Reproduce the Problem

  1.  public function index(JobRepository $jobRepository): **Response**
    {
        return $this->render('job/index.html.twig', ['jobs' => $jobRepository->findAll()]);
    }

  2.
  3.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 3.0.0-alpha1
* Install method phar
* php version 7.2
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): windows 10
* Link to your project:
* ...
* ...

**Comment by jaapio** [comment]
Could you please explain what you mean with optional return type? 
Do you mean nullable return types?

`function myFuntion() : ?SomeType`

**Comment by montypanday** [comment]
Hi, 
Yes, i mean functions which return value or null.
If i remove the ? It can generate the documentation, otherwise it ignores the class.
I tried with a symfony 4 project with php 7.2 and phpDocumentor phar file.

**Comment by jaapio** [comment]
We have an testcase for this scenario which passes
https://github.com/phpDocumentor/phpDocumentor2/blob/develop/tests/features/core/syntax/php71.feature

So I think there is another reason which it works the way it does right now. Can you provide some example code please?

**Comment by montypanday** [comment]
Hi, you can use the src folder in this [sample symphony](https://github.com/montypanday/Symfony-4-Skeleton). It will miss entities and controllers if they have the ? before the return type in functions

**Comment by mskocik** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/25513620/45600362-c7834980-b9fb-11e8-8910-4c497a6c651f.png)

**Comment by jaapio** [comment]
Issue should be fixed.
Feel free to open a new issue when problem remains.
