### ISSUE TITLE
References to functions in @see and @uses tags are not correctly resolved to FQSEN

### ISSUE THREAD

**Issue by oschildt** [phpDocumentor/phpDocumentor2#1981]
Description: 

References to functions in @see and @uses tags are not correctly resolved to FQSEN.

* Version used: master-dev
* Install method: composer
* php version: 7.2
* Operating system and version: Windows 10

Use this code and generate the doc using clean template:

```php
<?php
/**
 * This file contains utility functions.
 *
 * @package Utility Functions
 */

namespace SmartFactory;

/**
 * Echoes the text with escaping of HTML special charaters.
 *
 * @param string $text 
 * The text to be escaped.
 *
 * @return void
 *
 * @see escape_html()
 *
 * @uses escape_html()
 */
function echo_html($text)
{
  echo escape_html($text);
} // echo_html

/**
 * Escapes the HTML special characters in the text.
 *
 * @param string $text 
 * The text to be escaped.
 *
 * @return string
 * Returns the text with escaped HTML special charaters.
 */
function escape_html($text)
{
  return htmlspecialchars($text, ENT_QUOTES);
} // escape_html
```

## Expected Behavior

There is the doc block for the method echo_html. This block contains the references: 

 * @see escape_html()
 * @uses escape_html()

Both references should be resolved as:

\SmartFactory\escape_html()

## Actual Behavior

Both references are resolved as:

\escape_html()

**Comment by jaapio** [comment]
The issue has been fixed in v3.0.0-alpha3
