### ISSUE TITLE
phpDocumentor E_RECOVERABLE_ERROR could not be converted to string for laravel5.6.11

### ISSUE THREAD

**Issue by pkfactor** [phpDocumentor/phpDocumentor2#1983]
When I run phpdocumentor.phar with the latest version of phar downloaded from http://www.phpdoc.org/phpDocumentor.phar I get the following errors
phpDocumentor.ERROR: E_RECOVERABLE_ERROR: Object of class PhpParser\Node\Stmt\Class_ could not be converted to string {"code":4096,"message":"Object of class PhpParser\\Node\\Stmt\\Class_ could not be converted to string","file":"phar:///Users/apple/pK/code/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php","line":172} []
PHP Recoverable fatal error:  Object of class PhpParser\Node\Stmt\Class_ could not be converted to string in phar:///Users/apple/pK/code/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php on line 172

## Expected Behavior

phpdocumentor should produce the required output api documentation

## Actual Behavior

Currently I get following error 
phpDocumentor.ERROR: E_RECOVERABLE_ERROR: Object of class PhpParser\Node\Stmt\Class_ could not be converted to string {"code":4096,"message":"Object of class PhpParser\\Node\\Stmt\\Class_ could not be converted to string","file":"phar:///Users/apple/pK/code/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php","line":172} []
PHP Recoverable fatal error:  Object of class PhpParser\Node\Stmt\Class_ could not be converted to string in phar:///Users/apple/pK/code/phpDocumentor.phar/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/BaseReflector.php on line 172

## Steps to Reproduce the Problem

  1. Run sudo php phpDocumentor.phar -d ./x -t ./x/doc/api
  2. phpDocumentor starts running
  3. It stops spewing out the above errors

## Your environment

Running on Mac OS 10.13.5
PHP 7.1.16
Laravel 5.6.11
Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 3.0.0-alpha1
* Install method
* php version
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

**Comment by jaapio** [comment]
You are using phpdocumentor 2 which doesn't support php7. We are working hard to release a new version. This will solve your issue. Meanwhile you could try to use our alpha releases.

**Comment by pkfactor** [comment]
Thanks jaapio for the reply. When will the new version release. Where do I download the alpha releases? Will the alpha releases work with php7. 

Thanks

**Comment by crabmusket** [comment]
For any Googlers who find this, there are instructions to install an alpha version [here](https://github.com/phpDocumentor/phpDocumentor#phpdocumentor-v3-under-development). I just tested and it's working great with PHP 7.4!
