### ISSUE TITLE
Add support for connfiguration file `phpdoc.xml.dist`

### ISSUE THREAD

**Issue by filips123** [phpDocumentor/phpDocumentor2#1997]
Add support for connfiguration file `phpdoc.xml.dist`. I know that the phpDocumentor already supports `phpdoc.dist.xml`, but some other projects are using `filename.xml.dist` so it would be great to standardize file names.

phpDocumentor should look to config files in that order:
`phpdoc.xml` `phpdoc.dist.xml` `phpdoc.xml.dist` *or*
`phpdoc.xml` `phpdoc.xml.dist` `phpdoc.dist.xml`

**Comment by jaapio** [comment]
This issue is open for PRs.

**Comment by Samzy** [comment]
Would this require updating both behat features and documentation?

**Comment by jaapio** [comment]
Documentation and unittest should be updated. We are still building a good testsuite for behat. Any additional tests are welcome. But not required for a pr like this

**Comment by filips123** [comment]
Could you also add this to version 2?
Version 3 is still in alpha and I want to version 2 for now.

**Comment by mvriel** [comment]
I have fixed the issue (barring a couple of tests that I need to write) for phpDocumentor 3. Because our focus is currently on phpDocumentor 3 I cannot afford to make these changes for phpDocumentor 2.
