### ISSUE TITLE
Inheritance destroyed

### ISSUE THREAD

**Issue by donbidon** [phpDocumentor/phpDocumentor2#2001]
```
interface MyInterface {
    /**
     * Foo method short description.
     * @return void
     */
    public function foo();
    /**
     * Bar method short description.
     * @return void
     */
    public function bar();
}

abstract class MyAbstract implements MyInterface {
    /**
     * {@inheritdoc}
     */
    public function foo() {}
}

class MyClass extends MyAbstract {
    /**
     * {@inheritdoc}
     */
    public function bar() {}
}
```

## Expected Behavior
.../classes/MyClass.html#method_bar (default template)
Method short description: Bar method short description.
Implements (at right side): \MyInterface

## Actual Behavior
.../classes/MyClass.html#method_bar (default template)
Method short description: {@inheritdoc}
Inherited from (at right side): \MyClass

## Your environment
* Version used: 2.9.1 (same if download phar-file 2.9.0)
* Install method: Composer ( `"require-dev": { "phpdocumentor/phpdocumentor": "dev-master"  }` )
* php version: PHP 7.2.5 (cli) (built: Apr 25 2018 02:19:27) ( NTS MSVC15 (Visual C++ 2017) x64 ) -- no optimizers
* OS: Windows 10 x64
* Project: [Tunneled webhooks](https://github.com/donbidon/tunneled-webhooks)
* [Invalid behavior](https://donbidon.github.io/docs/apps/tunneled-webhooks/classes/donbidon.TunneledWebhooks.Service.ngrok.html#method_getURL)

**Comment by jaapio** [comment]
This is fixed in phpdoc v3. Which is currently in alpha phase. We cannot fix this in phpdoc v2. due limitations in  the code. Interface inheritance doesn't work in v2.
