### ISSUE TITLE
Usage without CLI?

### ISSUE THREAD

**Issue by Bizarrus** [phpDocumentor/phpDocumentor2#2003]
How i can use phpDocumentor without CLI on an main application? The usage is limited to the CLI (see Readme.md, no informations about that in the docs)

## Expected Behavior
Including phpDocumentor in existing projects without CLI usage.

## Actual Behavior
Can't start the phpDoc process. I had try to use it with (ugly) tricks like:

```php
<?php
	require_once('../vendor/include.php');
	
	use phpDocumentor\Bootstrap;
	
	$_SERVER['argv'] = [ 'phpdoc', 'run', '-d', 'test', '-t', 'lol' ];
	
	$app = Bootstrap::createInstance()->registerProfiler()->initialize();
	$app->run();
?>
```

But i want a concrete API to call phpDoc directly.

**Comment by jaapio** [comment]
phpdocumentor is an application that should not be part of an application but can be used as a tool during development. Therefor we will not provide an api to integrate phpdocumentor in an api. The internals will change somehow and we won't provide any feedback on this. 

If you want to use phpdocumentor this way the best solution is the way you already did it. Maybe future development will move us in another direction but for now it will stay an cli only application.
