### ISSUE TITLE
Cannot get XML generated

### ISSUE THREAD

**Issue by niden** [phpDocumentor/phpDocumentor2#2021]
Hey all

I cannot seem to get any XML generated when specifying the said template. If I run the command without the template I do see the docs generated but XML is still a no go for me. 

## Expected Behavior
XML file to be generated

## Actual Behavior
I cannot find the XML file anywhere

## Steps to Reproduce the Problem
  1. Downloaded the https://github.com/phpDocumentor/phpDocumentor2/releases/tag/v3.0.0-alpha.2 file as well as the key
  2. cd to my folder
  3. `$ php phpDocumentor.phar run -d ./src/ -t ./docs/ --template=xml`
  4. No output either in the `docs/` folder or the `build` folder
  5. `$ php phpDocumentor.phar run -d ./src/ -t ./docs/ --template="xml"`
  6. Same thing

## Your environment
* Version used: 3.0.0-alpha2
* Install method: phar
* php version: 7.2
* xubuntu 16.04
* Link to your project: https://github.com/niden/ide-stubs/tree/refactoring-for-phpdoc

Any pointers would be greatly appreciated.

Thank you

**Comment by jaapio** [comment]
Hi Niden,

Thanks for your report. Somehow the xml templates in phpdoc 3 are not working I will start searching why. Will keep you posted.

**Comment by jaapio** [comment]
It turnsout that we missed the xml templates somehow and that there was a bug in the commandline argument handling for templates. 

I checked both issues with our own code base. If you are able to check the latest version in develop that would be nice. There is no phar available yet.

**Comment by niden** [comment]
Thank you! Looking forward to the next release.

**Comment by jaapio** [comment]
We released a new version yesterday. I will close this issue. Feel free to reopen when this issue still exists.
