### ISSUE TITLE
Dependency block when installed via Composer with Laravel 5.7

### ISSUE THREAD

**Issue by mark-emery** [phpDocumentor/phpDocumentor2#2030]
use the command
composer require --dev phpdocumentor/phpdocumentor dev-master
fails with a dependency block. This same nikic/php-phaser issue has blocked other modules in a laravel environment and we were lucky enough the author of those module changed the dependencies and we got the modules installed.

## Expected Behavior
 a version of phpdocumentor/reflection  to require version of nikic/php-phaser ^4.1.0

## Actual Behavior
phpdocumentor/phpdocumentor dev-master requires phpdocumentor/reflection ^3.0 -> satisfiable by phpdocumentor/reflection[3.0.0, 3.0.1, 3.0.x-dev]
phpdocumentor/reflection 3.0.0 requires nikic/php-parser ^1.0 
Installation request for nikic/php-parser (locked at v4.1.0) -> satisfiable by nikic/php-parser[v4.1.0]

## Steps to Reproduce the Problem

  1. Install laravel 5.7
  2. Install phpDocumentor2

**Comment by letrunghieu** [comment]
Honestly, I would recommend against using composer for tools like phpdocumentor as it will pollute your composer dependencies. You should use the phar file instead.
