### ISSUE TITLE
How to insert a simple table to docblock?

### ISSUE THREAD

**Issue by in4s** [phpDocumentor/phpDocumentor2#2035]
I need to show tables at docummentation, like this:

    /**
     * Returns value of a preset key or default value.
     *___________________________________________________________________________
     *                              |    key is defined   |  key is not defined |
     * value is set                 |        value        |XXXXXXXXXXXXXXXXXXXXX|
     * value is not set             |       default       |       default       |
     *___________________________________________________________________________
     * @version v1.0.0 2018-10-17 08:37:52
     * @param string $key - key
     * @param string $default - default value
     * @return string
     */

**Comment by mvriel** [comment]
For Markdown we may use of the Parsedown library, on this page (https://parsedown.org/tests/simple_table) you can find the syntax needed
