### ISSUE TITLE
PHP autoloader in V3 not working

### ISSUE THREAD

**Issue by redaxmedia** [phpDocumentor/phpDocumentor2#2036]
When using V3 Alpha3 as an dependency, your `vendor/bin/phpdoc` fails to load the autoloader.php from composer. If I fix the path to `/../autoload.php` it fails to load the `AnnotationRegistry` by Doctrine.

## Expected Behavior
Just run vendor/bin/phpdoc without errors

## Actual Behavior
```
> vendor/bin/phpdoc
PHP Warning:  require(/home/redaxmedia/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/../autoload.php): failed to open stream: No such file or directory in /home/redaxmedia/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/phpdoc on line 14
PHP Fatal error:  require(): Failed opening required '/home/redaxmedia/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/../autoload.php' (include_path='.:/usr/share/php') in /home/redaxmedia/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/phpdoc on line 14
```

## Steps to Reproduce the Problem

Working example

  1. git clone https://github.com/redaxscript/redaxscript-api-sync.git
  2. composer install
  3. composer run build

**None** working example

  1. git clone https://github.com/redaxscript/redaxscript-api-sync.git
  1. composer require phpdocumentor/phpdocumentor 3.0.0-alpha.3 --dev
  2. composer install
  3. composer run build

## Your environment

PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

## Suggustions

I compared `vendor/bin/phpdoc` to  `vendor/bin/phpcs` and they have a smaller footprint in that file that just contains the kernel to boot up. In other words, you are doing too many things in that file and that might cause issues. Therefore, I suggest to follow the PHPCS pattern.

```
#!/usr/bin/env php
<?php
/**
 * PHP_CodeSniffer detects violations of a defined coding standard.
 *
 * @author    Greg Sherwood <gsherwood@squiz.net>
 * @copyright 2006-2015 Squiz Pty Ltd (ABN 77 084 670 600)
 * @license   https://github.com/squizlabs/PHP_CodeSniffer/blob/master/licence.txt BSD Licence
 */

if (is_file(__DIR__.'/../autoload.php') === true) {
    include_once __DIR__.'/../autoload.php';
} else {
    include_once 'PHP/CodeSniffer/autoload.php';
}

$runner   = new PHP_CodeSniffer\Runner();
$exitCode = $runner->runPHPCS();
exit($exitCode);
```

As you can see, they don't have vendor inside the autoloader path and also some fancy fallback mechanism. This is just an suggestion to learn from the other big players... it's upon you

Thank you

**Comment by rrajkomar** [comment]
Hi, it should be `$loader = require __DIR__.'/../../autoload.php';` to work from any project that required the library.
Also, is is sad that you added the dependency to symfony/framework-bundle... you're basically making your library unusable withour the symfony part :-(
The dependecy to symfony/dotenv could/should be added to the documentation because otherwise if we don't set a APP_ENV var nothing works...

**Comment by rrajkomar** [comment]
@mvriel @jaapio 
Any news on this autoloading issue. this is quite cumbersome. we can't move to the 3.X version because of this.
Personally I had to remove the dependency and all phpdocumentation generation in order to keep moving forward with my application coding...

I'd rather move to a newer version of phpdocumentor sooner than later :-)

**Comment by redaxmedia** [comment]
I tested this with 3.0.0 Alpha-4 and the following error returns

```
PHP Fatal error:  Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in /home/hruhs/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/phpdoc:23
Stack trace:
#0 {main}
  thrown in /home/hruhs/PhpstormProjects/redaxscript-api-sync/vendor/phpdocumentor/phpdocumentor/bin/phpdoc on line 23
Script vendor/bin/phpdoc handling the build event returned with error code 255
```
