### ISSUE TITLE
Suggestion to make type in @param and similar tags optional

### ISSUE THREAD

**Issue by codedokode** [phpDocumentor/phpDocumentor2#2037]
Curently the type in `@param` and `@return` decalaration [is required](https://docs.phpdoc.org/references/phpdoc/tags/param.html). But the type is often specified in function signature, and it causes unnecessary duplication. Duplication is bad because it increases code size, declarations can become inconsistent, and it becomes more difficult to edit the code: 

```php
/** 
* @param int $persons Number of people booking a room 
* @return int A room price per night in euros
*/
function calculateRoomPrice(int $persons): int 
```

I suggest to make type specification optional if the description is present, so that `@param` can be used only to add a description: `@param $persons Number of people booking a room`. Type declaration should be optional even if there is no type hint because it is not required in PHP: 

```php
/** @param $age User's age */
function canSeeContent($age) 
```

For consistency, I suggest to allow omitting type in `@var`, `@property`, `@throws` and `@return` declaration if it has a description: 

```php
/** @var * Price before any discounts and taxes are applied */
private $price;

/** @return * Final price after discounts are applied */
public function calculateFinalPrice(): int
```
The star is used instead of type declaration so that the word "Price" is not interpreted as a type. As an alternative, we could use other character, like `-` or a dot `.` which is easier to type because one doesn't have to press `Shift` key:

```php
@var * Price before discounts are applied
@var - Price before discounts are applied
@var . Price before discounts are applied
```

If this proposal is accepted, I could later try to find time and make necessary changes in the code and documentation.

**Comment by ashnazg** [comment]
@codedokode you'll need to make this suggestion on the php-fig ML in order to get it into discussion -- https://groups.google.com/forum/#!forum/php-fig

If it is adopted by the PSRs, then phpDocumentor will most certainly cater to it.
