### ISSUE TITLE
openssl signature could not be verified

### ISSUE THREAD

**Issue by dingo-d** [phpDocumentor/phpDocumentor2#2039]
I'm trying to install the latest alpha version of the phpDocumentor, but the install fails with the message:

> PHP Fatal error:  Uncaught PharException: phar "/usr/local/bin/phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in /usr/local/bin/phpDocumentor.phar:10

## Expected Behavior
I expect it to be working

## Actual Behavior
When I try to see if it works I get this error

```sh
PHP Fatal error:  Uncaught PharException: phar "/usr/local/bin/phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in /usr/local/bin/phpDocumentor.phar:10
Stack trace:
#0 /usr/local/bin/phpDocumentor.phar(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/local/bin/phpDocumentor.phar on line 10

Fatal error: Uncaught PharException: phar "/usr/local/bin/phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in /usr/local/bin/phpDocumentor.phar on line 10

PharException: phar "/usr/local/bin/phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in /usr/local/bin/phpDocumentor.phar on line 10

Call Stack:
    0.0009     391656   1. {main}() /usr/local/bin/phpDocumentor.phar:0
    0.0009     391656   2. Phar::mapPhar() /usr/local/bin/phpDocumentor.phar:10
```

## Steps to Reproduce the Problem

  1. Download the [phar file](https://github.com/phpDocumentor/phpDocumentor2/releases/download/v3.0.0-alpha.3/phpDocumentor.phar)
  2. Move it to `/usr/local/bin/`
  3. chmod it `sudo chmod +x /usr/local/bin/phpDocumentor.phar`
  4. Try to run `phpdoc --version`

## Your environment

**OS**
```sh
macOS Mojave version 10.14.1 (18B75)
```

**PHP**
```sh
PHP 7.2.10 (cli) (built: Sep 14 2018 07:06:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies
```

**Version used**: 3.0.0-alpha.3
**Install method**: Downloaded phar from the repo

I've also downloaded the pubkey and tried to do 

```sh
openssl verify phpDocumentor.phar.pubkey
```

But this fails with

```sh
unable to load certificate
4712818284:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.200.4/libressl-2.6/crypto/pem/pem_lib.c:683:Expecting: TRUSTED CERTIFICATE
```

**Comment by jaapio** [comment]
You need to store the pubkey file with the name `phpDocumentor.phar.pubkey` in the same dir as you stored the phar file. 

Please let me know when you have any issues.

**Comment by dingo-d** [comment]
Yup, just read this on one of the articles and now it seems to be working (the version at least). Wasn't aware of the signing. Thanks!
