### ISSUE TITLE
Is it possible to extend the class hierarchy diagram?

### ISSUE THREAD

**Issue by dingo-d** [phpDocumentor/phpDocumentor2#2040]
Currently, when I see the generated diagram, I can see boxed namespaces and connections which is great. But from the diagram itself it's a bit hard to see what is an interface for instance. You cannot see if it has constructor, what methods are present etc.

Is it possible to expand on the class diagram generation with some configuration options?

Maybe to look more like the diagrams generated by phpstorm:

![screenshot 2018-12-05 at 11 43 50](https://user-images.githubusercontent.com/8638515/49508545-482b4680-f883-11e8-86df-883df7c58914.png)

Current look:

![screenshot 2018-12-05 at 11 44 09](https://user-images.githubusercontent.com/8638515/49508552-4c576400-f883-11e8-8029-6cfdfb34615e.png)

**Comment by jaapio** [comment]
Hi @dingo-d,

Thanks for your request. I'm not sure how this can be done but I think there must be a way with a custom plugin to do this. However it won't be an easy task. I think the easiest way to do this is write a custom template based on xml which transforms the xml into a format that is understood by a tool like plantuml to generate a diagram. But I have never seen anyone doing this before. And I don't have time to help you with it right now.

The type of arrows used in the diagram do actually tell you the relation type between classes. Dotted lines are interface implementations. The solid lines are inherited classes. And interface can extend an other interface, in this case it is a solid line. But any class implementing the child interface will have the dotted relation.

**Comment by dingo-d** [comment]
> The type of arrows used in the diagram do actually tell you the relation type between classes. Dotted lines are interface implementations. The solid lines are inherited classes. And interface can extend an other interface, in this case it is a solid line. But any class implementing the child interface will have the dotted relation.

Didn't know this, thanks for the explanation, it actually helps a lot 🙂.

I'll see what can be done. I've been looking at a lot of plantuml packages but none of them seem to be working with PHP7+, and that's a big problem 😬 

THanks for the response :+1:
