### ISSUE TITLE
Memory has been rising

### ISSUE THREAD

**Issue by okou19900722** [phpDocumentor/phpDocumentor2#2042]
## Expected Behavior

build success

## Actual Behavior

Travis failed because the output log was too long. Local test memory has been rising

## Steps to Reproduce the Problem

mvn clean package phpdoc-local

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: v2.8.5, v3.0.0-alpha.2-nightly-gdff5545
* Install method
* php version : 7.2.5
* maven: 3.5.3
* jdk 8
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): windows 10
* Link to your project: https://github.com/vert-x-cn/vertx-lang-jphp/tree/9a0337bbdf417a9ee33c42e3fb769a4a2dcc0a05
* travis : https://travis-ci.org/vert-x-cn/vertx-lang-jphp/builds/466782352
* ...

**Comment by mvriel** [comment]
It would seem that phpDocumentor went into infinite recursion when it tried to determine the hierarchy of types. Unfortunately, I have been unable to find the cause file that would cause this to happen. It also doesn't help that I do not seem to be able to find the PHP files in that project.

Are you able to find the offending PHP file by running phpdocumentor against a smaller set and provide us with a link to that file or its contents?

**Comment by okou19900722** [comment]
run `mvn clean package phpdoc-local` will generate php source

**Comment by jaapio** [comment]
Please give the newer 4-alpha release a try and reopen the issue when needed.
