### ISSUE TITLE
php7.2  app.ALERT:   Unable to parse file "Namspace/Interface.php", an error was detec ted: Expected a different value than "". [] []

### ISSUE THREAD

**Issue by ALexeyP0708** [phpDocumentor/phpDocumentor2#2043]
phpdoc v3. Alpha 3 -php7.2 Windows 8.1
If an error occurs, the file will not be parsed any further.  missing interface (or class) in  list of interfaces (classes) .
The cause. Random empty @param parameter in method description.
R rkfccfv 'nf ghj,ktvf nj;t jnyjcbncz
```php
   	/**
         * Title
         * Description
         * 
	* {@see http://link/}  
	 * @param         
         * @param int $level  
         * @param int $optname  
         * @param mixed $optval  
         * 
         * @return bool
         */
         function(int $level,int $optname,$optval):bool;
```

**Comment by mvriel** [comment]
This issue is now resolved in the latest version on develop. Instead of a whole file failing to be included we now silently ignore the invalid tag
