### ISSUE TITLE
Template "xml" crashes if a @param tag is missing the type

### ISSUE THREAD

**Issue by fi5er** [phpDocumentor/phpDocumentor2#2044]
I have a method where the type and parameter name were accidentally switched. Instead of

    /**
     * @param  bool  $sortDesc
     */
    public function testMethod (bool $sortDesc) {}

the doc block was

    /**
     * @param  $sortDesc  bool
     */
    public function testMethod (bool $sortDesc) {}

It appears that phpDocumentor sees "bool" as the parameter description, and (nothing) as the type. Any other text than "bool" also causes the same crash.

The parsing stage runs successfully, but transforming for the "xml" template fails with the following error:

    ...
    [2018-12-23 12:39:09] app.INFO:   Writer xml  on structure.xml [] []
    [2018-12-23 12:39:09] app.INFO:   Execute transformation using writer "xml" [] []

    In ArgumentConverter.php line 52:

      [ErrorException]
      Warning: Invalid argument supplied for foreach()

    Exception trace:
     phpDocumentor\Plugin\Core\Transformer\Writer\Xml\ArgumentConverter->convert() at /home/user/git/phpDocumentor2/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml/MethodConverter.php:74
     phpDocumentor\Plugin\Core\Transformer\Writer\Xml\MethodConverter->convert() at /home/user/git/phpDocumentor2/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:393
     phpDocumentor\Plugin\Core\Transformer\Writer\Xml->buildClass() at /home/user/git/phpDocumentor2/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:198
     phpDocumentor\Plugin\Core\Transformer\Writer\Xml->buildFile() at /home/user/git/phpDocumentor2/src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php:140
     phpDocumentor\Plugin\Core\Transformer\Writer\Xml->transform() at /home/user/git/phpDocumentor2/src/phpDocumentor/Transformer/Transformer.php:287
     phpDocumentor\Transformer\Transformer->applyTransformationToProject() at /home/user/git/phpDocumentor2/src/phpDocumentor/Transformer/Transformer.php:253
     phpDocumentor\Transformer\Transformer->transformProject() at /home/user/git/phpDocumentor2/src/phpDocumentor/Transformer/Transformer.php:137
     phpDocumentor\Transformer\Transformer->execute() at /home/user/git/phpDocumentor2/src/phpDocumentor/Application/Stage/Transform.php:147
     phpDocumentor\Application\Stage\Transform->__invoke() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
     League\Pipeline\FingersCrossedProcessor->process() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/Pipeline.php:34
     League\Pipeline\Pipeline->process() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/Pipeline.php:39
     League\Pipeline\Pipeline->__invoke() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/FingersCrossedProcessor.php:11
     League\Pipeline\FingersCrossedProcessor->process() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/Pipeline.php:34
     League\Pipeline\Pipeline->process() at /home/user/git/phpDocumentor2/vendor/league/pipeline/src/Pipeline.php:39
     League\Pipeline\Pipeline->__invoke() at /home/user/git/phpDocumentor2/src/phpDocumentor/Application/Console/Command/Project/RunCommand.php:249
     phpDocumentor\Application\Console\Command\Project\RunCommand->execute() at /home/user/git/phpDocumentor2/vendor/symfony/console/Command/Command.php:251
     Symfony\Component\Console\Command\Command->run() at /home/user/git/phpDocumentor2/vendor/symfony/console/Application.php:904
     Symfony\Component\Console\Application->doRunCommand() at /home/user/git/phpDocumentor2/vendor/symfony/framework-bundle/Console/Application.php:89
     Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /home/user/git/phpDocumentor2/vendor/symfony/console/Application.php:262
     Symfony\Component\Console\Application->doRun() at /home/user/git/phpDocumentor2/vendor/symfony/framework-bundle/Console/Application.php:75
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/user/git/phpDocumentor2/vendor/symfony/console/Application.php:145
     Symfony\Component\Console\Application->run() at /home/user/git/phpDocumentor2/bin/phpdoc:44

This was a test run with a source directory containing only a single class file with only the method given above. The command line was:

    /home/user/git/phpDocumentor2/bin/phpdoc run
        --directory /path/to/TestDir
        --target out-transform
        --template xml
        --force
        -vvv

I'm running `phpdoc` v3.0.x-dev@ee92b8f directly from the git directory ("develop" branch, up to date at the time of writing) on Kubuntu 18.04, PHP version is 7.2.10.

**Comment by jaapio** [comment]
Fixed with #2050
