### ISSUE TITLE
Using PHP keywords as method name

### ISSUE THREAD

**Issue by MAChitgarha** [phpDocumentor/phpDocumentor2#2055]
I want to document a class (the link to the project exists in the Environment section) that has a method named `JSON::isSet()`. When I want to document it using phpDocumentor, the following error will be shown and the documentation will not be created successfully:

`Parse Error: Syntax error, unexpected T_ISSET, expecting T_STRING on line 307  No summary was found for this file`

Since PHP methods are case-insensitive, maybe phpDocumentor think the method as `JSON::isset()`, a PHP keyword. It may think a PHP keyword as method name is an error; however, as of PHP7, it is possible to do that ([see this RFC](https://wiki.php.net/rfc/context_sensitive_lexer)).

How to overcome the problem? Is there any quick fix for this?

__Note__: When I comment the `JSON::isSet()` definition or I change its name to something else (e.g. `JSON::is_set()`) and run the same command, the documentation will be created successfully.

## Environment
* Version used: 2.9.0
* Installed using PHAR
* PHP 7.2
* Ubuntu 18.10
* Project: https://github.com/MAChitgarha/JSON

**Comment by MAChitgarha** [comment]
Sorry, please delete this issue. Something went wrong.

**Comment by jaapio** [comment]
Hi, 

Thanks for you report. I thing you have to switch to phpdoc v3. We had issues like this we could not fix in phpdoc v2. V3 is still in alpha phase but should be stable enough to handle a library like yours. 

Please let me know if this solves your issue.

**Comment by MAChitgarha** [comment]
Hi, @jaapio!
Thanks for the new version. The problem fixed. However, it doesn't import protected methods in the documentation.

**Comment by jaapio** [comment]
This issue is fixed with #2056

**Comment by nelson6e65** [comment]
Thanks! I'll check. :smiley:
