### ISSUE TITLE
Improve error message when using phpDocumentor v3 without public key

### ISSUE THREAD

**Issue by Tilogorn** [phpDocumentor/phpDocumentor2#2061]
## Expected Behavior

1. Downloading `phpDocumentor.phar` and using it
2. A nice and friendly message tells me to download the OpenSSL-Public Key to the same directory

```
$ php phpDocumentor.phar
You can't use phpDocumentor.phar without providing a valid public key in the same directory called "phpDocumentor.phar.pubkey". 
You can find it on our download page: https://github.com/phpDocumentor/phpDocumentor2/releases
```

## Actual Behavior

1. Downloading `phpDocumentor.phar` and using it
2. Getting an ugly error
3. Googling the issue "phpDocumentor.phar" openssl signature could not be verified". Landing [here](https://github.com/phpDocumentor/phpDocumentor2/issues/2039)
4. Knowing what to do

```
$ php phpDocumentor.phar
PHP Fatal error:  Uncaught PharException: phar "phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in phpDocumentor.phar:10
Stack trace:
#0 phpDocumentor.phar(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown inphpDocumentor.phar on line 10
```

## Steps to Reproduce the Problem

  1. Download current alpha
  2. Execute it

## Your environment

* Version used: 3.0.0-alpha3
* PHAR-File
* 7.2.10
* Linux Mint 19

**Comment by jaapio** [comment]
we are switching to PGP signed phars. see #2028, this will make this issue invalid.
