### ISSUE TITLE
Cache Files

### ISSUE THREAD

**Issue by cryogenx** [phpDocumentor/phpDocumentor2#2064]
Is it ok to delete the cache files? parser cache?

## Expected Behavior
I would expect the script to do some cleanup

## Actual Behavior
every time I run it a new cache dir is created

## Steps to Reproduce the Problem

  1. run phpdoc

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 2.9.1
* Install method : Composer
* php version 7.1.19
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): OSX Mojave 10.14.2

**Comment by jaapio** [comment]
To speed up the execution of phpdocumentor, we are using several layers of cache. If you want phpdocumentor to ignore the cache you can use the `--force` flag. The parser cache dir can be configured in your configuration file. 

```
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor>
    <parser>
        <default-package-name>phpDocumentor</default-package-name>
        <target>build/api-cache</target>
    </parser>
```
phpdocumentor does not cleanup the created cache directories.

**Comment by ve3** [comment]
Is it possible to change **build** directory to other? I tried to change config via command line or xml but not working.
