### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by horgh** [phpDocumentor/phpDocumentor2#2069]
## Expected Behavior

I tried using the latest .phar from Releases, but I'm seeing #2053. I tried to build a phar from the repo, but `make` errors out (`File ".travis/phpdoc-phar.pem" was expected to exist.`).

Would it be possible to do a release with the more recent fixes? Thank you!

Alternatively, are there instructions for building the phar, or running the version from the repo directly?

## Actual Behavior

Running phpdoc from phar fails (version v3.0.0-alpha.3) with #2053.

## Your environment

* Version used: v3.0.0-alpha.3
* Install method: phar
* php version: 7.2.15-0ubuntu0.18.10.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): Ubuntu 18.10
* Link to your project: https://github.com/maxmind/GeoIP2-php

**Comment by jaapio** [comment]
I just published a new version of the alpha 4 release. Please let me know if you have any issues.
