### ISSUE TITLE
Uncaught PharException: phar   Phar::mapPhar('box-auto-genera...') #1 {main}

### ISSUE THREAD

**Issue by yangliuan** [phpDocumentor/phpDocumentor2#2075]
problem
when I execute:
php phpDocumentor.phar -d /home/yangliuan/Code/Study/larajob/vendor/laravel/horizon/ -t ./horizon

Uncaught PharException: phar "/home/yangliuan/Downloads/phpDocumentor.phar" openssl signature could not be verified: openssl public key could not be read in /home/yangliuan/Downloads/phpDocumentor.phar:10
Stack trace:
#0 /home/yangliuan/Downloads/phpDocumentor.phar(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /home/yangliuan/Downloads/phpDocumentor.phar on line 10

* Version used: 3.0.0-alpha2
* Install method  phar
* php version PHP 7.2.13
* Operating system and version Ubuntu 18.04

**Comment by jaapio** [comment]
I recommend you to use alpha v3. You need to place the pub key file next to the phar file
