### ISSUE TITLE
inheritdoc normal tag

### ISSUE THREAD

**Issue by MatTheCat** [phpDocumentor/phpDocumentor2#2076]
In https://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag it is said

> we are working to include a new (normal) tag in the PHPDoc Standard `@inheritDoc` that will serve that purpose.

Seems no issue has been submitted following https://github.com/phpDocumentor/phpDocumentor2/pull/1612#issuecomment-305889652 so here I go.

Could it be added to v3?

**Comment by jaapio** [comment]
Inheritdoc is under discussion in psr-5. We are aware of the unclear specs of the interitance of docblocks and their tags.

First of all the current behavior of phpdoc v3 and v2 need to checked. To see how inheritdoc works at this moment. In the past years we have seen several misinterpreted usecases in the wild. Adding another tag wouldn't make it much clearer.

I cannot state that we will implement a new tag for this purpose at the moment.

**Comment by MatTheCat** [comment]
> I cannot state that we will implement a new tag for this purpose at the moment.

In that case as `{@inheritdoc}` seems to be widely used as a block tag will it be considered as valid?

**Comment by jaapio** [comment]
Yes, we will keep support for `{@inheritdoc}` but at this moment it is unclear which tags will be included in the inheritance. But when things are changing that won't be done without a release of PRS-5 :-D so you are safe to use `{@inheritdoc}`
