### ISSUE TITLE
[DOCS LACKING] Either add `@const` or actually show how to document constants!

### ISSUE THREAD

**Issue by WadeShuler** [phpDocumentor/phpDocumentor2#2078]
If you research the topic on how to document class constants, you will find countless people saying to use `@const` because they found it in old, alpha/beta, german docs.

`@const` is not valid, it should be `@var`.

I honestly think `@const` just needs to be officially added, it makes the most sense.

Example within a class, using the proper `@var` tag:

```
/**
 * @var string APP_NAME The name of the application
 */
const APP_NAME = 'My Cool App';
```

> The @var tag MUST contain the name of the element it documents. An exception to this is when property declarations only refer to a single property. In this case the name of the property MAY be omitted.

So we can get by with `@var string The name of the application`. However, I wonder how popular IDE's handle/support this? Atom, VS Code, Netbeans, PHP Storm, etc.? Meaning, is there a need to pass the elements name for support in any of the mainstream editors?

If so, then it just needs to be required/standard to pass the element name. This will ensure projects/libraries (once majorly adopted over time) that we use will have better support out of the box with IDE's.

I know with some IDE's, people have to do a little hackery to get some of the comments to show up... So we could stand to bridge this gap.

---

**Alternatively**, maybe it is time to just officially add a `@const` tag? Then the IDE's can specifically handle constants a lot easier.

---

Is this project even maintained anymore? I saw really old issues, on top of them piling up (over 250 issues), and on the website, there are multiple 404s...

**Comment by jaapio** [comment]
The discussion of adding a new tag is not in the scope of phpdocumentor but more in the line of the PSR-19 working group. I would recommend you to contact them. https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md 

The project is more than alive. There are multiple project at github with the age of phpdocumentor that have the same amount of issues. We are not a commercial organization. So mostly things are moving slowly.
