### ISSUE TITLE
document network requests

### ISSUE THREAD

**Issue by hlb-schmidt** [phpDocumentor/phpDocumentor2#2079]
i got this class method:
```
public function deleteTabAction ()
{
	$tabId = (int) $this->Request()->get("tabId");
	
	...

	$this->redirect("/foo/bar/");
}
```

how do we document:
- network `GET` variable `tabId`?
- "return" is `301` redirect to `/foo/bar`?
- client/frontend url of this method?

**Comment by mvriel** [comment]
Hello,

phpDocumentor is intended for documenting code and not network interaction. I can recommend taking a look at tools like Swagger or NelmioApiDocBundle that build upon the PHPDoc standard to provided this for you.
