### ISSUE TITLE
Some ignore elements in configuration ignored

### ISSUE THREAD

**Issue by Jelmerb** [phpDocumentor/phpDocumentor2#2082]
I have two directories I want to ignore in the source directory (namely `Migrations` and `Repository`). The `Migrations` directory gets ignored in the HTML output but the `Repository` directory not. This is my configuration file (phpdoc.dist.xml). 

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor>
    <parser>
        <target>docs</target>
    </parser>
    <transformer>
        <target>docs</target>
    </transformer>
    <files>
        <directory>src</directory>
        <ignore>src/Kernel.php</ignore>
        <ignore>src/Migrations/*</ignore>
        <ignore>src/Repository*</ignore>
    </files>
    <title>SEAD Documentation</title>
</phpdocumentor>
```

## Expected Behavior

I expected the `Repository` directory to get ignored in the HTML output. 

## Actual Behavior

The `Repository` directory is displayed in the HTML output like nothing is configured. 

## Steps to Reproduce the Problem

  1. Create a src folder at the root of a project
  2. Create two directories in the root folder, `Migrations` and `Repository`.
  3. Use the configuration file above
  4. Run PHPDoc with the configuration file from the root of the project 
  5. Check the HTML output

## Your environment

* Version used: dev-develop
* Install method
Using composer outside of the project 
* php version
7.3.4
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
MacOS 10.14.4
* Folder structure:
```
sead->src->Controller
sead->src->Entity
sead->src->EventListener
sead->src->Form 
sead->src->Migrations
sead->src->Repository
sead->src->Service
sead->src->Validator
sead->phpdoc.dist.xml
```

**Comment by jaapio** [comment]
I think this will work when you just specify the path without `*`

**Comment by Jelmerb** [comment]
Really weird, I saw I made a mistake in the configuration file that I posted. The ignore element says `src/Repository*` but it should be `src/Repository/*`. I swear I had it like this before and it didn't work but now it works. Sorry for waisting your time.

**Comment by jaapio** [comment]
No problem. Glad it works for you.

**Comment by Jelmerb** [comment]
Well, I am playing with it a little more, and now it ignores the ignore element again. With or without the `*` in the path. Could it be that something is cached somewhere?

**Comment by jaapio** [comment]
Not that I'm aware of. But the processed code is cached. So if you are changing the config I would recommend removing the cache manually. We still need to work on that part, so phpdocumentor will do this automatically.

**Comment by Jelmerb** [comment]
I did this with `phpdoc cache:clear`, but that didn't work either. Cleared the cache of my browser too.

**Comment by mvriel** [comment]
Since at this point there is little that we can do for this issue I am going to close it for now. If you have more info, please let us know and we'll reopen the issue and continue with it

**Comment by Jelmerb** [comment]
I will. Last week, I used PhpDocumentor again, and it ignored the directories like I expected. I still have no clue what happened

**Comment by asmecher** [comment]
In case this helps someone else -- if you've generated the documentation, added an excluded directory, and then generated the documentation again, any documentation that was previously generated and is now excluded may still be hanging around your documentation output directory. If you're reloading a now-excluded file expecting it to disappear, it won't (unless you remove your output directory's contents). However, it will become orphaned (i.e. it won't be linked from the rest of the documentation).

**Comment by MLIMG** [comment]
there is a param --force as i remember.
this will purge the cache and also should solve that issue.

**Comment by asmecher** [comment]
@MLIMG, this is not a cache issue; when you add new path exclusions and re-run phpDocumentor, the cache will be updated successfully. But extra output files that were already generated from a previous phpDocumentor run will not be removed from the output directory.

**Comment by mvriel** [comment]
@asmecher you are right, cleaning the build folder is, by-design, not done by phpDocumentor. This is similar to how other tools manage their build folders and was implemented this way the application does not know whether files in the build folder were intentionally added prior to phpDocumentor -for example: PDFs- or not.

Since phpDocumentor also does not keep a record of previously created files; we simply do not know whether it is safe to delete a file.

**Comment by MLIMG** [comment]
> @MLIMG, this is not a cache issue; when you add new path exclusions and re-run phpDocumentor, the cache will be updated successfully. But extra output files that were already generated from a previous phpDocumentor run will not be removed from the output directory.

got it
