### ISSUE TITLE
Setting up web interface on debian with nginx

### ISSUE THREAD

**Issue by Dagobert57** [phpDocumentor/phpDocumentor2#2089]
Hello,
I tried to set up phpdoc on a machine with debian 9.9, nginx 1.10.3 and php 7.0.33. The webserver is configured to /media/RAID/www on port 8080. My other php projects in this directory do not make any trouble. I expected to see the web interface under [nas:8080/phpDocumentor](url).

But when I visit nas:8080/phpDocumentor I get the error "403 Forbidden".

I did the following (see also [https://gist.github.com/benlk/82f3c1e63167548a0a43#file-setup-md](url)):
  1. sudo apt-get install php-pear
  2. sudo pear config-set data_dir /media/RAID/www
  3. sudo pear channel-discover pear.phpdoc.org
  4. sudo pear install phpdoc/phpDocumentor
  5. sudo mkdir /media/RAID/www/phpdoc-output
  6. cd /media/RAID/www/
  7. sudo chown www-data:www-data phpdoc-output

I am wondering why in the directory /media/RAID/www/phpDocumentor there is no file with an extension "html" or "php". The output of
ls -l /media/RAID/www/phpDocumentor is the following:

drwxrws---+  3 root users   4096 Mai 11 17:52 ansible
-rw-r--r--+  1 root users   4726 Mai 11 17:52 box.json
-rw-r--r--+  1 root users  21406 Mai 11 17:52 CHANGELOG.md
-rw-r--r--+  1 root users   2835 Mai 11 17:52 composer.json
-rw-r--r--+  1 root users 143470 Mai 11 17:52 composer.lock
-rw-r--r--+  1 root users   7468 Mai 11 17:52 CONTRIBUTING.md
 drwxrws---+  7 root users   4096 Mai 11 17:52 features
-rw-r--r--+  1 root users    845 Mai 11 17:52 phpmd.xml.dist
-rw-r--r--+  1 root users   5357 Mai 11 17:52 README.md
-rw-r--r--+  1 root users   1043 Mai 11 17:52 Vagrantfile
drwxrws---+ 24 root users   4096 Mai 11 17:52 vendor
-rw-r--r--+  1 root users   1853 Mai 11 17:52 wercker.yml

Are there any files missing? Which file shall be opened if I visit [nas:8080/PhpDocumentor](url)? I would be very greatful if someone could help me.

**Comment by ashnazg** [comment]
PhpDocumentor does not provide a web interface... it is strictly CLI.
