### ISSUE TITLE
Docker: Add /opt/phpdoc/bin to $PATH

### ISSUE THREAD

**Issue by MyIgel** [phpDocumentor/phpDocumentor2#2092]
## Expected Behavior
It would be nice if I could directly run `phpdoc` in the container.

## Actual Behavior
Because `/opt/phpdoc/bin` is not in the `$PATH` i have to use `/opt/phpdoc/bin/phpdoc` to call it

## Your environment
I use the `phpdoc/phpdoc:v3.0.0-alpha.3` Docker container with `--entrypoint bash` in my CI.

* Version used: v3.0.0-alpha.3
* Docker

**Comment by mvriel** [comment]
I have added this request to the Dockerfile; so with the next build of the docker image this will be in place.
