### ISSUE TITLE
Return value of getTypes()  must implement interface Type or be null error.

### ISSUE THREAD

**Issue by ve3** [phpDocumentor/phpDocumentor2#2097]
I'm running the command `phpDocumentor.phar --directory="src" --cache-folder="../../_cache" --target="../../_doc-simple-cache"` and get this error message.

## Expected Behavior

Expect that phpDocumentor will generate the document properly.

## Actual Behavior

Get this error message.

> Return value of phpDocumentor\Descriptor\Tag\BaseTypes\TypedAbstract::getTy
>   pes() must implement interface phpDocumentor\Reflection\Type or be null, in
>   stance of phpDocumentor\Descriptor\Collection returned

## Steps to Reproduce the Problem

  1. Open command prompt.
  2. Run `phpDocumentor.phar --directory="src" --cache-folder="../../_cache" --target="../../_doc-simple-cache"`
  3. Then get this error message.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 3.0.0-alpha3
* Install using **phpDocumentor.phar** and **phpDocumentor.phar.pubkey**
* PHP 7.1.26
* Windows 10 x64
* I try to generate doc from this project. https://github.com/Rundiz/simple-cache

**Comment by ve3** [comment]
OK, it seems that this is because of cache from previous version (phpdoc 2).
Clear all cache, doc and generate fresh new doc again working fine.

**Comment by jaapio** [comment]
Thanks for the heads up. We could check if it is needed to warn about this :-)
