### ISSUE TITLE
phpstan incompatibility

### ISSUE THREAD

**Issue by MockingMagician** [phpDocumentor/phpDocumentor2#2101]
## Expected Behavior

Upgrade nikic/php-parser package version to v4 in phpdocumentor.

## Actual Behavior

Installation is incompatible with phpstan library cause both require nikic/php-parser package. phpstan require at least v4 when phpdocumentor require only v1

## Steps to Reproduce the Problem

  1. Install phpstan
  2. Try to install phpdocumentor

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.
Since many issue might only occur on a specific code base it would be very helpfull if you link to your project
or add any code that is involved in to the issue.

* Version used: 2.9
* Install method composer
* php version 7.2
* Operating system and version: Ubuntu 18.04

**Comment by jaapio** [comment]
We are not supporting any conflict on composer packages. We cannot be compatibel with all framework versions and packages out there. 

Please use the phar install or docker image.
