### ISSUE TITLE
[v3.0.0-alpha.3] @return type not being documented

### ISSUE THREAD

**Issue by o-alquimista** [phpDocumentor/phpDocumentor2#2107]
For example, this is the getNumResults() method:
```
    /**
     * @return int
     */
    public function getNumResults(): int
    {
        return $this->numResults;
    }
```
And this is what gets documented:
![Captura de tela de 2019-08-03 20-40-06](https://user-images.githubusercontent.com/25424263/62417764-e9df7f00-b62e-11e9-86b7-2899d8cf2b43.png)

It is the same on all other methods in this file, except for one of them where the return type is `\Traversable`:
![Captura de tela de 2019-08-03 20-44-28](https://user-images.githubusercontent.com/25424263/62417786-81dd6880-b62f-11e9-8f9e-00aefcd6448d.png)

**Comment by jaapio** [comment]
Issue is solved in alpha 4.
