### ISSUE TITLE
[v3.0.0-alpha.3] No properties are being documented

### ISSUE THREAD

**Issue by o-alquimista** [phpDocumentor/phpDocumentor2#2108]
This is an example from an Entity object, which is full of documented properties:
![Captura de tela de 2019-08-03 20-47-25](https://user-images.githubusercontent.com/25424263/62417804-f87a6600-b62f-11e9-8c07-667c83f5d285.png)

None were found. None of my files' properties are found, only constants (their descriptions are missing though).

Here's another file, with a constant and multiple private properties:
![Captura de tela de 2019-08-03 20-54-34](https://user-images.githubusercontent.com/25424263/62417843-ecdb6f00-b630-11e9-8ff6-c9d7fa724e22.png)

phpDocumentor v2 was able to detect them properly.

Here's a sample code from the file where that constant is:
```
    /**
     * @var int The number of items displayed on a single page
     */
    private const PAGE_SIZE = 10;

    /**
     * @var int
     */
    private $currentPage;

    /**
     * @var \Traversable A traversable object containing the paginated results
     */
    private $results;

    /**
     * @var int The total number of items retrieved from all pages
     */
    private $numResults;
```

System specs:
Ubuntu 19.04
PHP 7.2.19-0ubuntu0.19.04.1
PHAR file of v3.0.0-alpha.3 of phpDocumentor
GraphViz 2.40.1-6

**Comment by jaapio** [comment]
Fixed in alpha 4
