### ISSUE TITLE
Pipe-delimited exceptions in try-catch break phpdoc

### ISSUE THREAD

**Issue by WoodrowShigeru** [phpDocumentor/phpDocumentor2#2109]
I am getting this error.

```
Parse Error: Syntax error, unexpected '|', expecting T_VARIABLE on line 136
```

## Steps to Reproduce the Problem

```
// 1. Write this in a file:
try {} catch (Exception|ArgumentOutOfRangeException $ex) {}

// 2. Compare with:
try {} catch (Exception $ex) {} catch (ArgumentOutOfRangeException $ex) {}
```

## Your environment

* Ubuntu 18.04.2
* LAMP, Server version: Apache/2.4.29 (Ubuntu), Server built:   2019-07-16T18:14:45
* PHP 7.2.19
* phpDocumentor 2.9.0, installed manually by downloading the [tar-ball][tar] from the releases tab of this github.

[tar]: https://github.com/phpDocumentor/phpDocumentor2/archive/v2.9.0.tar.gz

**Comment by jaapio** [comment]
This is syntax is incorrect,  for php 5, the php parser in phpdoc v2 only supports php syntax up to php 7.0. This syntax notation was added in php 7.1 

If you want to parse a php 7.1+ project you will need to use the latest alpha version of phpdocumentor. We are not yet at a stable level with php 7 support

**Comment by WoodrowShigeru** [comment]
Ok, gotcha. Thanks.
