### ISSUE TITLE
Pear repo broken?

### ISSUE THREAD

**Issue by andocodes** [phpDocumentor/phpDocumentor2#2110]
## Expected Behavior
Expecting to install phpDocumentor via PEAR. 

## Actual Behavior
Channel does not seem to exist.

## Steps to Reproduce the Problem

  1. `pear channel-discover pear.phpdoc.org`

**Comment by mvriel** [comment]
There seems to be a DNS issue; we will investigate it

**Comment by mvriel** [comment]
The issue is resolved, the PEAR repo is available again
