### ISSUE TITLE
Feature Request: New Tag for functions which `die()` or `exit()`

### ISSUE THREAD

**Issue by Narimm** [phpDocumentor/phpDocumentor2#2128]
Not an issue per se more a request for a new tag standard to indicate a function that never returns ie it calls either `exit()` or `die()`.

My suggestion would be to either make the `@return` tag a hard requirement  - rather than the current standard that it is implied to be `@return self` on constructors or ``@return void` on other methods

OR alternatively, look at using a new tag `@noreturn` to indicate functions which `die()`;

I appreciate your consideration.

**Comment by mvriel** [comment]
As discussed on the mailing list: I do not see capacity in our time nor the urgent need for this. As an alternative, I recommend using your own custom tag (which is supported by phpDocumentor; just pick on :))
