### ISSUE TITLE
Enable inline references to structural elements

### ISSUE THREAD

**Issue by hschletz** [phpDocumentor/phpDocumentor2#357]
phpDocumentor allows creating inline references to structural elements, like this:

```
{@link method()}
```

With the now implemented inline link feature, it is possible to emulate this, like:

```
{@link #%5cclass::method() method()}
```

This is ugly and gets even worse when linking to a different file.

It would be nice to have a simpler solution available in DocBlox.

**Comment by jaapio** [comment]
Need to check if this is already possible. Think it is now.

**Comment by jaapio** [comment]
After reading this again I don't really understand what the requested feature is. It is possible to link to an element using `@link` and provide and description. Same way the `@see` tags supports this. So I think this is resolved over the years.
