### ISSUE TITLE
Implement @example tag

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#48]
The example tag needs to be implemented as described here:
http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.example.pkg.html

-Additionally the output needs to be parsed by GeSHi-
[SyntaxHighlighter](http://alexgorbatchev.com/SyntaxHighlighter/) should be included with the template to do ad hoc Syntax Highlighting of the source

**Comment by jaapio** [comment]
looks like thins one can be closed?

**Comment by hive** [comment]
http://www.phpdoc.org/docs/latest/references/phpdoc/tags/example.html

As far as I can see, this still does not support inline examples. 

"To do an inline code example, use the html tag <code> or the new inline {@example} tag"

**Comment by mvriel** [comment]
I agree with @jaapio; this issue is directly related to the 'normal' `@example` tag and should thus be closed. A new issue can be opened for the inline variant
