### ISSUE TITLE
Support for global @package description

### ISSUE THREAD

**Issue by Yuav** [phpDocumentor/phpDocumentor2#549]
I find myself wanting to write a top level description of @package components, such that you can easily see description of what the package in its entirety is meant to do. Can this be done?

**Comment by DannyvdSluijs** [comment]
Is this still relevant after so many time ?

**Comment by mvriel** [comment]
@DannyvdSluijs this specific issue (description) is no longer fully relevant as a functionality is planned for phpDocumentor 3 that will help provide a complete documentation solution. Thank you for making me aware of this

**Comment by DannyvdSluijs** [comment]
Tribute to Codetriage mailing me random tickets to see if I can help.
