### ISSUE TITLE
Does not recognize page-level DocBlock on "empty" files

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor2#604]
I am running a basic model-view-controller approach. My project contains lots of template files that have a page-level DocBlock, but then continue in plain HTML without any PHP functionality.

Here is an example:

```
<?php

/**
 * 404.php
 * Copyright 2012 Jan Nikolas Jansen <email removed>
 * 
 * This file is part of Projectname
 * 
 * Projectname is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * Projectname is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Projectname. If not, see <http://www.gnu.org/licenses/>.
 */

?>

<h1>Oops</h1>
<p>The document you are looking for could not be found.</p>
```

**Comment by ashnazg** [comment]
@mvriel since the nikic/php-parser fix was put in its v2.1.0, will our fix be possible in the 2.x line?  Or will the dependency requirements of Reflection to gain php-parser 2.x or 3.x end up forcing phpDocumentor to 3.x or higher?

**Comment by jaapio** [comment]
I think we can't fix this in v2. If an upgrade of php parser is required. It will remove the option to run on php 5.3. Which we marked as a bc break. 

Needs to be scheduled for v3

**Comment by ashnazg** [comment]
Ah, so it is php-parser's own PHP minimum that changed between its 1.x and 2.x that is constraining us... ouch.

**Comment by jaapio** [comment]
Yes, and we decided to skip php parser v2 and move to v3 directly. Since v2 does not have any additional features we need right now.
