### ISSUE TITLE
Add support for multi-type array notation

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#607]
The PhpDoc specification states that an array containing multiple types may be  denoted using the following notation:

``` php
@return (integer|string)[]
```

This notation is not yes supported by phpDocumentor and should be added

**Comment by jaapio** [comment]
Needs a test to check if this is already working as expected

**Comment by jaapio** [comment]
it turns out that our type resolver supports this from version 0.5.0 and needs an new release of reflection-docblock. Currently waiting for some feedback on a build error I have in reflection-docblock.

**Comment by ashnazg** [comment]
@jaapio think this one is ok to merge now?  I've done several release updates of TypeResolver and ReflectionDocBlock, and phpDocumentor2 has those updates now.

**Comment by ashnazg** [comment]
@jaapio think this one is ok to merge now? I've done several release updates of TypeResolver and ReflectionDocBlock, and phpDocumentor2 has those updates now.
