### ISSUE TITLE
Improvement suggestion in short description parsing logic

### ISSUE THREAD

**Issue by ghost** [phpDocumentor/phpDocumentor2#621]
If you have short description like

<pre>
/**
 * My function is super cool, i.e. very good.
 * This is because I wrote it very carefully.
 */
</pre>

This will end up as
description = My function is super cool, i.
long-description = e. very good. This is because....

IMO it makes sense to use logic like this
If first docblock line ends in [.?!] the whole line is short description.
If it ends in comma or other character it is multiline short description and
should end on the next [.?!] character.

Regards,
bobef

**Comment by jaapio** [comment]
caused by https://github.com/phpDocumentor/ReflectionDocBlock/issues/63
Closing it here since this is not an issue of phpdocumentor itself
