### ISSUE TITLE
Suggestion: Auto-Expand-on-Click Should be Moved to an Icon

### ISSUE THREAD

**Issue by sstringer** [phpDocumentor/phpDocumentor2#635]
Currently, when you click on a function or class name in phpDocumentor, it auto-expands the contents and details.  When you click again, it collapses back to the summary.

My suggestion is to move this auto-expand/collapse functionality to an icon on the sidebar next to the function/class name.  That way, it will be possible to click or double-click on a word to copy it to the clipboard. For instance, let's say you want to copy the function name so you can paste it into your code in another window.  This isn't currently possible without triggering the collapse function.

Thanks,
Steve

**Comment by jaapio** [comment]
Closing this one, since it is a few year old. Please comment on this issue when you find it still applicable.
