### ISSUE TITLE
Investigate whether we can replace GraphViz with Dagre

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/phpDocumentor2#765]
https://github.com/cpettitt/dagre/

**Comment by jaapio** [comment]
Closing since Dagre is not maintained anymore

**Comment by safareli** [comment]
@jaapio there is still some activity in https://github.com/dagrejs/dagre and I was not able to find any note that repo is not maintained any more, do you have a link to any "this lib is not  maintained anymore" notice ?

**Comment by safareli** [comment]
Ah looks like it was at some point not maintained but that note has been removed https://github.com/dagrejs/dagre/commit/f5e622c61331feac1107070728c3b4d7035196d0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by jaapio** [comment]
My comment is also 3 years old. So this could be around the same date.

Phpdocumentor itself is moving away from graphiz as pure lib. Instead we are exploring plantuml which is more suitable for the features we want to build.

**Comment by Potherca** [comment]
@jaapio If you run into any issues with PlantUML, I humbly offer my services, as I am becoming quite an expert! :grin:

**Comment by jaapio** [comment]
Thanks @Potherca I will try to remember that. 
An example of what we are currently doing with phpDocumentor can be found here: https://docs.phpdoc.org/3.0/guide/internals/flow.html  which is the rendered version of https://github.com/phpDocumentor/phpDocumentor/blob/master/docs/internals/flow.rst#the-flow-in-more-detail
