### ISSUE TITLE
Upgrading from version 1 template ...

### ISSUE THREAD

**Issue by lsces** [phpDocumentor/phpDocumentor2#923]
OK I have http://lsces.org.uk/bitweaverdocs3 building, and it's throwing a lot of errors, but I can look at them at leisure. The next step is to get back to the clean and more readable format of the older template we were using. It does not help that I can't remember what the layout was called, but http://lsces.org.uk/bitweaverdocsPHP 

In particular, the class layout as http://lsces.org.uk/bitweaverdocsPHP/wiki/BitBook.html allows one to see straight off where a class developed from and pick back up the chain, but http://lsces.org.uk/bitweaverdocs3/classes/BitPage.html is simply not as directly readable?

**Comment by jaapio** [comment]
this one looks pretty old to me. Phpdocumentor 2 is already a long time stable. Version 3 is in development. Please feel free to open an issue when you still have any issues regarding the usages of phpdocumentor. We are very pleased to help you.

**Comment by lsces** [comment]
If you can provide a way of mirroring http://lsces.org.uk/bitweaverdocsPHP/fisheye/FisheyeImage.html and the rest of the bitweaver class hierarchy then I might be able to move from 1.5 over to 2, but as yet I do not see any way of creating a full 1.x style hierarchy?

**Comment by jaapio** [comment]
There is a way to do this. I think you need to spend some time to convert your template but it should be possible. The snippet below shows you how to create a tree like you had. But in this case with namespaces. You can do the same thing for classes. 

You could have a look at our `clean` template. That contains most of the elements you need. If you need any help regarding your template please feel free to ask,

```twig
<ul class="breadcrumbs no-bg no-border">
    {% set namespace = node.namespace %}
    {%  if not namespace %}
        {% set namespace = node.parent %}
    {%  endif %}
    {% block namespace_breadcrumb %}
        {% if namespace %}
            {% set child = namespace %}
            {% set namespace = namespace.parent %}
            {{ block('namespace_breadcrumb') }}
            <li><a href="{{ child|route('url')|raw }}">{{ child.name }}</a></li>
        {% endif %}
    {% endblock %}
    <li class="current" >
        <a href="{{ node|route('url')|raw }}">{{ node.name }}</a>
    </li>
</ul>
```

**Comment by lsces** [comment]
My problem jaaplo is that 'my template' is simply one of many bog standard 1.x templates that give the proper hierarchy. What I am missing in '2' stock templates is any indication on where a function is overridden, and more usefully where a parent class has a number of variant child classes. Having to learn YET ANOTHER templateing system to make something work again is just adding to the already excessive code re-factoring simply to keep perfectly functional code working.
